### ISSUE TITLE
Update README links and build instruction

### ISSUE THREAD

**Issue by calvintam236** [xmrig/xmrig-amd#1]
can you update README? Links are linked to `xmrig-nvidia`.
do you have build instruction for `xmrig-amd`?

**Comment by mxjoe** [comment]
I think you can stick to the xmrig-nvidia build instructions.

**Comment by xmrig** [comment]
Build instruction not yet available. I fixed wrong link in README.
Thank you.

**Comment by metalurgus** [comment]
>  I fixed wrong link in README
Looks like you didn't. At least now the build link (https://github.com/xmrig/xmrig-amd/wiki/Build) redirects to the repository home page

**Comment by xmrig** [comment]
https://github.com/xmrig/xmrig/releases/tag/v4.0.0-beta

**Comment by Jschwartz89** [comment]
xmr-usa.dwarfpool.com:8005
