### ISSUE TITLE
No more WIKI, https://github.com/xmrig/xmrig-amd/wiki/Build

### ISSUE THREAD

**Issue by bizlevel** [xmrig/xmrig-amd#103]
All is gone!
Build now is only in memory and own playbooks.

**Comment by Tohelo101** [comment]
Any helps for build amd version on linux ?

**Comment by bizlevel** [comment]
No need, i can, but this only now absent wiki and etc. Not good!

**Comment by xmrig** [comment]
https://github.com/xmrig/xmrig/releases/tag/v4.0.0-beta
