### ISSUE TITLE
GPU Compute errors

### ISSUE THREAD

**Issue by hvcmartins** [xmrig/xmrig-amd#112]
Hello xmrig,
Thanks for the great development of your app.
I tried to update to xmrig-amd 2.6.1 but I'm having a lot of GPU compute errors in every GPU. No errors at all with 2.5.1.
I'm using Ubuntu 16.04.4 LTS (GNU/Linux 4.4.0-122-generic x86_64) under amdgpu-pro-18.10-572953.
Thanks for your reply

**Comment by rswingle** [comment]
same issue on 18.04 with the amdgpu-pro 18.20 drivers. I think the drivers are the issue because I had no issues until I upgraded from 16.04 with amdgpu-pro 17.50 drivers.

**Comment by bananajamma** [comment]
the 18.20 drivers gave me nothing but trouble, try downgrading to 18.10, or the blockchain 17.40 ones.

**Comment by cryptonote-social** [comment]
yeah getting the same thing with 18.20 drivers not working for me either on ubuntu with RX 570 8gb cards

**Comment by calvintam236** [comment]
I'm seeing the same problem with ROCm 1.8.2-192 as well..

**Comment by xmrig** [comment]
https://github.com/xmrig/xmrig/releases/tag/v4.0.0-beta
