### ISSUE TITLE
How to disable iGPU?

### ISSUE THREAD

**Issue by emailyc** [xmrig/xmrig-amd#114]
I have a Ryzen 3 2200G with Vega 8 graphics. I also have four Vega 56 which I will mine with. Is there a way to prevent the Vega 8 from mining ? I keep getting blue screen and I suspect it's the iGPU.

**Comment by k0ste** [comment]
You should not declare index with this gpu in threads configuration.

**Comment by emailyc** [comment]
Is it possible to declare gpu index before first start up (right after compile)? The config files are only generated on first start up but that runs my iGPU to determine the suggested values for GPU auto configuration. That's when it BSOD and even though the files are generated (after BSOD), I'm not sure whether the configuration is proper.

**Comment by k0ste** [comment]
> Is it possible to declare gpu index before first start up (right after compile)?
Yes.

**Comment by emailyc** [comment]
So I just place a config file in the build directory and it won't create a new one automatically ?

**Comment by k0ste** [comment]
> So I just place a config file in the build directory and it won't create a new one automatically ?

Yes.

**Comment by emailyc** [comment]
so now I'm able to start without the iGPU. But with 4 vega 56, I'm getting no greater than 4k h/s.
intensity at 1920, worksize 8.
