### ISSUE TITLE
Error CL_OUT_OF_HOST_MEMORY when calling clCreateCommandQueueWithProperties.

### ISSUE THREAD

**Issue by takasungi** [xmrig/xmrig-amd#115]
start with error

Error CL_OUT_OF_HOST_MEMORY when calling clCreateCommandQueueWithProperties.

Failed to start threads

**Comment by k0ste** [comment]
What is your environment?

**Comment by xmrig** [comment]
https://github.com/xmrig/xmrig/releases/tag/v4.0.0-beta
