### ISSUE TITLE
error: "Unauthenticated", code -1

### ISSUE THREAD

**Issue by Fusridi** [xmrig/xmrig-amd#116]
![image](https://user-images.githubusercontent.com/33223881/40946554-61ac9ed4-685e-11e8-9b5f-d9d7168cd416.png)
I can't mine with "Xmrig-amd 2.6.1" but I can mine with "xmrig 2.6.2"

**Comment by xmrig** [comment]
https://github.com/xmrig/xmrig/releases/tag/v4.0.0-beta
