### ISSUE TITLE
make fail

### ISSUE THREAD

**Issue by mercwhite** [xmrig/xmrig-amd#118]
mac@mac-PC MINGW64 /e/soft/xmrig-amd-master/xmrig-amd-master/build
$ make
Scanning dependencies of target xmrig-amd
[  2%] Building CXX object CMakeFiles/xmrig-amd.dir/src/api/Api.cpp.obj
[  5%] Building CXX object CMakeFiles/xmrig-amd.dir/src/api/ApiState.cpp.obj
[  7%] Building CXX object CMakeFiles/xmrig-amd.dir/src/api/NetworkState.cpp.obj
[ 10%] Building CXX object CMakeFiles/xmrig-amd.dir/src/App.cpp.obj
[ 12%] Building CXX object CMakeFiles/xmrig-amd.dir/src/Console.cpp.obj
[ 15%] Building CXX object CMakeFiles/xmrig-amd.dir/src/Cpu_stub.cpp.obj
[ 17%] Building CXX object CMakeFiles/xmrig-amd.dir/src/log/ConsoleLog.cpp.obj
[ 20%] Building CXX object CMakeFiles/xmrig-amd.dir/src/log/FileLog.cpp.obj
[ 22%] Building CXX object CMakeFiles/xmrig-amd.dir/src/log/Log.cpp.obj
[ 25%] Building CXX object CMakeFiles/xmrig-amd.dir/src/net/Client.cpp.obj
[ 27%] Building CXX object CMakeFiles/xmrig-amd.dir/src/net/Job.cpp.obj
[ 30%] Building CXX object CMakeFiles/xmrig-amd.dir/src/net/Network.cpp.obj
[ 32%] Building CXX object CMakeFiles/xmrig-amd.dir/src/net/strategies/DonateStr           ategy.cpp.obj
[ 35%] Building CXX object CMakeFiles/xmrig-amd.dir/src/net/strategies/FailoverS           trategy.cpp.obj
[ 37%] Building CXX object CMakeFiles/xmrig-amd.dir/src/net/strategies/SinglePoo           lStrategy.cpp.obj
[ 40%] Building CXX object CMakeFiles/xmrig-amd.dir/src/net/SubmitResult.cpp.obj
[ 42%] Building CXX object CMakeFiles/xmrig-amd.dir/src/net/Url.cpp.obj
[ 45%] Building CXX object CMakeFiles/xmrig-amd.dir/src/amd/OclCLI.cpp.obj
[ 47%] Building CXX object CMakeFiles/xmrig-amd.dir/src/amd/OclGPU.cpp.obj
[ 50%] Building CXX object CMakeFiles/xmrig-amd.dir/src/Options.cpp.obj
[ 52%] Building CXX object CMakeFiles/xmrig-amd.dir/src/Platform.cpp.obj
[ 55%] Building CXX object CMakeFiles/xmrig-amd.dir/src/Summary.cpp.obj
[ 57%] Building CXX object CMakeFiles/xmrig-amd.dir/src/workers/OclWorker.cpp.ob           j
[ 60%] Building CXX object CMakeFiles/xmrig-amd.dir/src/workers/OclThread.cpp.ob           j
[ 62%] Building CXX object CMakeFiles/xmrig-amd.dir/src/workers/Handle.cpp.obj
[ 65%] Building CXX object CMakeFiles/xmrig-amd.dir/src/workers/Hashrate.cpp.obj
[ 67%] Building CXX object CMakeFiles/xmrig-amd.dir/src/workers/Workers.cpp.obj
[ 70%] Building CXX object CMakeFiles/xmrig-amd.dir/src/xmrig.cpp.obj
[ 72%] Building RC object CMakeFiles/xmrig-amd.dir/res/app.rc.obj
gcc: error: Files\: No such file or directory
gcc: error: \(x86\)/AMD\: No such file or directory
gcc: error: APP\: No such file or directory
gcc: error: SDK/2.9-1/include: No such file or directory
C:\msys64\mingw64\bin\windres.exe: preprocessing failed.
make[2]: *** [CMakeFiles/xmrig-amd.dir/build.make:455：CMakeFiles/xmrig-amd.dir/           res/app.rc.obj]  error 1
make[1]: *** [CMakeFiles/Makefile2:68：CMakeFiles/xmrig-amd.dir/all] error 2
make: *** [Makefile:84：all] error 2

**Comment by xmrig** [comment]
Fixed.
