### ISSUE TITLE
cmake failed in CentOS 7

### ISSUE THREAD

**Issue by tujuhion** [xmrig/xmrig-amd#119]
Hello,

I try to build xmrig-amd in centos 7 with driver of gpu amdgpu-pro-18.10, but I have error when cmake, here the error message

=======
CMake Warning at cmake/OpenCL.cmake:53 (find_package):
  By not providing "FindOpenCL.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "OpenCL", but
  CMake did not find one.

  Could not find a package configuration file provided by "OpenCL" with any
  of the following names:

    OpenCLConfig.cmake
    opencl-config.cmake

  Add the installation prefix of "OpenCL" to CMAKE_PREFIX_PATH or set
  "OpenCL_DIR" to a directory containing one of the above files.  If "OpenCL"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  CMakeLists.txt:148 (include)
=======

Anyone know how to fix this...? I see installed opencl because I get output when I type clinfo.

Regard's
Yanwar P

**Comment by yanwarpurnama** [comment]
Hi,

I solve this issue with follow https://medium.com/2sync/intall-xmr-stak-on-centos-7-x-c7e4b46277f9

1. Download and install git clone https://github.com/fireice-uk/xmr-stak-cpu.git
2. Install with yum
yum update -y
yum -y install epel-release
yum -y install centos-release-scl cmake3 hwloc-devel libmicrohttpd-devel openssl-devel git screen nano
yum -y install libmpc-devel mpfr-devel gmp-devel
yum --enablerepo=centos-sclo-rh-testing install devtoolset-7-gcc devtoolset-7-gcc-c++
scl enable devtoolset-7 bash
3. Install from source:
git clone https://github.com/xmrig/xmrig-amd.git
cd xmrig-amd
mkdir build
cmake3 ..
make

Done :)

**Comment by xmrig** [comment]
https://github.com/xmrig/xmrig/releases/tag/v4.0.0-beta
