### ISSUE TITLE
Cryptonight-XTL algorithm for stellite?

### ISSUE THREAD

**Issue by bananajamma** [xmrig/xmrig-amd#120]
I see this has already been implemented in the CPU version, any idea when the `xmrig-amd` and `xmrig-nvidia` variants will support this algorithm?

https://github.com/xmrig/xmrig/issues/581

**Comment by asylum119** [comment]
This would be great +1

**Comment by xmrig** [comment]
Released in **v2.7.0-beta**.
Thank you.
