### ISSUE TITLE
How to correctly config AMD RX460/560

### ISSUE THREAD

**Issue by septuig** [xmrig/xmrig-amd#121]
How to correctly config below three GPUs, why is the hashrate of RX560(4G 1024sp) less than RX460(4G 896sp) . Thank you in advance.

AMD RX460 2G 896sp
Current configuration: intensity:760 (if i increase it, the software will hang)
Hashrate: 301H/s

AMD RX460 4G 896sp
Current configuration: intensity:896 (if i increase it, the hashrate will decrease.)
Hashrate:322H/s

AMD RX560 4G 1024sp
Current configuration: intensity:896 (if i increase it, the hashrate will decrease.)
Hashrate: 309H/s

**Comment by Bojan023** [comment]
There are many factors that influence hashrates so there is no clear answer to your question. Try different vbios, frequencies, voltages or memory timings. Just try and error. Good luck!

**Comment by xmrig** [comment]
https://github.com/xmrig/xmrig/releases/tag/v4.0.0-beta
