### ISSUE TITLE
 Build instructions-link dead

### ISSUE THREAD

**Issue by sheepchen** [xmrig/xmrig-amd#122]
Hi,

under Download (clone) the link "Build instructions." brings you nowere.

**Comment by emailyc** [comment]
would be nice to see a thorough compiling instruction

**Comment by xmrig** [comment]
Actually build instructions exactly same with CPU miner https://github.com/xmrig/xmrig/wiki/Build exept only one additional step, install AMD APP SDK 3.0.
Thank you.

**Comment by xmrig** [comment]
https://github.com/xmrig/xmrig/releases/tag/v4.0.0-beta
