### ISSUE TITLE
Masari/MSR limited support

### ISSUE THREAD

**Issue by xmrig** [xmrig/xmrig-amd#128]
Unlike other cryptonight algorithms in Masari variant changed iterations count, with limitations of OpenCL platform it means:

* Miner not able switch in runtime between `cn/msr` and all other `cn/*` algorithms.
* Miner not able switch in runtime to `cn/msr` from other `cn/*` algorithms.
* `cn/msr` should set only via global `algo` option.

These restrictions only applied to OpenCL/AMD miner, CPU miner can switch between all cryptonight variants.

**Comment by bananajamma** [comment]
Unfortunate limitation.  Thank you for sharing.  Does this also mean a new release with MSR support soon? (~19 hours until MSR's fork)

**Comment by andygajetzki** [comment]
I'm not able to successfully mine MSR with 2.7.1-beta. All submitted shares come back as 'low share difficulty'. Is there something besides -a cn and --variant=msr that I need to be using? The CPU miner works correctly with those flags on the same pool. Cheers!

**Comment by bananajamma** [comment]
Use `--algo=cn/msr`, not `--variant`

**Comment by andygajetzki** [comment]
Still no luck. I do not get the 'low share difficulty' error anymore, but in hindsight,  I suspect I was banned for submitting invalid shares for a few hours after the fork. Using either --algo=cn/msr or the previously mentioned arguments results in 'n/a' being displayed for the hash rate. No further messages are provided. This is on pool.masaricoin.com. Would it be useful for me to provide network traffic transcriptions?

**Comment by xmrig** [comment]
This issue not actual anymore, all restrictions solved in v2.7.3-beta.
