### ISSUE TITLE
gpu compute error cryptonight-lite

### ISSUE THREAD

**Issue by pomwtin** [xmrig/xmrig-amd#13]
Hy

I have a problem on few of my older rigs, built from old amd HD GPUs.
Using xmrig I still mannage to get almost 4 Hashes per watt for xmr, so I decided to try aeon too.
After reconfiguration and algo change I can not get past by gpu compute error in case of cryptonite-lite.
I even undo bios modifications, error still occurs, meanwhile I can mine aeon on another amd miner, so I'd say hardware is capable of it.
Is there anything I can do? Cards are HD 5970

**Comment by semtex41** [comment]
I am starting to wonder if this is an issue dependent on the driver. I am seeing the same complaint with both XMRig/2.4.3-beta2 libuv/1.14.1 OpenCL/2.0 MSVC/2017 and xmr-stak 2.2.0. In my case, I am using a HD 6890, but I was forced to use the older ATI driver (v15.200.1062.1004). 
GPU #0 Compute Error for days.

**Comment by thedobe** [comment]
@semtex41 Are you saying by using the 15.200.1062.1004 driver the compute errors go away while mining cryptonight-lite? I have the 15.200.1062.1004 drivers installed and still receiving the errors. :(

**Comment by semtex41** [comment]
@thedobe Yes, exactly.

**Comment by semtex41** [comment]
Belay my last. The error does NOT go away. 
The compute error persists as changing the driver didn’t help.

**Comment by thedobe** [comment]
@semtex41 Ahh okay. I feel your pain as well then. Haha. 💃 

I was curious if the errors would stop and ran the miner for about thirty minutes. It turned out about one to two accepted shares per every fifty-sixty compute errors per card. Oh well.

**Comment by maxstl** [comment]
Heeeeelp ,my hd6870, 6850 and 6770 says gpu compute error only on cryptonight lite algo ,pls fix this

**Comment by maxifri** [comment]
same for me.. i got 6990 rig and 6950 ... same story...

**Comment by asylum119** [comment]
I was getting an error on xmrig-amd which failed the GPU initialisation when using the cryptonight-light algo, the error ended up being persistent even when changing back to an algo that previously worked prior to a recent compile.

My fix was to remove the ".cache" dir so  ended up putting it in the miners start up script like so (I run xmrig-amd from desktop so have no .cache conflicts to worry about when deleting)

If [ -d '.cache' ]; then
  rm -r '.cache'
fi
# load the miner

Not sure if that helps anyone

**Comment by xmrig** [comment]
https://github.com/xmrig/xmrig/releases/tag/v4.0.0-beta
