### ISSUE TITLE
Very long start time

### ISSUE THREAD

**Issue by MetallianFR68** [xmrig/xmrig-amd#130]
Hi,

I'm the lucky owner of 24 VEGA 56 cards.
Each card takes around 12 seconds to initialize in XMRIG-AMD
This takes a very long time to restart the miner, for example if I want to change from LOKI to SUMO

CASTXMR takes less than 1 second per card to initialise.
Why is there such a difference ?
It seems that CASTXMR doesn't recompile everytime.

Is there a way to implement this on XMRIG ?
CASTXMR is great but it crashes al lot more than XMRIG

**Comment by xmrig** [comment]
OpenCL cache already added in dev branch and will be available in v2.7.1-beta release later today.
How OpenCL cache works:
1. On first run miner compile OpenCL code from source as usual, it takes long time.
2. Miner store compiled code on file system.
3. Precompiled code loaded from file system, it much faster.

**Comment by xmrig** [comment]
Implemented in v2.7.1-beta release.
Thank you.
