### ISSUE TITLE
"cryptonight-lite" hash self-test failed.

### ISSUE THREAD

**Issue by yyfong0918** [xmrig/xmrig-amd#131]
With non-AES CPU,
xmrig-amd.exe will report ""cryptonight-lite" hash self-test failed." 
I need to completely disable "selftest" with "return true" to bypass this error.

Please check, thanks.

>  * VERSIONS     XMRig/2.7.0-beta libuv/1.20.3 OpenCL/2.0 gcc/7.3.0
>  * CPU                  Intel(R) Pentium(R) CPU G2030 @ 3.00GHz x64 -AES
>  * ALGO         cryptonight-lite, donate=1%

**Comment by xmrig** [comment]
Fixed, thank you.

**Comment by yyfong0918** [comment]
It is OK now, and the new oclcache is excellent!

**Comment by naphtha88** [comment]
I have the same error but for gosthrider algo (on arm64) ![Screenshot_20211201-180339](https://user-images.githubusercontent.com/14175333/144280567-b9ae834d-3137-4a8d-b74e-74757562d556.png)
