### ISSUE TITLE
XMRig new options problem

### ISSUE THREAD

**Issue by weltall666** [xmrig/xmrig-amd#133]
Hello! I'm trying to use your -c config.json command with awesome miner and despite it works with 2.6.1, when I change the exe for 2.7.0 with new options strided_index and memory_chunk, it closes automatically.

I know its a problem with awesome miner since I cant start properly via exe or cmd file, but I really like using awesome miner profit profile.

That said, I wish you could make these options (along comp_mode) switches for command line, or maybe see a workaround to use config.json option on awesome, altough I'd prefer the first option, I really wish to use them as command line options, like:

--opencl-platform=0 --stridedindex=2 memchunk=8 compmode=true --opencl-devices=0,0,1,1 --opencl-launch=1152x8,1152x8,1152x8,1152x8

Is there a way to do this!? Thanks in advance!!!

Oh, sorry I was forgetting:

Everytime I start xmrig again, it compiles each gpu again. When I use xmr-stak or srbminer, they save a file for each gpu (xmr-stak on program data and srb on files inside its folder), is there a way to make xmrig saves those precompiled files for each gpu??? I waste a lot of time recompiling when I switch the algo (awesome miner doesnt do it automatically like in proxy, at least I dont know how) neither after a crash. It would be very good having pre compiled files.

**Comment by weltall666** [comment]
Hello. I tried adding pool and config.json on command line and I got the same problem. This is happening only on 2.7 and 2.7.1.

**Comment by BobbyGR** [comment]
Confirmed same issue here, trying to run *.exe -o pool.etn.spacepools.org:3333 -u <ADDRESS HERE> -p x --api-port 33999 --donate-level 1 --variant 1 -a cryptonightv7 --opencl-platform=1 --opencl-devices=0,0,1,1,2,2,3,3,4,4,5,5 --opencl-launch=864x8,864x8,864x8,864x8,864x8,864x8,864x8,864x8,864x8,864x8,864x8,864x8

This no longer works in the new version, it forces the config file

**Comment by weltall666** [comment]
I was ignored, try creating a New comment Bobby maybe you are answered
