### ISSUE TITLE
Halved hash rate

### ISSUE THREAD

**Issue by emailyc** [xmrig/xmrig-amd#134]
[2018-06-19 11:45:54] |      0 |   1 |   973.4 |     n/a |     n/a |[0m
[2018-06-19 11:45:54] |      1 |   2 |   973.0 |     n/a |     n/a |[0m
[2018-06-19 11:45:54] |      2 |   3 |   974.7 |     n/a |     n/a |[0m
[2018-06-19 11:45:54] |      3 |   4 |   970.7 |     n/a |     n/a |[0m

So I'm getting exactly half the hash rate then I'd get in Cast XMR or SRBminer for each of my vega 56
Here is my config.
I omittedmy first gup as it is the iGPU and including it give me a TDL failure (Ryzen 3 2200g w/ vega 8)

{
    "algo": "cryptonight",
    "api": {
        "port": 0,
        "access-token": null,
        "worker-id": null,
        "ipv6": false,
        "restricted": true
    },
    "background": false,
    "cache": true,
    "colors": true,
    "donate-level": 1,
    "log-file": null,
    "opencl-platform": 0,
    "pools": [
        {
            "url": "pool.monero.hashvault.pro:7777",
            "user": "47v2jiCRGzpXebTVZrjtcqQEe92JZkLRM1Z54q4qYZTWGeDvaBA4uc5R3SXjpZx2z8F93TS4BpGauWuuQ9g8mBnBEpGwKQF",
            "pass": "myXMRig",
            "rig-id": null,
            "nicehash": false,
            "keepalive": true,
            "variant": 1
        }
    ],
    "print-time": 60,
    "retries": 5,
    "retry-pause": 5,
    "threads": [
        {
            "index": 1,
            "intensity": 1792,
            "worksize": 8,
            "strided_index": 1,
            "mem_chunk": 2,
            "comp_mode": true,
            "affine_to_cpu": false
        },
        {
            "index": 2,
            "intensity": 1792,
            "worksize": 8,
            "strided_index": 1,
            "mem_chunk": 2,
            "comp_mode": true,
            "affine_to_cpu": false
        },
        {
            "index": 3,
            "intensity": 1792,
            "worksize": 8,
            "strided_index": 1,
            "mem_chunk": 2,
            "comp_mode": true,
            "affine_to_cpu": false
        },
        {
            "index": 4,
            "intensity": 1792,
            "worksize": 8,
            "strided_index": 1,
            "mem_chunk": 2,
            "comp_mode": true,
            "affine_to_cpu": false
        }
    ],
    "user-agent": null,
    "syslog": false,
    "watch": false
}

**Comment by xmrig** [comment]
Use double threads and increase intensity, usually values near 1932 is good.
Example:
```json
"threads": [
    {
        "index": 1,
        "intensity": 1932,
        "worksize": 8,
        "strided_index": 1,
        "mem_chunk": 2,
        "comp_mode": true,
        "affine_to_cpu": false
    },
    {
        "index": 1,
        "intensity": 1932,
        "worksize": 8,
        "strided_index": 1,
        "mem_chunk": 2,
        "comp_mode": true,
        "affine_to_cpu": false
    },
    {
        "index": 2,
        "intensity": 1932,
        "worksize": 8,
        "strided_index": 1,
        "mem_chunk": 2,
        "comp_mode": true,
        "affine_to_cpu": false
    },
    {
        "index": 2,
        "intensity": 1932,
        "worksize": 8,
        "strided_index": 1,
        "mem_chunk": 2,
        "comp_mode": true,
        "affine_to_cpu": false
    },
    {
        "index": 3,
        "intensity": 1932,
        "worksize": 8,
        "strided_index": 1,
        "mem_chunk": 2,
        "comp_mode": true,
        "affine_to_cpu": false
    },
    {
        "index": 3,
        "intensity": 1932,
        "worksize": 8,
        "strided_index": 1,
        "mem_chunk": 2,
        "comp_mode": true,
        "affine_to_cpu": false
    },
    {
        "index": 4,
        "intensity": 1932,
        "worksize": 8,
        "strided_index": 1,
        "mem_chunk": 2,
        "comp_mode": true,
        "affine_to_cpu": false
    },
    {
        "index": 4,
        "intensity": 1932,
        "worksize": 8,
        "strided_index": 1,
        "mem_chunk": 2,
        "comp_mode": true,
        "affine_to_cpu": false
    }
],
```

**Comment by emailyc** [comment]
Yes that did the trick! Another question, how is intensity supposed to be calculated? Would like to know the math behind.

**Comment by xmrig** [comment]
Intensity it's a number of hashes for one calculation round. Example, intensity is 1792 and hashrate is 974 (1792 / 974 = ~1.84) so GPU thread will be busy for 1.84 seconds, all shares will found only after round is done.

Also intensity it's memory usage, for cryptonight: 1932 * 2 = 3864 MB + some overhead on top.

Intensity should be a multiple of the worksize, possible to break this rule via `comp_mode` option, but it can crash the miner.

So it's all about memory, but memory usage vs hashrate it's not linear dependence. No magic rule.
Thank you.

**Comment by emailyc** [comment]
very informative, thank you.
