### ISSUE TITLE
Defining pools on command line doenst work anymore

### ISSUE THREAD

**Issue by weltall666** [xmrig/xmrig-amd#135]
Trying to run *.exe -o pool.etn.spacepools.org:3333 -u

-p x --api-port 33999 --donate-level 1 --variant 1 -a cryptonightv7 --opencl-platform=1 --opencl-devices=0,0,1,1,2,2,3,3,4,4,5,5 --opencl-launch=864x8,864x8,864x8,864x8,864x8,864x8,864x8,864x8,864x8,864x8,864x8,864x8
This no longer works in the new version, it forces the config file

Can you create command line options for strided_index and memory_chunk?

**Comment by BobbyGR** [comment]
Can confirm, same issue here.

**Comment by xmrig** [comment]
`cryptonightv7` is not valid algorithm name, before such errors was silency ignored, valid values is `cryptonight`, `cryptonight-lite`, `cryptonight-heavy`, `cryptonight/msr` or short aliases.
New options for command line will be added later.
Thank you.

**Comment by UselessGuru** [comment]
> little outdated now

Could you please put together an updated list of allowed algos? Thank you!

**Comment by xmrig** [comment]
https://github.com/xmrig/xmrig-proxy/blob/master/doc/STRATUM_EXT.md#14-algorithm-names-and-variants

**Comment by xmrig** [comment]
https://github.com/xmrig/xmrig/releases/tag/v4.0.0-beta
