### ISSUE TITLE
GPU index

### ISSUE THREAD

**Issue by emailyc** [xmrig/xmrig-amd#137]
How does gpu number correspond to each card? I'm getting compute errors on gpu 5 and 'm not sure whether this is referring to THREAD number 5 or GPU number 5? I only have 4 cards so I assume THREAD number 5?
Also, is there a proper way to find out each card's corresponding index in OverDriveNTool?

**Comment by xmrig** [comment]
For compute errors, it's actually thread number. Miner use GPU indexes provided by OpenCL platform, same as `clinfo` output.
Thank you.
