### ISSUE TITLE
Feature request: add Raspberry Pi support

### ISSUE THREAD

**Issue by Zenitur** [xmrig/xmrig-amd#138]
[How to install OpenCL on Raspberry Pi](https://github.com/doe300/VC4CL/wiki/How-to-get)
[Not supported functions](https://github.com/doe300/VC4CL/wiki/NotSupported)
[clinfo output on Pastebin](https://pastebin.com/aQtG1UcT)
xmrig-amd build log:

```
-- Configuring done
CMake Error at CMakeLists.txt:248 (add_executable):
  Cannot find source file:

    src/Cpu_arm.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx


CMake Error: CMake can not determine linker language for target: xmrig-amd
CMake Error: Cannot determine link language for target "xmrig-amd".
-- Generating done
-- Build files have been written to: /home/pi/xmrig/xmrig-amd-master/build
pi@raspberrypi:~/xmrig/xmrig-amd-master/build $ make
make[2]: *** No rule to make target 'CMakeFiles/xmrig-amd.dir/build'.  Stop.
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/xmrig-amd.dir/all' failed
make[1]: *** [CMakeFiles/xmrig-amd.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by JakeTrans** [comment]
This would also be useful to allow some of the Single board computers equpped  will Mali GPUs to mine as they should use OpenCL.  The Cpu version does compile and run on a RPI.

In a attempt to allow it to compile I attempted to take the .cpp files of the same name from the cpu version unfortantly it would appear that some of the commands used aren;t compatable with arm (cpu_id).

**Comment by xmrig** [comment]
https://github.com/xmrig/xmrig/releases/tag/v4.0.0-beta
