### ISSUE TITLE
"ipbc / bittube" new algo support

### ISSUE THREAD

**Issue by yyfong0918** [xmrig/xmrig-amd#140]
Bittube changed from cn-lite to cn-heavy
is it possible to support this?

**Comment by xmrig** [comment]
Actually it not a regular cn-heavy, it's modified cn-heavy https://github.com/xmrig/xmrig/issues/700
Thank you.

**Comment by travis1234** [comment]
Any update on this one @xmrig ?

**Comment by xmrig** [comment]
@travis1234 https://github.com/xmrig/xmrig/issues/700#issuecomment-404303501

**Comment by yyfong0918** [comment]
xmrig-amd still not yet support bittube?  That algo is not cpu friendly...

**Comment by bananajamma** [comment]
@yyfong0918 It's released in https://github.com/xmrig/xmrig-amd/releases/tag/v2.7.3-beta
