### ISSUE TITLE
Compute error by reducing intensity.

### ISSUE THREAD

**Issue by emailyc** [xmrig/xmrig-amd#141]
I'm constantly getting compute error on a particular gpu thread. I tried lowering OC and lowering target temperature. No use. Since I'm running on duo thread, I'm thinking whether it would help by reducing the intensity of that particular thread? And if so would having different intensity on different thread of the same gpu affect stability?

**Comment by xmrig** [comment]
You can use different intensity for different threads, at least you can check it.
Thank you.
