### ISSUE TITLE
the xmrig-amd.exe cannot start

### ISSUE THREAD

**Issue by bright-light-in-the-night** [xmrig/xmrig-amd#142]
When i double click `start.cmd` or `xmrig-amd.exe`, i get the following error:
"The procedure entry point clCreateCommandQueueWithProperties could not be located in the dynamic link library OpenCL.dll"

The OS is Windows 7 Home Premium x64 and the video card is AMD 7950

**Comment by xmrig** [comment]
Please check #145

**Comment by bright-light-in-the-night** [comment]
I'm using xmr-stak now and is working fine. You can close this issue. Thanks!

**Comment by xmrig** [comment]
https://github.com/xmrig/xmrig/releases/tag/v4.0.0-beta
