### ISSUE TITLE
Thread becomes n/a

### ISSUE THREAD

**Issue by emailyc** [xmrig/xmrig-amd#143]
So I have this Vega 56 which gives a compute error every 30 minute or so; one of the two threads would turn to n/a after about one hour of mining. I wonder if I have a faulty card, and whether there are any settings I can make to make it mine stably.

**Comment by xmrig** [comment]
You can try reduce intensity or reduce GPU clocks by external methods.
Thank you.

**Comment by xmrig** [comment]
Duplicate #141
