### ISSUE TITLE
Adrenalin Edition 18.7.1

### ISSUE THREAD

**Issue by emailyc** [xmrig/xmrig-amd#146]
Are there any particular reasons for not using 18.7.1? I've been running 2.7.1 beta on 18.7.1 for a couple of days and only encountered minor issues (e.g. windows rebooted once).

**Comment by xmrig** [comment]
Symptoms is 70%-100% of compute errors, I faced it byself I get reports from other users. It not just xmrig issue, same errors on all other miners. What OS you use? it may also be Windows 10 related issue.
Thank you.

**Comment by emailyc** [comment]
Windows 10 1803
Ryzen 3 2200g
6x Vega 56

**Comment by yellatthewalls** [comment]
would this make all my shares come up invalid?

**Comment by xmrig** [comment]
@yellatthewalls No, invalid shares on pool side it wrong algorithm/variant. https://github.com/xmrig/xmrig/blob/master/doc/ALGORITHMS.md
Thank you.

**Comment by xmrig** [comment]
But yes, compute errors it's invalid shares itself, only difference, they will never send to pool.

**Comment by xmrig** [comment]
Please check https://github.com/xmrig/xmrig-amd/issues/156#issuecomment-427494685

**Comment by xmrig** [comment]
https://github.com/xmrig/xmrig/releases/tag/v4.0.0-beta
