### ISSUE TITLE
Mesa on Raven Ridge

### ISSUE THREAD

**Issue by calvintam236** [xmrig/xmrig-amd#147]
I made a docker image `calvintam236/xmrig-amd:mesa`, and `xmrig-amd` would not run after `#0, GPU #0 AMD RAVEN (DRM 3.23.0 / 4.16.14-2-MANJARO, LLVM 6.0.0)`.

PS: Auto set intensity fails - default is 0 (8/256).

XMRig 2.6.1

**Comment by calvintam236** [comment]
@xmrig 
I just tried to run (tried to build myself too) v2.8.5 in Manjaro (Arch Linux) with mesa, and I get this error: "AMD OpenCL platform NOT found." Yet, I'm seeing "#0: Mesa" when calling `--print-platforms`. Looks like something hardcoded not to accept mesa?

**Comment by xmrig** [comment]
Try `--opencl-platform=0`, default value for this option changed to `AMD`.
Thank you.

**Comment by calvintam236** [comment]
@xmrig I compiled v2.8.6 and ran with `--opencl-platform=0` option, and I'm still getting "AMD OpenCL platform NOT found." Any clue to fix that?

**Comment by calvintam236** [comment]
Hi @xmrig ,

I just tried to use v2.14.4 to test (w/ & w/out `--opencl-platform`), and it stuck at "Failed to start threads" after trying to compile. Any idea how to fix it?

**Comment by xmrig** [comment]
https://github.com/xmrig/xmrig/releases/tag/v4.0.0-beta
