### ISSUE TITLE
R9-290X  low hash

### ISSUE THREAD

**Issue by zubutu** [xmrig/xmrig-amd#148]
Ask for help! I have 2 R9-290X-4GB, mining cryptonight. No matter how hard I try, each card has a maximum of 700H. I hope someone will share the best configuration of the 290X. thank you very much!

My configuration is like this，reach my best hash:
   "threads": [
        {
            "index": 0,
       "threads":8,
      "intensity": 1024,      
     "worksize": 8,
  "blocks" : 12, 
"bfactor": 0,
"bsleep":0,    
   "affine_to_cpu": false
        },    
   {
            "index": 1,
      "threads":8,
       "intensity": 1024,
        "worksize": 8,
 "blocks" : 12, 
"bfactor": 0,
"bsleep":0,           
 "affine_to_cpu": false
        }
    ],

**Comment by xmrig** [comment]
https://github.com/xmrig/xmrig/releases/tag/v4.0.0-beta
