### ISSUE TITLE
Significantly low hashrate(cn-heavy)

### ISSUE THREAD

**Issue by puka89** [xmrig/xmrig-amd#149]
I have a rig with 2 RX 550 and a R9 285. on cryptonight(monero) i get the RX's  about 350 stable hashes per card and the R9 has like 500, but on cn-heavy(Loki).
Like always, 2 threads per card, worksize 8 on all cards, the RX's were stable on 284 intensity per thread, and the R9 did well on 464 intensity per thread.
Now on cn-heavy, the RX's are stable at 204 intensity per thread and the R9 is stable at 218 per thread... and the R9 hashes lower than the RX's, i mean, they are on 270 hashes per card and the R9 has 260...
Any ideas?

Win 7, 64 bit, 
Adrenalin 18.6.1
Xmrig 2.7.3 beta

**Comment by xmrig** [comment]
https://github.com/xmrig/xmrig/releases/tag/v4.0.0-beta
