### ISSUE TITLE
GPU monitoring

### ISSUE THREAD

**Issue by RipZ** [xmrig/xmrig-amd#15]
Please add GPU monitoring and the ability to run an external script (like in Claymore's) when GPU is hangs (hashrate is 0).
Also I would like to monitoring frequencies and temperatures of each GPU. Thanks!

cat /sys/class/drm/card0/device/pp_dpm_sclk
cat /sys/class/drm/card0/device/pp_dpm_mclk
cat /sys/kernel/debug/dri/0/amdgpu_pm_info

**Comment by MetallianFR68** [comment]
+1 for GPU monitoring
It would be nice to access some GPU information in the API as well (card description, gpu temp, fan speed ...) like it already exists in xmrig-nvidia

RipZ suggestion about autorestart when hashrate is equal to zero is also good.
It would be perfect if the user could set the hashrate threshold.
VEGA56 cards are known to suddenly throttle for no reason (they lower from 1950 to 1500 H/s) and it needs an xmrig restart

**Comment by noctrex** [comment]
+1 for me, as I have seen sometimes that my 7870 will stop hashing at random intervals, without any reason (at least no temperature problem or whatsoever as I can see from the Radeon panel)

**Comment by sitchi** [comment]
+1

**Comment by RipZ** [comment]
I write a script for monitoring (by API) falling hashrate , but this is not true way, we need a internal way for this :)

**Comment by RipZ** [comment]
something like this) sorry for shit-code ;)

`#!/bin/bash

function getJsonVal () {
    python -c "import json,sys;sys.stdout.write(json.dumps(json.load(sys.stdin)$1))";
}

function hardReset () {
    sync
    echo 1 > /proc/sys/kernel/sysrq
    echo u > /proc/sysrq-trigger
    sleep 1
    echo b > /proc/sysrq-trigger
}

echo -n "Start monitoring, waiting for 3 minutes... "
sleep 180
echo "done"

while true; do
    DATE=`date '+%d/%m/%Y %H:%M:%S'`
    GPU0=`curl -s http://192.168.1.51:8080 | getJsonVal "['hashrate']['threads'][0][0]"`
    GPU1=`curl -s http://192.168.1.51:8080 | getJsonVal "['hashrate']['threads'][1][0]"`
    GPU2=`curl -s http://192.168.1.51:8080 | getJsonVal "['hashrate']['threads'][2][0]"`
    GPU3=`curl -s http://192.168.1.51:8080 | getJsonVal "['hashrate']['threads'][3][0]"`
    GPU4=`curl -s http://192.168.1.51:8080 | getJsonVal "['hashrate']['threads'][4][0]"`

    echo "$DATE GPU #0: $GPU0 h/s, GPU #1: $GPU1 h/s, GPU #2: $GPU2 h/s, GPU #3: $GPU3 h/s, GPU #4: $GPU4 h/s"
    echo "$DATE GPU #0: $GPU0 h/s, GPU #1: $GPU1 h/s, GPU #2: $GPU2 h/s, GPU #3: $GPU3 h/s, GPU #4: $GPU4 h/s" >> /opt/monitor/monitor.log

    if [ $GPU0 == "0.0" ]
    then
        echo "$DATE GPU #0 hangs, hard reset"
        echo "$DATE GPU #0 hangs, hard reset" >> /opt/monitor/monitor.log
        hardReset
    fi

    if [ $GPU1 == "0.0" ]
    then
        echo "$DATE GPU #1 hangs!, hard reset"
        echo "$DATE GPU #1 hangs!, hard reset" >> /opt/monitor/monitor.log
        hardReset
    fi

    if [ $GPU2 == "0.0" ]
    then
        echo "$DATE GPU #2 hangs!, hard reset"
        echo "$DATE GPU #2 hangs!, hard reset" >> /opt/monitor/monitor.log
        hardReset
    fi

    if [ $GPU3 == "0.0" ]
    then
        echo "$DATE GPU #3 hangs!, hard reset"
        echo "$DATE GPU #3 hangs!, hard reset" >> /opt/monitor/monitor.log
        hardReset
    fi

    sleep 60
done`

**Comment by xmrig** [comment]
https://github.com/xmrig/xmrig/releases/tag/v4.0.0-beta
