### ISSUE TITLE
Unable to run the make command successfully

### ISSUE THREAD

**Issue by matthewyuhk01** [xmrig/xmrig-amd#153]
I am using Macbook Pro 2017 version with Radeon Pro 555 

I followed this instructions: https://github.com/xmrig/xmrig-amd/wiki/Ubuntu-Build.
This command is not run successfully 
`sudo apt-get install git build-essential cmake libuv1-dev libmicrohttpd-dev`

Then, the make is not successful. Here is the log.

`
[  2%] Building CXX object CMakeFiles/xmrig-amd.dir/src/amd/OclCache.cpp.o
In file included from /Users/user/Documents/mining/xmrig-amd/src/amd/OclCache.cpp:30:
In file included from /Users/user/Documents/mining/xmrig-amd/src/amd/OclCache.h:28:
In file included from /Users/user/Documents/mining/xmrig-amd/src/amd/GpuContext.h:28:
/Users/user/Documents/mining/xmrig-amd/src/3rdparty/CL/cl.h:33:10: fatal error: 
      'OpenCL/cl_version.h' file not found
#include <OpenCL/cl_version.h>
         ^~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [CMakeFiles/xmrig-amd.dir/src/amd/OclCache.cpp.o] Error 1
make[1]: *** [CMakeFiles/xmrig-amd.dir/all] Error 2
make: *** [all] Error 2
`

What should I do? Does xmrig-amd support macOS High Sierra?

**Comment by djfinch** [comment]
FYI: https://github.com/xmrig/xmrig-amd/issues/155
Use dev version which solve this issue. High Sierra was not the problem...

**Comment by xmrig** [comment]
https://github.com/xmrig/xmrig/releases/tag/v4.0.0-beta
