### ISSUE TITLE
cryptonight-heavy not work

### ISSUE THREAD

**Issue by kostepanych** [xmrig/xmrig-amd#157]
When setting "algo": "cryptonight-heavy" get error message:
No valid configuration found. Exiting.
All other configurations are default. Changed only pool address.

**Comment by hanyoonLDA** [comment]
Same thing happens to me, but with cn-lite.

**Comment by maktan38** [comment]
"algo": "cryptonight-heavy/tube"

**Comment by xmrig** [comment]
https://github.com/xmrig/xmrig/releases/tag/v4.0.0-beta
