### ISSUE TITLE
path for OpenCL cache directory

### ISSUE THREAD

**Issue by k0ste** [xmrig/xmrig-amd#165]
After #130 miner can make cache in ".cache" directory.
We need `path-prefix` option for this, because in case when miner started with systemd may be impossible to write in `/` (root) directory.

**Comment by Spudz76** [comment]
Set workdir properly in systemd service override file and it won't be running out of /

basically a systemd misconfiguration

`WorkingDirectory=/some/good/place` within the `[Service]` section

**Comment by k0ste** [comment]
Of course, but this is not a solution, just a avoidness.

**Comment by xmrig** [comment]
Was little lazy to implement configurable path when create this feature, also default path on Linux system should be different, for example `~/.cache/xmrig`.

**Comment by xmrig** [comment]
https://github.com/xmrig/xmrig/releases/tag/v4.0.0-beta
