### ISSUE TITLE
Low hashrate

### ISSUE THREAD

**Issue by neptune-klm** [xmrig/xmrig-amd#169]
I am completely new to Xmrig, but want to be able to mine all the alt coins on Monero Ocean.  I have downloaded 2.8.1 for amd.  I am running 6 x Vega 64's and no CPU.  I have been running stak and getting about 12,100h/s before this.  I tried using 2 threads by just copying/pasting index 0 etc, but xmrig-amd-exe wouldn't even start.  Please advise:)  See below for my config.json & hashrate...

{
    "algo": "cryptonight",
    
"api": {
"port": 0,
"access-token": null,
"id": null,
"worker-id": null,
"ipv6": false,
"restricted": true
    },
"autosave": true,
"background": false,
"cache": true,
"colors": true,
"donate-level": 1,
"log-file": null,
"opencl-platform": "AMD",
"opencl-loader": "OpenCL.dll",
"pools": [
        {
"url": "gulf.moneroocean.stream:10128",
"user": "purposefully left out for this example",
"pass": "purposefully left out for this example",
"rig-id": null,
"nicehash": false,
"keepalive": false,
"variant": -1,
"tls": false,
"tls-fingerprint": null
        }
    ],
"print-time": 30,
"retries": 5,
"retry-pause": 5,
"threads": [
{"index": 0,
 "intensity": 1920,
 "worksize": 8,
 "strided_index": 2,
 "mem_chunk": 2,
 "unroll": 8,
 "comp_mode": false,
"affine_to_cpu": false},

{"index": 1,
 "intensity": 1920,
 "worksize": 8,
 "strided_index": 2,
 "mem_chunk": 2,
 "unroll": 8,
 "comp_mode": false,
"affine_to_cpu": false},

{"index": 2,
 "intensity": 1920, 
"worksize": 8,
 "strided_index": 2,
 "mem_chunk": 2,
 "unroll": 8,
 "comp_mode": false,
"affine_to_cpu": false},
   
{"index": 3,
 "intensity": 1920, "worksize": 8,
 "strided_index": 2,
 "mem_chunk": 2,
 "unroll": 8,
 "comp_mode": false,
"affine_to_cpu": false},
    
{"index": 4,
 "intensity": 1920,
 "worksize": 8,
 "strided_index": 2,
 "mem_chunk": 2,
 "unroll": 8,
 "comp_mode": false,
"affine_to_cpu": false},
   
{"index": 5,
 "intensity": 1920,
 "worksize": 8,
 "strided_index": 2,
 "mem_chunk": 2,
 "unroll": 8,
 "comp_mode": false,
"affine_to_cpu": false}
   ],
    
"user-agent": null,
"syslog": false,
"watch": false
}

| THREAD | GPU | 10s H/s | 60s H/s | 15m H/s |
|      0 |   0 |  1507.6 |     n/a |     n/a |
|      1 |   1 |  1506.7 |     n/a |     n/a |
|      2 |   2 |  1505.2 |     n/a |     n/a |
|      3 |   3 |  1510.1 |     n/a |     n/a |
|      4 |   4 |  1505.7 |     n/a |     n/a |
|      5 |   5 |  1506.7 |     n/a |     n/a |
[2018-10-12 19:53:02] speed 10s/60s/15m 9042.0 n/a n/a H/s max 9051.7 H/s

**Comment by danjae** [comment]
Hi, please try following threads config, increase intensity if this one will run stable 

    "threads": [
        {
            "index": 0,
            "intensity": 1800,
            "worksize": 8,
            "strided_index": 2,
            "mem_chunk": 2,
            "unroll": 8,
            "comp_mode": true,
            "affine_to_cpu": false
        },
        {
            "index": 0,
            "intensity": 1800,
            "worksize": 8,
            "strided_index": 2,
            "mem_chunk": 2,
            "unroll": 8,
            "comp_mode": true,
            "affine_to_cpu": false
        },
        {
            "index": 1,
            "intensity": 1800,
            "worksize": 8,
            "strided_index": 2,
            "mem_chunk": 2,
            "unroll": 8,
            "comp_mode": true,
            "affine_to_cpu": false
        },
        {
            "index": 1,
            "intensity": 1800,
            "worksize": 8,
            "strided_index": 2,
            "mem_chunk": 2,
            "unroll": 8,
            "comp_mode": true,
            "affine_to_cpu": false
        },
        {
            "index": 2,
            "intensity": 1800,
            "worksize": 8,
            "strided_index": 2,
            "mem_chunk": 2,
            "unroll": 8,
            "comp_mode": true,
            "affine_to_cpu": false
        },
        {
            "index": 2,
            "intensity": 1800,
            "worksize": 8,
            "strided_index": 2,
            "mem_chunk": 2,
            "unroll": 8,
            "comp_mode": true,
            "affine_to_cpu": false
        },
        {
            "index": 3,
            "intensity": 1800,
            "worksize": 8,
            "strided_index": 2,
            "mem_chunk": 2,
            "unroll": 8,
            "comp_mode": true,
            "affine_to_cpu": false
        },
        {
            "index": 3,
            "intensity": 1800,
            "worksize": 8,
            "strided_index": 2,
            "mem_chunk": 2,
            "unroll": 8,
            "comp_mode": true,
            "affine_to_cpu": false
        },
 {
            "index": 4,
            "intensity": 1800,
            "worksize": 8,
            "strided_index": 2,
            "mem_chunk": 2,
            "unroll": 8,
            "comp_mode": true,
            "affine_to_cpu": false
        },
        {
            "index": 4,
            "intensity": 1800,
            "worksize": 8,
            "strided_index": 2,
            "mem_chunk": 2,
            "unroll": 8,
            "comp_mode": true,
            "affine_to_cpu": false
        }
 {
            "index": 5,
            "intensity": 1800,
            "worksize": 8,
            "strided_index": 2,
            "mem_chunk": 2,
            "unroll": 8,
            "comp_mode": true,
            "affine_to_cpu": false
        },
        {
            "index": 5,
            "intensity": 1800,
            "worksize": 8,
            "strided_index": 2,
            "mem_chunk": 2,
            "unroll": 8,
            "comp_mode": true,
            "affine_to_cpu": false
        }



    ],

**Comment by sumnone** [comment]
I was getting ~2000 H/s before consistently at 3584 intensity on a Vega FE, maxing at around 2050 H/s. Now, I'm getting 760 H/s at the same intensity. Everything else is default (like above). The best I've been able to do in testing thus far (i.e. today) is 1365 H/s at 2048 intensity.

I've read the comment somewhere else about a 25% decrease in hash rate is normal, but I'm just not seeing that. Here's everything else I've tried:

intensity = H/s
1536 = 1110
1736 = 1226
1800 = 1238
1920 = 1290
1984 = 1301
2048 = 1367
2112 = 1178
2176 = 1206
2240 = 1230
2304 = 1262
2560 = 1343
3000 = 1314
3072 = 1193
3584 = 760

I'm basically just guessing in lumps of 64 (and a few stragglers in there), but my ADD is kicking in. So, I think I'm just going to leave it at 2048 for the time being. I suppose a 30%+ hit is in the ballpark of 25%.

For the record, I was getting lower hash rates on other versions of xmrig too (2.6.4, 2.7.3... 2.8.1 just a few days ago...usually around 1800-1900 H/s). I assumed 3584 wasn't the magic intensity number and so I just stuck with 2.6.0 beta 1 until I was forced to just now switch.

Be nice if we had a tool or something to streamline the best intensity.

**Comment by danjae** [comment]
Looks like you are using outdated drivers then, please try 18.6.1

**Comment by sumnone** [comment]
I am using the blockchain drivers here:

https://support.amd.com/en-us/kb-articles/Pages/Radeon-Software-Crimson-ReLive-Edition-Beta-for-Blockchain-Compute-Release-Notes.aspx/

No good?

**Comment by xmrig** [comment]
@sumnone You should use only 18.6.1 (best choice) or 18.5.1 driver. Blockchain drivers not work well with new algorithm.

Also use double threads (example above) and worksize 16.

**Comment by sumnone** [comment]
Thanks for the reply guys, but with the 18.6.1 (Adrenaline) drivers it drops to 1327 H/s. I did a clean install with the drivers only and several reboots. If I disable and enable the display adapter in Computer Management (trick from before to turn off some of the AMD toggles, can't think of the name at the moment and don't have it installed), it drops to 1318 H/s. If I set strided_index back to 2, it drops to 1175 H/s. Add a second thread and now I'm at 905 H/s... Seems I'm going in the wrong direction here... 

If I use the example above:

{
        "index": 0,
        "intensity": 1800,
        "worksize": 8,
        "strided_index": 2,
        "mem_chunk": 2,
        "unroll": 8,
        "comp_mode": true,
        "affine_to_cpu": false
    },
    {
        "index": 0,
        "intensity": 1800,
        "worksize": 8,
        "strided_index": 2,
        "mem_chunk": 2,
        "unroll": 8,
        "comp_mode": true,
        "affine_to_cpu": false
    }

Equals to 1020 H/s.

If I use the example above and simply change worksize to 16, xmrig-amd drops my intensity to 1792 and then I'm averaging around 1080 H/s.

I'm way worse off at this point, but I'll keep messing with it. Thanks again for your replies.

**Comment by sumnone** [comment]
I got it to around 1535 H/s maxed at 1638 H/s by installing the AMD Settings controls and turning off HBCC and everything else with a toggle, then setting intensity to 2048 and worksize to 16 (everything else default) and adding a second thread.

That's around 25% hit. So, I'll just hang with that until I find evidence that it can do better.

Thanks for the tips.

**Comment by xmrig** [comment]
https://github.com/xmrig/xmrig/releases/tag/v4.0.0-beta
