### ISSUE TITLE
Build problem when AMD APP SDK installed

### ISSUE THREAD

**Issue by YuriyPobezhymov** [xmrig/xmrig-amd#17]
Hello.
I successfully built xmrig-amd on the Kubuntu 17.10.
But after installing AMD APP SDK I tried to build it again and it failed:
```{r, engine='bash'}
cmake .     
-- The C compiler identification is GNU 7.2.0
-- The CXX compiler identification is GNU 7.2.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found UV: /usr/lib/x86_64-linux-gnu/libuv.so  
-- Looking for CL_VERSION_2_0
-- Looking for CL_VERSION_2_0 - found
-- Found OpenCL: /opt/AMDAPPSDK-3.0/lib/x86_64/libOpenCL.so (found version "2.0") 
-- Looking for syslog.h
-- Looking for syslog.h - found
-- Found mhd: /usr/include  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/yuriy/xmrig-amd

make
Scanning dependencies of target xmrig-amd
[  2%] Building CXX object CMakeFiles/xmrig-amd.dir/src/api/Api.cpp.o
[  4%] Building CXX object CMakeFiles/xmrig-amd.dir/src/api/ApiState.cpp.o
[  7%] Building CXX object CMakeFiles/xmrig-amd.dir/src/api/NetworkState.cpp.o
[  9%] Building CXX object CMakeFiles/xmrig-amd.dir/src/App.cpp.o
[ 12%] Building CXX object CMakeFiles/xmrig-amd.dir/src/Console.cpp.o
[ 14%] Building CXX object CMakeFiles/xmrig-amd.dir/src/Cpu_stub.cpp.o
[ 17%] Building CXX object CMakeFiles/xmrig-amd.dir/src/log/ConsoleLog.cpp.o
[ 19%] Building CXX object CMakeFiles/xmrig-amd.dir/src/log/FileLog.cpp.o
[ 21%] Building CXX object CMakeFiles/xmrig-amd.dir/src/log/Log.cpp.o
[ 24%] Building CXX object CMakeFiles/xmrig-amd.dir/src/net/Client.cpp.o
[ 26%] Building CXX object CMakeFiles/xmrig-amd.dir/src/net/Job.cpp.o
[ 29%] Building CXX object CMakeFiles/xmrig-amd.dir/src/net/Network.cpp.o
[ 31%] Building CXX object CMakeFiles/xmrig-amd.dir/src/net/strategies/DonateStrategy.cpp.o
[ 34%] Building CXX object CMakeFiles/xmrig-amd.dir/src/net/strategies/FailoverStrategy.cpp.o
[ 36%] Building CXX object CMakeFiles/xmrig-amd.dir/src/net/strategies/SinglePoolStrategy.cpp.o
[ 39%] Building CXX object CMakeFiles/xmrig-amd.dir/src/net/SubmitResult.cpp.o
[ 41%] Building CXX object CMakeFiles/xmrig-amd.dir/src/net/Url.cpp.o
[ 43%] Building CXX object CMakeFiles/xmrig-amd.dir/src/amd/OclCLI.cpp.o
[ 46%] Building CXX object CMakeFiles/xmrig-amd.dir/src/amd/OclGPU.cpp.o
[ 48%] Building CXX object CMakeFiles/xmrig-amd.dir/src/Options.cpp.o
[ 51%] Building CXX object CMakeFiles/xmrig-amd.dir/src/Platform.cpp.o
[ 53%] Building CXX object CMakeFiles/xmrig-amd.dir/src/Summary.cpp.o
[ 56%] Building CXX object CMakeFiles/xmrig-amd.dir/src/workers/OclWorker.cpp.o
[ 58%] Building CXX object CMakeFiles/xmrig-amd.dir/src/workers/OclThread.cpp.o
[ 60%] Building CXX object CMakeFiles/xmrig-amd.dir/src/workers/Handle.cpp.o
[ 63%] Building CXX object CMakeFiles/xmrig-amd.dir/src/workers/Hashrate.cpp.o
[ 65%] Building CXX object CMakeFiles/xmrig-amd.dir/src/workers/Workers.cpp.o
[ 68%] Building CXX object CMakeFiles/xmrig-amd.dir/src/xmrig.cpp.o
[ 70%] Building CXX object CMakeFiles/xmrig-amd.dir/src/App_unix.cpp.o
[ 73%] Building CXX object CMakeFiles/xmrig-amd.dir/src/Cpu_unix.cpp.o
[ 75%] Building CXX object CMakeFiles/xmrig-amd.dir/src/Platform_unix.cpp.o
[ 78%] Building C object CMakeFiles/xmrig-amd.dir/src/crypto/c_keccak.c.o
[ 80%] Building C object CMakeFiles/xmrig-amd.dir/src/crypto/c_groestl.c.o
[ 82%] Building C object CMakeFiles/xmrig-amd.dir/src/crypto/c_blake256.c.o
[ 85%] Building C object CMakeFiles/xmrig-amd.dir/src/crypto/c_jh.c.o
[ 87%] Building C object CMakeFiles/xmrig-amd.dir/src/crypto/c_skein.c.o
[ 90%] Building C object CMakeFiles/xmrig-amd.dir/src/crypto/soft_aes.c.o
[ 92%] Building CXX object CMakeFiles/xmrig-amd.dir/src/crypto/CryptoNight.cpp.o
[ 95%] Building CXX object CMakeFiles/xmrig-amd.dir/src/log/SysLog.cpp.o
[ 97%] Building CXX object CMakeFiles/xmrig-amd.dir/src/api/Httpd.cpp.o
make[2]: *** No rule to make target '/opt/AMDAPPSDK-3.0/lib/x86_64/libOpenCL.so', needed by 'xmrig-amd'.  Stop.
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/xmrig-amd.dir/all' failed
make[1]: *** [CMakeFiles/xmrig-amd.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```
I tried to run `cmake . -DOpenCL_LIBRARY=/opt/AMDAPPSDK-3.0/lib/x86_64/libOpenCL.so -DOpenCL_INCLUDE_DIR=/opt/AMDAPPSDK-3.0/include/CL`, but those flags don't change result.

What's wrong here with AMD/ATI libOpenCL.so? With Mesa OpenCL lib compilation was OK.
Thanks, Yuriy.

**Comment by RipZ** [comment]
try to use /opt/amdgpu-pro/lib/x86_64-linux-gnu/libOpenCL.so

**Comment by RipZ** [comment]
root@rig2:/home/vsadilov/xmrig-amd/build# cmake .. -DOpenCL_LIBRARY=/opt/AMDAPPSDK-3.0/lib/x86_64/libOpenCL.so -DOpenCL_INCLUDE_DIR=/opt/AMDAPPSDK-3.0/include/CL
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found UV: /usr/lib/x86_64-linux-gnu/libuv.so
-- Looking for CL_VERSION_2_0
-- Looking for CL_VERSION_2_0 - not found
-- Looking for CL_VERSION_1_2
-- Looking for CL_VERSION_1_2 - not found
-- Looking for CL_VERSION_1_1
-- Looking for CL_VERSION_1_1 - not found
-- Looking for CL_VERSION_1_0
-- Looking for CL_VERSION_1_0 - not found
-- Found OpenCL: /opt/AMDAPPSDK-3.0/lib/x86_64/libOpenCL.so
-- Looking for syslog.h
-- Looking for syslog.h - found
-- Found mhd: /usr/include
-- Configuring done
-- Generating done
-- Build files have been written to: /home/vsadilov/xmrig-amd/build
root@rig2:/home/vsadilov/xmrig-amd/build# make
Scanning dependencies of target xmrig-amd
[  2%] Building CXX object CMakeFiles/xmrig-amd.dir/src/api/Api.cpp.o
[  4%] Building CXX object CMakeFiles/xmrig-amd.dir/src/api/ApiState.cpp.o
[  7%] Building CXX object CMakeFiles/xmrig-amd.dir/src/api/NetworkState.cpp.o
[  9%] Building CXX object CMakeFiles/xmrig-amd.dir/src/App.cpp.o
[ 12%] Building CXX object CMakeFiles/xmrig-amd.dir/src/Console.cpp.o
[ 14%] Building CXX object CMakeFiles/xmrig-amd.dir/src/Cpu_stub.cpp.o
[ 17%] Building CXX object CMakeFiles/xmrig-amd.dir/src/log/ConsoleLog.cpp.o
[ 19%] Building CXX object CMakeFiles/xmrig-amd.dir/src/log/FileLog.cpp.o
[ 21%] Building CXX object CMakeFiles/xmrig-amd.dir/src/log/Log.cpp.o
[ 24%] Building CXX object CMakeFiles/xmrig-amd.dir/src/net/Client.cpp.o
[ 26%] Building CXX object CMakeFiles/xmrig-amd.dir/src/net/Job.cpp.o
[ 29%] Building CXX object CMakeFiles/xmrig-amd.dir/src/net/Network.cpp.o
[ 31%] Building CXX object CMakeFiles/xmrig-amd.dir/src/net/strategies/DonateStrategy.cpp.o
[ 34%] Building CXX object CMakeFiles/xmrig-amd.dir/src/net/strategies/FailoverStrategy.cpp.o
[ 36%] Building CXX object CMakeFiles/xmrig-amd.dir/src/net/strategies/SinglePoolStrategy.cpp.o
[ 39%] Building CXX object CMakeFiles/xmrig-amd.dir/src/net/SubmitResult.cpp.o
[ 41%] Building CXX object CMakeFiles/xmrig-amd.dir/src/net/Url.cpp.o
[ 43%] Building CXX object CMakeFiles/xmrig-amd.dir/src/amd/OclCLI.cpp.o
[ 46%] Building CXX object CMakeFiles/xmrig-amd.dir/src/amd/OclGPU.cpp.o
[ 48%] Building CXX object CMakeFiles/xmrig-amd.dir/src/Options.cpp.o
[ 51%] Building CXX object CMakeFiles/xmrig-amd.dir/src/Platform.cpp.o
[ 53%] Building CXX object CMakeFiles/xmrig-amd.dir/src/Summary.cpp.o
[ 56%] Building CXX object CMakeFiles/xmrig-amd.dir/src/workers/OclWorker.cpp.o
[ 58%] Building CXX object CMakeFiles/xmrig-amd.dir/src/workers/OclThread.cpp.o
[ 60%] Building CXX object CMakeFiles/xmrig-amd.dir/src/workers/Handle.cpp.o
[ 63%] Building CXX object CMakeFiles/xmrig-amd.dir/src/workers/Hashrate.cpp.o
[ 65%] Building CXX object CMakeFiles/xmrig-amd.dir/src/workers/Workers.cpp.o
[ 68%] Building CXX object CMakeFiles/xmrig-amd.dir/src/xmrig.cpp.o
[ 70%] Building CXX object CMakeFiles/xmrig-amd.dir/src/App_unix.cpp.o
[ 73%] Building CXX object CMakeFiles/xmrig-amd.dir/src/Cpu_unix.cpp.o
[ 75%] Building CXX object CMakeFiles/xmrig-amd.dir/src/Platform_unix.cpp.o
[ 78%] Building C object CMakeFiles/xmrig-amd.dir/src/crypto/c_keccak.c.o
[ 80%] Building C object CMakeFiles/xmrig-amd.dir/src/crypto/c_groestl.c.o
[ 82%] Building C object CMakeFiles/xmrig-amd.dir/src/crypto/c_blake256.c.o
[ 85%] Building C object CMakeFiles/xmrig-amd.dir/src/crypto/c_jh.c.o
[ 87%] Building C object CMakeFiles/xmrig-amd.dir/src/crypto/c_skein.c.o
[ 90%] Building C object CMakeFiles/xmrig-amd.dir/src/crypto/soft_aes.c.o
[ 92%] Building CXX object CMakeFiles/xmrig-amd.dir/src/crypto/CryptoNight.cpp.o
[ 95%] Building CXX object CMakeFiles/xmrig-amd.dir/src/log/SysLog.cpp.o
[ 97%] Building CXX object CMakeFiles/xmrig-amd.dir/src/api/Httpd.cpp.o
[100%] Linking CXX executable xmrig-amd
[100%] Built target xmrig-amd

**Comment by YuriyPobezhymov** [comment]
Thank you! Works.

**Comment by jeee** [comment]
Still did not work for me. I had to run this for it to compile:

sudo ln -s /opt/AMDAPPSDK-3.0/lib/x86_64/sdk/libOpenCL.so.1 /usr/lib/libOpenCL.so.1

**Comment by YuriyPobezhymov** [comment]
I can say that passing libOpenCL.so.1 to cmake's argument OpenCL_LIBRARY works, but not libOpenCL.so which is symlink.

**Comment by joshgrobin** [comment]
Thanks RipZ this worked for me
cmake .. -DOpenCL_LIBRARY=/opt/amdgpu-pro/lib/x86_64-linux-gnu/libOpenCL.so -DOpenCL_INCLUDE_DIR=-DOpenCL_INCLUDE_DIR=/opt/AMDAPPSDK-3.0/include/CL

**Comment by karpa13a** [comment]
can you provide a link to proper amd sdk?

**Comment by xmrig** [comment]
AMD SDK no more required for recent versions.
