### ISSUE TITLE
RX 580 high temperature problem after hardfork

### ISSUE THREAD

**Issue by minimalist83** [xmrig/xmrig-amd#170]
Type of the GPU: RX580
Simpleming OS
Version: xmrig-amd-v2.8.1
GPUs are one-click patch overclocked

Just after the hard work, I get very high temperatures.
The hashrate is higher a little bit also, comparing before.
Nothing is changed, except the hardfork.
I use dual thread for all of 12 GPUs.

**Comment by xmrig** [comment]
New algorithm use more power than before => increased temperature.
Thank you.

**Comment by xmrig** [comment]
https://github.com/xmrig/xmrig/releases/tag/v4.0.0-beta
