### ISSUE TITLE
not working on older cards...

### ISSUE THREAD

**Issue by 38rc** [xmrig/xmrig-amd#178]
It just crashes GPU (5800) then n/a hash rate on monero. after fork. is there a workaround. ?

**Comment by IvankoB** [comment]
HD6850 1Gb too in wn7 64bit. (monero8)

Possibly a specific driver version is needed but which ?

**Comment by IvankoB** [comment]
Thaxn, it's working woarkaround.
Though the speed it low - me only have 90H/s on Monero8 with HD6850 1G.
If you have much better speed please share your driver version (or download link) & GPU thread config.

**Comment by 38rc** [comment]
Thanks SergeichM , its working now. only 64H/s, but better than 0... :) I'm using catalyst 15.7.1 drivers.

**Comment by xmrig** [comment]
https://github.com/xmrig/xmrig/releases/tag/v4.0.0-beta
