### ISSUE TITLE
HD7970+HD6990 

### ISSUE THREAD

**Issue by sergeysrnd** [xmrig/xmrig-amd#18]
Help me please! In my system work xfx hd7970 and his hd6990. But miner work with only hd7970. What can I do? Where my error?

**Comment by carboneer** [comment]
You have to use the ccc driver 15.7.1 with any other driver your 2 gpu will never run together

**Comment by cryptonius** [comment]
The problem is, VLIW GPUs perform very poorly with xmrig-amd (Claymore v9.7 runs faster)... this needs to be fixed.

**Comment by xmrig** [comment]
https://github.com/xmrig/xmrig/releases/tag/v4.0.0-beta
