### ISSUE TITLE
Can you add a new algo?

### ISSUE THREAD

**Issue by Cideg** [xmrig/xmrig-amd#183]
Please add the algo: CN-Heavy-Fast

Many  thx

**Comment by xmrig** [comment]
I already answered to your email about troubles with your xmrig-amd fork.

To add your algorithm to mainstream you should met minimum requirements:

1. Working mainnet, at least 1 MH/s, but better if more.
2. Website.
3. bitcointalk announcement.
4. At least one exchange.

**Comment by xmrig** [comment]
https://github.com/xmrig/xmrig/releases/tag/v4.0.0-beta
