### ISSUE TITLE
Please add "Cryptonight Red" for xmrid-amd ! thank you very much !!!

### ISSUE THREAD

**Issue by lamgztey** [xmrig/xmrig-amd#184]
"Cryptonight Red" https://getmox.org/

**Comment by xmrig** [comment]
Make a pull request or provide all information what changed/test pool/etc, I can't and don't like to dig what changed, MoX is third coin today who create new innovate/unique algorithm.
Thank you.

**Comment by lamgztey** [comment]
Algo: "CryptoNight Red" [mox]
Website: https://getmox.org/
https://github.com/mox-project/
https://bitcointalk.org/index.php?topic=4724483.0
https://miningpoolstats.stream/mox
I use xmrig-amd on ubuntu 16.04 ! please add it ! thanks you !
