### ISSUE TITLE
error "Error CL_MEM_OBJECT_ALLOCATION_FAILURE when calling clEnqueueNDRangeKernel for kernel 0", Ubuntu swap set 26G

### ISSUE THREAD

**Issue by lamgztey** [xmrig/xmrig-amd#186]
Help me !
I use ethos 1.3.3, xmrig-amd 2.8.5,  Ubuntu set swap to 60G  my config:

{
    "algo": "cn-heavy/xhv",
    "api": {
        "port": 3333,
        "access-token": null,
        "id": null,
        "worker-id": null,
        "ipv6": false,
        "restricted": true
    },
    "autosave": true,
    "background": false,
    "cache": true,
    "colors": true,
    "donate-level": 1,
    "log-file": null,
    "opencl-platform": "AMD",
    "opencl-loader": "libOpenCL.so",
    "pools": [
        {
            "url": "lamgztey.dyndns.org:9000",
            "user": "x",
            "pass": "x",
            "rig-id": null,
            "nicehash": false,
            "keepalive": false,
            "variant": "xhv",
            "tls": false,
            "tls-fingerprint": null
        }
    ],
    "print-time": 60,
    "retries": 5,
    "retry-pause": 5,
    "threads": [
        {
            "index": 0,
            "intensity": 928,
            "worksize": 8,
            "strided_index": 2,
            "mem_chunk": 2,
            "unroll": 8,
            "comp_mode": true,
            "affine_to_cpu": false
        },
        {
            "index": 0,
            "intensity": 928,
            "worksize": 8,
            "strided_index": 2,
            "mem_chunk": 2,
            "unroll": 8,
            "comp_mode": true,
            "affine_to_cpu": false
        },		
        {
            "index": 1,
            "intensity": 928,
            "worksize": 8,
            "strided_index": 2,
            "mem_chunk": 2,
            "unroll": 8,
            "comp_mode": true,
            "affine_to_cpu": false
        },
        {
            "index": 1,
            "intensity": 928,
            "worksize": 8,
            "strided_index": 2,
            "mem_chunk": 2,
            "unroll": 8,
            "comp_mode": true,
            "affine_to_cpu": false
        },		
        {
            "index": 2,
            "intensity": 928,
            "worksize": 8,
            "strided_index": 2,
            "mem_chunk": 2,
            "unroll": 8,
            "comp_mode": true,
            "affine_to_cpu": false
        },
        {
            "index": 2,
            "intensity": 928,
            "worksize": 8,
            "strided_index": 2,
            "mem_chunk": 2,
            "unroll": 8,
            "comp_mode": true,
            "affine_to_cpu": false
        },		
        {
            "index": 3,
            "intensity": 928,
            "worksize": 8,
            "strided_index": 2,
            "mem_chunk": 2,
            "unroll": 8,
            "comp_mode": true,
            "affine_to_cpu": false
        },
        {
            "index": 3,
            "intensity": 928,
            "worksize": 8,
            "strided_index": 2,
            "mem_chunk": 2,
            "unroll": 8,
            "comp_mode": true,
            "affine_to_cpu": false
        },		
        {
            "index": 4,
            "intensity": 928,
            "worksize": 8,
            "strided_index": 2,
            "mem_chunk": 2,
            "unroll": 8,
            "comp_mode": true,
            "affine_to_cpu": false
        },
        {
            "index": 4,
            "intensity": 928,
            "worksize": 8,
            "strided_index": 2,
            "mem_chunk": 2,
            "unroll": 8,
            "comp_mode": true,
            "affine_to_cpu": false
        },		
        {
            "index": 5,
            "intensity": 928,
            "worksize": 8,
            "strided_index": 2,
            "mem_chunk": 2,
            "unroll": 8,
            "comp_mode": true,
            "affine_to_cpu": false
        },
        {
            "index": 5,
            "intensity": 928,
            "worksize": 8,
            "strided_index": 2,
            "mem_chunk": 2,
            "unroll": 8,
            "comp_mode": true,
            "affine_to_cpu": false
        }		
    ],
    "user-agent": null,
    "syslog": false,
    "watch": false
}

**Comment by lamgztey** [comment]
![image](https://user-images.githubusercontent.com/32880928/48225976-65f5b080-e396-11e8-9e2d-02e6ffcaba16.png)

**Comment by lamgztey** [comment]
![image](https://user-images.githubusercontent.com/32880928/48226076-a9501f00-e396-11e8-9853-9330b9991c91.png)

**Comment by lamgztey** [comment]
![image](https://user-images.githubusercontent.com/32880928/48226124-cd136500-e396-11e8-95d8-c9fa42215786.png)

**Comment by lamgztey** [comment]
![image](https://user-images.githubusercontent.com/32880928/48229419-e4a31b80-e39f-11e8-960e-3931b78b593a.png)

**Comment by xmrig** [comment]
Your GPUs is 4 GB or 8 GB? this error means your GPU is out of memory and you should reduce intensity.

928 it's about 3712 MB (928 * 4), to know max available memory size please show `clinfo` output.
Thank you.

**Comment by lamgztey** [comment]
My GPU 4G !!! 
![image](https://user-images.githubusercontent.com/32880928/48260770-4a021580-e44f-11e8-8ebf-18d1893d9d8c.png)

**Comment by xmrig** [comment]
https://github.com/xmrig/xmrig/releases/tag/v4.0.0-beta
