### ISSUE TITLE
AMD RX470 - Speed only 580 hashes/r

### ISSUE THREAD

**Issue by imrecsoka** [xmrig/xmrig-amd#19]
Hi, i seem to get low speeds using XMRIG AMD:
![image](https://user-images.githubusercontent.com/25494601/33417975-5b5329e4-d5ac-11e7-856d-19806f37f62b.png)

I normally get 650 hashes/s with Claymore or SGMiner  - so about 1900 hashes for 3 cards with 4GB ram.

Is this a known issue

**Comment by gboelter** [comment]
What are your settings for your RX470 in config.json ....?

**Comment by imrecsoka** [comment]
I will look for you when i am home thanks

**Comment by dkarma** [comment]
i'm getting slow hashing from my 580 as well:
[2017-12-31 15:22:19] speed 10s/60s/15m 572.9 572.9 568.7 H/s max: 573.5 H/s
[2017-12-31 15:22:19] GPU 0 10s/60s/15m 572.9 572.9 568.7 H/s
[2017-12-31 15:22:19] speed 10s/60s/15m 572.9 572.9 568.7 H/s max: 573.5 H/s
[2017-12-31 15:23:00] speed 10s/60s/15m 572.5 572.5 568.6 H/s max: 573.5 H/s


my configfile is:
{
    "algo": "cryptonight",
    "background": false,
    "colors": true,
    "donate-level": 5,
    "log-file": null,
    "print-time": 60,
    "retries": 5,
    "retry-pause": 5,
    "syslog": false,
    "opencl-platform": 0,
    "threads": [
           {
            "index": 0,
            "intensity": 950,
            "worksize": 8,
            "affine_to_cpu": false
        }

**Comment by noctrex** [comment]
Have you tried different intensity and worksize combinations? Usually it need a little bit tinkering with the default values provided. I raised the intensity from 512 to 760 on my HD 7850 config and I gained about +50 hashes

**Comment by xmrig** [comment]
https://github.com/xmrig/xmrig/releases/tag/v4.0.0-beta
