### ISSUE TITLE
Only getting compute errors in 2.8.4 and 2.8.5

### ISSUE THREAD

**Issue by RadeonBEN** [xmrig/xmrig-amd#194]
Dear all,

I was using XMRig AMD with a RX480 and 17.12.2 radeon drivers. >> No issues at all
BUT getting only compute errors with any other drivers. (never understand why...)

I am currently using an ASUS RX560 (to do some test before adding other GPU) however I am only getting compute error. Here is the list of setup I have tried (only with a RX560 2go):

-XMRig AMD 2.8.4 with **17.12.2** drivers>> only getting errors
-XMRig AMD 2.8.4 with **18.5.1** drivers>> only getting errors
-XMRig AMD 2.8.4 with **18.6.1** drivers>> only getting errors
-**XMRig AMD 2.8.5** with 18.6.1 drivers>> only getting errors

![image](https://user-images.githubusercontent.com/45048747/48509929-b23b6780-e852-11e8-92f1-fc657987eefb.png)

Example
![image](https://user-images.githubusercontent.com/45048747/48509868-8d46f480-e852-11e8-8d98-dbfa7030da9e.png)

I have no idea of what I can do... Could you help me?

Here is the config file to mine AEON that I use:

{
    "algo": "cryptonight-lite",
    "api": {
        "port": 0,
        "access-token": null,
        "id": null,
        "worker-id": null,
        "ipv6": false,
        "restricted": true
    },
    "autosave": true,
    "background": false,
    "cache": true,
    "colors": true,
    "donate-level": 2,
    "log-file": null,
    "opencl-platform": "AMD",
    "opencl-loader": "OpenCL.dll",
    "pools": [
        {
            "url": "pool.aeon.hashvault.pro:5555",
            "user": "xxx",
            "pass": "xxx",
            "rig-id": null,
            "nicehash": false,
            "keepalive": false,
            "variant": -1,
            "tls": false,
            "tls-fingerprint": null
        }
    ],
    "print-time": 60,
    "retries": 5,
    "retry-pause": 5,
    "threads": [
        {
            "index": 0,
            "intensity": 672,
            "worksize": 8,
            "strided_index": 2,
            "mem_chunk": 2,
            "unroll": 8,
            "comp_mode": true,
            "affine_to_cpu": false
        }
    ],
    "user-agent": null,
    "syslog": false,
    "watch": false
}

Another file to mine Lethean:

{
    "algo": "cryptonight",
    "api": {
        "port": 0,
        "access-token": null,
        "id": null,
        "worker-id": null,
        "ipv6": false,
        "restricted": true
    },
    "autosave": true,
    "background": false,
    "cache": true,
    "colors": true,
    "donate-level": 5,
    "log-file": null,
    "opencl-platform": "AMD",
    "opencl-loader": "OpenCL.dll",
    "pools": [
        {
            "url": "pool.lethean.hashvault.pro:3333",
            "user": "xx",
            "pass": "xx",
            "rig-id": null,
            "nicehash": false,
            "keepalive": false,
            "variant": -1,
            "tls": false,
            "tls-fingerprint": null
        }
    ],
    "print-time": 60,
    "retries": 5,
    "retry-pause": 5,
    "threads": [
        {
            "index": 0,
            "intensity": 672,
            "worksize": 8,
            "strided_index": 2,
            "mem_chunk": 2,
            "unroll": 8,
            "comp_mode": true,
            "affine_to_cpu": false
        }
    ],
    "user-agent": null,
    "syslog": false,
    "watch": false
}

Thanks a lot in advance for any help

**Comment by xmrig** [comment]
First try recent dev version https://download.xmrig.com/xmrig-amd/2.8.6-dev/a43020b1c20bb01f5e0cb9f3ca7b0d9c626d5ea9/
If it not help, I will check tomorrow on RX 560, same Baffin with 14 cu, but with 4GB of memory. Also what about your CPU (miner show this information on startup) and motherboard, your GPU runs is PCIe 1.1 mode.
Thank you.

**Comment by xmrig** [comment]
Looks like some incompatibility issue, RX 560 works fine https://i.imgur.com/MZIwbgY.png but if I start GPU-Z, card stop hashing after some random period of time, exactly like your last screenshot.

**Comment by RadeonBEN** [comment]
Ok, i will try without gpu z. And with a rx570 instead too.

I ll keep you in touch.

**Comment by unsivilaudio** [comment]
Also have you been removing the opencl cache between driver changes?

**Comment by RadeonBEN** [comment]
Unsivilaudio, tell me how you do it (I am not sur of what you are talking about)

**Comment by unsivilaudio** [comment]
WIN+R, type in "%localappdata%" and hit enter, it will open a folder.
Delete the files in ".openclcache" and restart the miner.

**Comment by RadeonBEN** [comment]
So GPUZ or not change nothing for me, a bit better after the cache destruction

![image](https://user-images.githubusercontent.com/45048747/48569268-80cda500-e901-11e8-8d82-8957e6ca12dd.png)


But not perfect...

**Comment by RadeonBEN** [comment]
Some big instability after several minutes of mining

![image](https://user-images.githubusercontent.com/45048747/48570991-03586380-e906-11e8-9f58-6c98236b5e13.png)

**Comment by unsivilaudio** [comment]
OMG sorry, I told you the cache location of xmr-stak.

The cache for xmrig is in, "/xmrig/.cache/"  same location %localappdata%

**Comment by RadeonBEN** [comment]
Don t worry,

So same issues with my RX 570 XFX:
With 2.8.5 with 18.5.1 drivers/ only errors
With 2.8.6 with 18.5.1 : some accepted and some errors
![image](https://user-images.githubusercontent.com/45048747/48575196-8f23bd00-e911-11e8-824f-44edee38ee7a.png)

**Comment by RadeonBEN** [comment]
Hi everyone,

Some news,
I have fully reinstall my computer with only WIN10, Radeon driver 18.5.1 and xmrig.
It works with my RX560 or with my RX570.
However during the night my RX560 has stopped working with XMRig 2.8.5.

I have just restarted with Xmrig 2.8.5. Let see the result

We can close this issue. I will open another one if it stops hashing again.

The problem was certainly an incompability between software or drivers...
