### ISSUE TITLE
Will this work to support newer Adrenlin driver version?

### ISSUE THREAD

**Issue by JungleCatSW** [xmrig/xmrig-amd#199]
I noticed ethminer are shipping precompiled binaries of the open cl kernels, https://github.com/ethereum-mining/ethminer/tree/master/libethash-cl/kernels/bin
Is it possible to do something like this in Xmrig and precompile them with Adrenaline version < 18.2. Do you think this will work to support Adrenalin version 18.10+

**Comment by UnclWish** [comment]
Connect to question! Need support for new drivers!

**Comment by JungleCatSW** [comment]
@xmrig any idea if this is worth doing ?

**Comment by xmrig** [comment]
https://github.com/xmrig/xmrig/releases/tag/v4.0.0-beta
