### ISSUE TITLE
Failed to start threads.

### ISSUE THREAD

**Issue by Amirhz9479** [xmrig/xmrig-amd#200]
I have some ATI Radeon HD 4300/4500 Serie
When I try to run xmrig-amd, xmrig shows me:
`found AMD platform index: 0, name: Advanced Micro Devices, Inc.`
`found OpenCL GPU: ATI Radeon HD 4300/4500 Series (ATI RV710), cu: 2`
`Failed to start threads.`
how can I fix this?

edit:

My config.json
`{`
`    "algo": "cryptonight",`
`    "api": {`
`        "port": 0,`
`        "access-token": null,`
`        "worker-id": null,`
`        "ipv6": false,`
`        "restricted": true`
`    },`
`    "background": false,`
`    "colors": true,`
`    "donate-level"`: 1,
`    "log-file": null,`
`    "opencl-platform": "AMD",`
`    "pools": [`
`        {`
`            "url": "xx",`
`            "user": "xx",`
`            "pass": "x",`
`            "keepalive": true,`
`            "nicehash": false,`
`            "variant": -1,`
`            "tls": false,`
`            "tls-fingerprint": null`
`        }`
`    ],`
`    "print-time": 60,`
`    "retries": 5,`
`    "retry-pause": 5,`
`    "syslog": false,`
`    "threads": null`
`}`

made by [xmrig-config](https://config.xmrig.com)

**Comment by Amirhz9479** [comment]
hello?

**Comment by alphagocc** [comment]
Same Problem

**Comment by marcel1974** [comment]
I have similar problem. Radeon HD 6850
 
XMRig-AMD 2.14.1
 built on Mar 16 2019 with GCC 5.3.0
 features: 64-bit AES

libuv/1.8.0
microhttpd/0.9.42
OpenSSL/1.0.1e

* ABOUT        XMRig-AMD/2.14.1 gcc/5.3.0
 * LIBS         libuv/1.8.0 OpenCL/2.0 OpenSSL/1.0.1e microhttpd/0.9.42
 * CPU          Intel(R) Xeon(R) CPU           E5345  @ 2.33GHz x64 -AES
 * ALGO         cryptonight, donate=5%
 * POOL #1      192.168.0.200:3311 variant auto
 * COMMANDS     hashrate, pause, resume
[2019-03-16 11:35:57] compiling code and initializing GPUs. This will take a while...
[2019-03-16 11:35:57] found AMD platform index: 0, name: Advanced Micro Devices, Inc.
[2019-03-16 11:35:57] found OpenCL GPU:  (Barts), cu: 12
[2019-03-16 11:35:57] Failed to start threads.

**Comment by TopherBrowne** [comment]
ditto...no cmake or make errors. xmrig using same config.json without problems.

Christophers-iMac:Monero christopherbrowne$ ./xmrig-amd-notls
 * ABOUT        XMRig-AMD/2.14.1 clang/10.0.0
 * LIBS         libuv/1.26.0 OpenCL/1.2 microhttpd/0.9.62 
 * CPU                 Intel(R) Core(TM) i5-2400S CPU @ 2.50GHz x64 AES
 * ALGO         cryptonight, donate=5%
 * POOL #1      monerohash.com:2222 variant auto
 * COMMANDS     hashrate, pause, resume
[2019-03-19 22:54:32] compiling code and initializing GPUs. This will take a while...
[2019-03-19 22:54:32] found OpenCL GPU: ATI Radeon HD 6750M, cu: 6
[2019-03-19 22:54:32] Failed to start threads.

**Comment by calvintam236** [comment]
It happened to me too. v2.14.1 binary with ROCm 2.2.31 on RX470.

**Comment by scoobybejesus** [comment]
Happened to me.  Lubuntu 16.04.  Was mining fine, I think.  Ran `apt update` and `apt upgrade`, and then failed to start threads. Built latest tag. Same result.  Built master.  Same result.

![Screen Shot 2019-03-23 at 13 04 57](https://user-images.githubusercontent.com/21372487/55378053-76452e00-54e5-11e9-9f9b-e5e24fa0f348.jpeg)

**Comment by Amirhz9479** [comment]
someone help us

**Comment by NmxMilk** [comment]
Hi all,
I had same problem today with my RX 550 card after Windows mars update.
Neither v2.14 nor v2.14.1 worked no more.
The message indicates that the OCL core lib is failing to create the required threads.
After digging here is what I found/done:
- the radeon settings won't launch neither
- the device manager showed my RX card as not working, this looks as a driver update happened
- since my card bios has been touched, I repatched with "atikmdag-patcher"
- rebooted and my card was detected fine
- retried xmrig and this time it worked
Not sure the linux guy is having the same problem, but hope other windows are in the same case.

**Comment by marcel1974** [comment]
Is this project still active !!!! It has been quite some time since dev support said anything about it. Yes , No ,Dont Know , We Know about the problem, Dont Know How to Fix It..... 
It is broken.

**Comment by Spudz76** [comment]
Couple different issues here.

Antique GPUs before GCN2 require also ancient driver not newer than 15.x.  All newer drivers can't mine correctly on anything before Hawaii or so (GCN2).  This is true for all AMD miner apps, they broke OpenCL on old models in the newer drivers and never fixed it.  No client-side workarounds exist, it is broken, in the driver.  Luckily, the 15.7 or newer will work on Win10 so you don't have to revert to Win7.  Linux you do have to revert to Ubuntu 14 so that the kernel is old enough to run the 15.x fglrx driver.

RX or newer users it seems 18.6.1 is the best, unless Linux then ROCm latest trunk, otherwise probably random problems.

**Comment by UpperNickel** [comment]
> Couple different issues here.
> 
> Antique GPUs before GCN2 require also ancient driver not newer than 15.x. All newer drivers can't mine correctly on anything before Hawaii or so (GCN2). This is true for all AMD miner apps, they broke OpenCL on old models in the newer drivers and never fixed it. No client-side workarounds exist, it is broken, in the driver. Luckily, the 15.7 or newer will work on Win10 so you don't have to revert to Win7. Linux you do have to revert to Ubuntu 14 so that the kernel is old enough to run the 15.x fglrx driver.
> 
> RX or newer users it seems 18.6.1 is the best, unless Linux then ROCm latest trunk, otherwise probably random problems.

So there's nothing that I can do to get my Radeon HD 6870 to mine?

**Comment by marcel1974** [comment]
I also can't get my HD6850 to mine. Not even on Ubuntu 14. I cant even test with old versions of xmrig as it has been removed without warning

**Comment by Spudz76** [comment]
It's not just Ubuntu 14 but also ubuntu 14 not the final release, I forget which exactly but if you use the newest installer then you will have to revert the kernel to 3.2.0 or something (you don't want the LTS-HWE-etc one)

then install fglrx via finding these three files somewhere, and `dpkg -i`:
```
073d8f61719a878f79fdf1e1f8b136a5  fglrx_13.152-0ubuntu1_amd64.deb
81b0b53b9e875afb9def749a60c180f2  fglrx-amdcccle_13.152-0ubuntu1_amd64.deb
fd11515212386709774eccbaf930f036  fglrx-dev_13.152-0ubuntu1_amd64.deb
```
Once that fglrx works (don't forget to blacklist radeon, amdgpu, etc) then clinfo should work (and show correct total memory) and mining should work.

The fglrx from Debian is 15.something and does not work at all, do not install fglrx with apt, but only from above files with matching checksums and dpkg.

There could have been some change more recently in xmrig-amd that broke pre-CL2.0 though, I have not tried in a while, but this recipe did work for xmr-stak before CN-R but I believe after CN2v2 ("CN-V8").  I did not use xmrig back then so I do not know, but miners definitely do not work on any other driver.  flgrx is probably OpenCL 1.2 only.  If xmrig-amd truly stopped working on OpenCL 1.2 then you will have to go use xmr-stak as I'm pretty sure it still does a 1.2 mode.

Also HD5570 (evergreen core, before any of the "islands" chips) no longer work even with this recipe, as some old GPUs don't have a required rounding mode (but those will fail to compile and say the feature is missing, not just fail or hang).  But they did work up to CN2v1 ("CN-V7").  And probably still work for some "V8-based" algos just not CN-R for sure.

**Comment by xmrig** [comment]
https://github.com/xmrig/xmrig/releases/tag/v4.0.0-beta
