### ISSUE TITLE
Custom path to OpenSSL for cmake under MacOS

### ISSUE THREAD

**Issue by Unnameless** [xmrig/xmrig-amd#201]
Hi,

Because Apple deprecated ssl in macos 10.14, we have to go the openssl route.

Thankfully it's a breze to install with with hombrew. The path is: /usr/local/opt/openssl

How can I add this path to the cmake file and where. Openssl has bin dir for binaries, lib etc.

**Comment by djfinch** [comment]
```
cmake .. -DUV_LIBRARY=/usr/local/lib/libuv.a -DOPENSSL_SSL_LIBRARY=/usr/local/opt/openssl/lib/libssl.a -DOPENSSL_CRYPTO_LIBRARY=/usr/local/opt/openssl/lib/libcrypto.a
```
