### ISSUE TITLE
Strange GPU detection/hread number and crash in 2.8.6

### ISSUE THREAD

**Issue by RadeonBEN** [xmrig/xmrig-amd#202]
Hello everyone,

I was using a RX570 XFX to mine with the graft with XMrig 2.8.6 and I was around 580h/s.

Then I have add a RX560 and there are 2 things strange:

-Firstly XMrig tells me that I have 2 RX560 (but just the name, it gives to them different intensities...)
![image](https://user-images.githubusercontent.com/45048747/48859542-9853d480-edbe-11e8-9258-65915f45f7ca.png)

-Secondly it creates 2 thread by card, I say why not, it s faster. But why does he chosen that now? Why hasn t it do that with only my RX570?
![image](https://user-images.githubusercontent.com/45048747/48859677-07c9c400-edbf-11e8-90c8-ff8404b6b95b.png)

It's not really issues but mainly questions.

Thanks for your help.

**Comment by xmrig** [comment]
Can you show `clinfo` definitely wrong names is a bug, but I don't know where it come from, because other information is looks good.

Double threads is better for this GPUs, but auto config is still not optimal, you can try higher `intensity` for each thread and looks like real RX560 hashing OK.
Thank you.

**Comment by RadeonBEN** [comment]
Thanks for all these answer... I am a bit a nooby...how to find the clinfo? Stupid question I know

**Comment by xmrig** [comment]
It usually installed with driver, Start -> cmd -> type `clinfo` and Enter, it will show a lot of info, if it works, better run `clinfo > clinfo.txt` and send resulting clinfo.txt file some how.
Thank you.

**Comment by RadeonBEN** [comment]
Hi,

Maybe this thing will help you:
[info.txt](https://github.com/xmrig/xmrig-amd/files/2609325/info.txt)


Some new stuff:

I have changed the RX560 by an asus RX470 (so the main is a RX570 and the second one a RX470) and I have still the issue:
![image](https://user-images.githubusercontent.com/45048747/48922987-d8908100-eeaa-11e8-8fe0-bf391e34e951.png)

I have done some tests:
-RYO mining in 2.8.4: auto conf creates 1 thread by GPU>> OK
-RYO mining in 2.8.6: auto conf creates 2 thread by GPU >>> CRASH impossible to mine, the computer restart(GPU memomry over loaded? 4go by GPU)
-RYO mining in 2.8.6: auto conf and 1 thread by GPU removed>> no problem
-Lethean/Graft in 2.8.6: auto conf creates 2 thread by GPU >> NO issues at all

**Comment by RadeonBEN** [comment]
Update:

Big instabillity issue in 2.8.6 with monero mining (wants to create 2 thread by GPU)...

In 2.8.4 with 1 thread by GPU >>no issues

With the JSON create by the soft 2.8.4 and if I use it in 2.8.6 miner (so 1 thread by GPU) >> no issues

**Comment by RadeonBEN** [comment]
Yeah I have tested with other miner version and same name issue... (I haven t seen that before because I was using always a single gpu).
I know it isn t the file you asked me.windows do the job with the command line and create a file...bit even by starting a research on the complete SSD...nothing found...

**Comment by Leonyxtested** [comment]
Hi

I have the same problem, I have 4 threads, 2 for each GPU, (1 RX 580 4G and 1 RX 560 4G), the RX 560 does the job well but the RX 580 does not, there is also an increase in RAM consumption, going from 140 Mb to 5.5 Gb. There is also a drop in intensity for no reason.

------

Hi

Yo tengo el mismo problema, me aparecen 4 hilos, 2 para cada GPU,(1 RX 580 4G y 1 RX 560 4G), la RX 560 realiza el trabajo bien pero la RX 580 no, tambien se produce un aumento del consumo de RAM, pasa de  140 Mb a 5,5 Gb. Tambien se produce una bajada de intensidad sin motivo.

**Comment by xmrig** [comment]
https://github.com/xmrig/xmrig/releases/tag/v4.0.0-beta
