### ISSUE TITLE
THREAD #0 COMPUTE ERROR in 2.8.6

### ISSUE THREAD

**Issue by kimxilxyong** [xmrig/xmrig-amd#205]
I am using amdgpu-pro-18.40-676022-ubuntu-18.04 and am getting THREAD #0 COMPUTE ERROR instead of accepted. 2.8.5 is working normally. Algo is cn/2. I compiled with gcc 6, ubuntu 18.04.
Any idea what it could be?
[xmrig286_failure.txt](https://github.com/xmrig/xmrig-amd/files/2613156/xmrig286_failure.txt)
[clinfo.txt](https://github.com/xmrig/xmrig-amd/files/2613157/clinfo.txt)
[config_make_binary286.zip](https://github.com/xmrig/xmrig-amd/files/2614506/config_make_binary286.zip)

Edit:
Just to be sure i downloaded the xmrig-amd-2.8.6-xenial-x64.tar.gz binary and its the same error.

My linux kernel is 4.19.4-041904-generic

**Comment by kimxilxyong** [comment]
Im not sure if i understand. 
Are you saying that its a amdgpu-pro problem? I have never used 18.10, i started a fresh ubuntu install with 18.40, never used 18.10.
And with cache files you mean the xmrig OpenCL program cache (=the precompile CL)?

Is it working for you and are you using the 18.10 amdgpu-pro drivers?

**Comment by rsguru** [comment]
Well, there is a explanation here: [https://github.com/xmrminer01102018/VegaToolsNConfigs/blob/master/VegaUbuntuGuideForCNv2](url)
It is a little bit of work, but it is working for me. I had the same issues before.

**Comment by kimxilxyong** [comment]
Thanks for this info
