### ISSUE TITLE
New drivers support.

### ISSUE THREAD

**Issue by UnclWish** [xmrig/xmrig-amd#206]
Authors, does you plannig to add latest Adrenalin drivers (18.9.x, 18.10.x, 18.11.x) support without compute errors?

**Comment by unsivilaudio** [comment]
That has nothing to do with the dev of xmrig.  Thats all on AMD. They shipped a broken opencl compiler with newer drivers.

**Comment by UnclWish** [comment]
Maybe it's possible somehow to add opencl compiler into miner to use right compiler, not from drivers?

**Comment by xmrig** [comment]
https://github.com/xmrig/xmrig/releases/tag/v4.0.0-beta works fine with recent drivers.
