### ISSUE TITLE
how to Config wallet address

### ISSUE THREAD

**Issue by lyunfun** [xmrig/xmrig-amd#21]
how to Config wallet address,wheren can i input wallet address

**Comment by alexcom** [comment]
I believe you need a field **user** in pool definition. Here's extract from my config:
"pools": [
        {
            "url": "stratum+tcp://xmr-eu1.nanopool.org:14444",
            "user": "45kk3tKTyqKFHJgoA8khHLJxMWrDU5rD814akNwS12Dki1dTVvqo7to6U8sEeNd9PuQhq36TvMGyCgr45J8Age694KLoBDQ.test", // this is it along with worker after the dot
            "pass": "x",
            "keepalive": true,
            "nicehash": false
        }
    ]

**Comment by xmrig** [comment]
https://github.com/xmrig/xmrig/releases/tag/v4.0.0-beta
