### ISSUE TITLE
Card showing N/A when trying to run CN-PICO/TRTL Help!

### ISSUE THREAD

**Issue by paintufast** [xmrig/xmrig-amd#221]
I am running a rig with RX 580s. I have one card that hashes EthHash just fine but when I switch over to this algo using XMRig-AMD (Through HiveOS). I have one card that was working yesterday and now is showing N/A and my overall hashrate is down that card.

However that card looks like it configures properly on startup in miner Log. And looking at the card it is running at a wattage that would imply it is working, not sitting idle. 

Thoughts? I am hearing I may need to change intensity but struggling to figure that out. 

I am at a loss

**Comment by netmebtc** [comment]
I have met the same issue. My 6 x vega56 rig  windows10 amddrv18.6.1, when running xmrig-amd cn/trtl algo for servral hours, one card showing N/A and no hashrate  .  Then I closed the xmrig-amd2.11.1, did not restart rig,  On the same rig I started SRBminer to run cn/trtl algo for a long time, ervery card is working fine , no card showing N/A.

**Comment by asylum119** [comment]
if its a single card issue then is that GPU running too hot ?
my second GPU ran too hot with cn/trtl (first GPU cools more due to the seconnd GPUs fans) so i underclocked the second GPU rather than adding extra fanage to keep the temp down.

**Comment by netmebtc** [comment]
When the problem was occured, I stop xmrig-amd.exe and try start xmrig-amd agin at once, then every card was working fine, After serveral hours ,It will be occured again.  The card which showing N/A seems not crashed, but just sleeping or stucked by someting.

**Comment by paintufast** [comment]
So turns out I had gotten some bad advice on OC settings. I was told this algo is power hungry and to run at 1300 core. Got straightened out and running cards at 1100/900/2100 and all is well. It was just a bad OC setting issue. Thank you everyone for the suggestions and help. I appreciate it!
