### ISSUE TITLE
gpu amd не видит мою видеокарту на ноутбуке. Возможно ли как-то это исправить?

### ISSUE THREAD

**Issue by wolfimen** [xmrig/xmrig-amd#230]
Майнер gpu amd не видит мою видеокарту на ноутбуке. Запуск происходит, но все показатели 0. Возможно ли как-то это исправить?
Спасибо!

**Comment by bizlevel** [comment]
Никаких данных не расписал - никто не поможет!

**Comment by wolfimen** [comment]
Приветствую вас! Хочу сделать кран бесплатной раздачи, для монеты
turtlecoin. Привязать его к официальному сайту. Как сделать сайт и кран, я
знаю. А вот как привязать именно определённую крипто валюту, нет. Вот в чём
загвоздка.

вс, 10 мар. 2019 г. в 16:30, Olexandr Minzak <notifications@github.com>:
