### ISSUE TITLE
Vega56 Cryptonight Heavyx

### ISSUE THREAD

**Issue by R00dNet** [xmrig/xmrig-amd#237]
Hi

I am only seeing around 440+ hs on vega56. It does not have modded bios. However in xmrig I see the max speed it hits is around double that. hashrate will go up to 880+ then back down. Below are the settings I use to get hashrate speed as is. Can anyone please enlighten me as to anything I may have done wrong? or is this speed and behaviour normal?

Card memory is clocked upto 930, nothing major.

{
    "algo": "cryptonight/double",
    "api": {
        "port": 0,
        "access-token": null,
        "id": null,
        "worker-id": null,
        "ipv6": false,
        "restricted": true
    },
    "autosave": true,
    "background": false,
    "cache": true,
    "colors": true,
    "donate-level": 1,
    "log-file": null,
    "opencl-platform": "AMD",
    "opencl-loader": "OpenCL.dll",
    "pools": [
        {
            "url": "xcash.luckypool.io:4488",
            "user": "walletaddress",
            "pass": "roodAMD",
            "rig-id": null,
            "nicehash": false,
            "keepalive": false,
            "variant": -1,
            "enabled": true,
            "tls": false,
            "tls-fingerprint": null
        }
    ],
    "print-time": 60,
    "retries": 5,
    "retry-pause": 5,
    "threads": [
        {
            "index": 0,
            "intensity": 1024,
            "worksize": 16,
            "strided_index": 2,
            "mem_chunk": 1,
            "unroll": 8,
            "comp_mode": true,
            "affine_to_cpu": false
        }	],
    "user-agent": null,
    "syslog": false,
    "watch": true
}

**Comment by R00dNet** [comment]
in fact this speed hike happens on all devices. see max speed. touches it then drops right back down... can anyone please help out with this? first time mining heavyx not sure if this is correct behaviour or not

![cryptonight heavyx](https://user-images.githubusercontent.com/37847231/54277677-727a5780-4588-11e9-9820-743342b1110c.png)

**Comment by unsivilaudio** [comment]
I did a quick test on it to find optimal settings for my Vega (1500core/1100mem) and came up with these.
http://prntscr.com/mzmaec
Your settings probably aren't your problem, what driver version are you using?

**Comment by R00dNet** [comment]
18.6.1 drivers

If that is your settings for 1 vega56 card then I think I have made a mistake in the config. it appears I am missing another area for second thread. will redo config file

**Comment by Spudz76** [comment]
`algo: "cryptonight/double"` seems wrong also; it should be `algo: "cryptonight-heavy"` ??
