### ISSUE TITLE
cant generate json file?

### ISSUE THREAD

**Issue by rafise** [xmrig/xmrig-amd#240]
How to generate the config.json file? here what I'm getting, any idea how can get this? thaks

$ ./xmrig-amd
unable to open "/home/box/xmrig-amd/build/config.json".
No valid configuration found. Exiting.

**Comment by rafise** [comment]
anyone know how to generate the json file??

**Comment by xmrig** [comment]
1. Copy and edit sample from source `cp ../src/config.json .` https://github.com/xmrig/xmrig-amd/blob/master/src/config.json
2. Use https://config.xmrig.com/amd

**Comment by rafise** [comment]
thanks

**Comment by xmrig** [comment]
https://github.com/xmrig/xmrig/releases/tag/v4.0.0-beta
