### ISSUE TITLE
Mojave fresh install : issue with gnutls lib ?

### ISSUE THREAD

**Issue by LeChatNoir69** [xmrig/xmrig-amd#242]
Trying to compile the dev branch on Mojave fresh install. The linker can't find gnutls references.

Cmake is ok :
cmake .. -DUV_LIBRARY=/usr/local/opt/libuv/lib/libuv.a -DMHD_LIBRARY=/usr/local/opt/libmicrohttpd/lib/libmicrohttpd.a -DWITH_TLS=OFF
-- The C compiler identification is AppleClang 10.0.0.10001145
-- The CXX compiler identification is AppleClang 10.0.0.10001145
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found UV: /usr/local/opt/libuv/lib/libuv.a  
-- The ASM compiler identification is AppleClang
-- Found assembler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Looking for syslog.h
-- Looking for syslog.h - found
-- Found MHD: /usr/local/opt/libmicrohttpd/lib/libmicrohttpd.a  
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/lechat/Documents/Devel/Miner/BuildXmrig/xmrig-amd/build

But make fails :
Scanning dependencies of target xmrig-asm
[  1%] Building ASM object CMakeFiles/xmrig-asm.dir/src/crypto/asm/cn_main_loop.S.o
[  2%] Building ASM object CMakeFiles/xmrig-asm.dir/src/crypto/asm/CryptonightR_template.S.o
[  4%] Linking C static library libxmrig-asm.a
[  4%] Built target xmrig-asm
Scanning dependencies of target xmrig-amd-notls
[  5%] Building CXX object CMakeFiles/xmrig-amd-notls.dir/src/amd/OclCache.cpp.o
[  7%] Building CXX object CMakeFiles/xmrig-amd-notls.dir/src/amd/OclCLI.cpp.o
[  8%] Building CXX object CMakeFiles/xmrig-amd-notls.dir/src/amd/OclCryptonightR_gen.cpp.o
[ 10%] Building CXX object CMakeFiles/xmrig-amd-notls.dir/src/amd/OclGPU.cpp.o
[ 11%] Building CXX object CMakeFiles/xmrig-amd-notls.dir/src/amd/OclLib.cpp.o
[ 13%] Building CXX object CMakeFiles/xmrig-amd-notls.dir/src/api/NetworkState.cpp.o
[ 14%] Building CXX object CMakeFiles/xmrig-amd-notls.dir/src/App.cpp.o
[ 15%] Building CXX object CMakeFiles/xmrig-amd-notls.dir/src/base/io/Json.cpp.o
[ 17%] Building CXX object CMakeFiles/xmrig-amd-notls.dir/src/base/io/Watcher.cpp.o
[ 18%] Building CXX object CMakeFiles/xmrig-amd-notls.dir/src/base/kernel/Entry.cpp.o
[ 20%] Building CXX object CMakeFiles/xmrig-amd-notls.dir/src/base/kernel/Process.cpp.o
[ 21%] Building CXX object CMakeFiles/xmrig-amd-notls.dir/src/base/kernel/Signals.cpp.o
[ 23%] Building CXX object CMakeFiles/xmrig-amd-notls.dir/src/base/net/Pool.cpp.o
[ 24%] Building CXX object CMakeFiles/xmrig-amd-notls.dir/src/base/net/Pools.cpp.o
[ 26%] Building CXX object CMakeFiles/xmrig-amd-notls.dir/src/base/tools/Arguments.cpp.o
[ 27%] Building CXX object CMakeFiles/xmrig-amd-notls.dir/src/base/tools/Handle.cpp.o
[ 28%] Building CXX object CMakeFiles/xmrig-amd-notls.dir/src/base/tools/String.cpp.o
[ 30%] Building CXX object CMakeFiles/xmrig-amd-notls.dir/src/common/config/CommonConfig.cpp.o
[ 31%] Building CXX object CMakeFiles/xmrig-amd-notls.dir/src/common/config/ConfigLoader.cpp.o
[ 33%] Building CXX object CMakeFiles/xmrig-amd-notls.dir/src/common/config/ConfigWatcher.cpp.o
[ 34%] Building CXX object CMakeFiles/xmrig-amd-notls.dir/src/common/Console.cpp.o
[ 36%] Building CXX object CMakeFiles/xmrig-amd-notls.dir/src/common/cpu/BasicCpuInfo.cpp.o
[ 37%] Building CXX object CMakeFiles/xmrig-amd-notls.dir/src/common/cpu/Cpu.cpp.o
[ 39%] Building CXX object CMakeFiles/xmrig-amd-notls.dir/src/common/crypto/Algorithm.cpp.o
[ 40%] Building CXX object CMakeFiles/xmrig-amd-notls.dir/src/common/crypto/keccak.cpp.o
[ 42%] Building CXX object CMakeFiles/xmrig-amd-notls.dir/src/common/log/BasicLog.cpp.o
[ 43%] Building CXX object CMakeFiles/xmrig-amd-notls.dir/src/common/log/ConsoleLog.cpp.o
[ 44%] Building CXX object CMakeFiles/xmrig-amd-notls.dir/src/common/log/FileLog.cpp.o
[ 46%] Building CXX object CMakeFiles/xmrig-amd-notls.dir/src/common/log/Log.cpp.o
[ 47%] Building CXX object CMakeFiles/xmrig-amd-notls.dir/src/common/net/Client.cpp.o
[ 49%] Building CXX object CMakeFiles/xmrig-amd-notls.dir/src/common/net/Job.cpp.o
[ 50%] Building CXX object CMakeFiles/xmrig-amd-notls.dir/src/common/net/strategies/FailoverStrategy.cpp.o
[ 52%] Building CXX object CMakeFiles/xmrig-amd-notls.dir/src/common/net/strategies/SinglePoolStrategy.cpp.o
[ 53%] Building CXX object CMakeFiles/xmrig-amd-notls.dir/src/common/net/SubmitResult.cpp.o
[ 55%] Building CXX object CMakeFiles/xmrig-amd-notls.dir/src/common/Platform.cpp.o
[ 56%] Building CXX object CMakeFiles/xmrig-amd-notls.dir/src/core/Config.cpp.o
[ 57%] Building CXX object CMakeFiles/xmrig-amd-notls.dir/src/core/Controller.cpp.o
[ 59%] Building CXX object CMakeFiles/xmrig-amd-notls.dir/src/Mem.cpp.o
[ 60%] Building CXX object CMakeFiles/xmrig-amd-notls.dir/src/net/Network.cpp.o
[ 62%] Building CXX object CMakeFiles/xmrig-amd-notls.dir/src/net/strategies/DonateStrategy.cpp.o
[ 63%] Building CXX object CMakeFiles/xmrig-amd-notls.dir/src/Summary.cpp.o
[ 65%] Building CXX object CMakeFiles/xmrig-amd-notls.dir/src/workers/Handle.cpp.o
[ 66%] Building CXX object CMakeFiles/xmrig-amd-notls.dir/src/workers/Hashrate.cpp.o
[ 68%] Building CXX object CMakeFiles/xmrig-amd-notls.dir/src/workers/OclThread.cpp.o
[ 69%] Building CXX object CMakeFiles/xmrig-amd-notls.dir/src/workers/OclWorker.cpp.o
[ 71%] Building CXX object CMakeFiles/xmrig-amd-notls.dir/src/workers/Workers.cpp.o
[ 72%] Building CXX object CMakeFiles/xmrig-amd-notls.dir/src/xmrig.cpp.o
[ 73%] Building CXX object CMakeFiles/xmrig-amd-notls.dir/src/amd/OclCache_unix.cpp.o
[ 75%] Building CXX object CMakeFiles/xmrig-amd-notls.dir/src/App_unix.cpp.o
[ 76%] Building CXX object CMakeFiles/xmrig-amd-notls.dir/src/base/io/Json_unix.cpp.o
[ 78%] Building CXX object CMakeFiles/xmrig-amd-notls.dir/src/common/Platform_mac.cpp.o
[ 79%] Building CXX object CMakeFiles/xmrig-amd-notls.dir/src/Mem_unix.cpp.o
[ 81%] Building C object CMakeFiles/xmrig-amd-notls.dir/src/crypto/c_groestl.c.o
[ 82%] Building C object CMakeFiles/xmrig-amd-notls.dir/src/crypto/c_blake256.c.o
[ 84%] Building C object CMakeFiles/xmrig-amd-notls.dir/src/crypto/c_jh.c.o
[ 85%] Building C object CMakeFiles/xmrig-amd-notls.dir/src/crypto/c_skein.c.o
[ 86%] Building CXX object CMakeFiles/xmrig-amd-notls.dir/src/crypto/CryptoNight.cpp.o
[ 88%] Building CXX object CMakeFiles/xmrig-amd-notls.dir/src/crypto/CryptonightR_gen.cpp.o
[ 89%] Building CXX object CMakeFiles/xmrig-amd-notls.dir/src/common/log/SysLog.cpp.o
[ 91%] Building CXX object CMakeFiles/xmrig-amd-notls.dir/src/api/Api.cpp.o
[ 92%] Building CXX object CMakeFiles/xmrig-amd-notls.dir/src/api/ApiRouter.cpp.o
[ 94%] Building CXX object CMakeFiles/xmrig-amd-notls.dir/src/common/api/Httpd.cpp.o
[ 95%] Building CXX object CMakeFiles/xmrig-amd-notls.dir/src/common/api/HttpRequest.cpp.o
[ 97%] Building CXX object CMakeFiles/xmrig-amd-notls.dir/src/crypto/cn_gpu_avx.cpp.o
[ 98%] Building CXX object CMakeFiles/xmrig-amd-notls.dir/src/crypto/cn_gpu_ssse3.cpp.o
[100%] Linking CXX executable xmrig-amd-notls
Undefined symbols for architecture x86_64:
  "_gnutls_bye", referenced from:
      _MHD_cleanup_connections in libmicrohttpd.a(libmicrohttpd_la-daemon.o)
      _MHD_tls_connection_shutdown in libmicrohttpd.a(libmicrohttpd_la-connection_https.o)
  "_gnutls_certificate_allocate_credentials", referenced from:
      _MHD_start_daemon_va in libmicrohttpd.a(libmicrohttpd_la-daemon.o)
  "_gnutls_certificate_free_credentials", referenced from:
      _MHD_stop_daemon in libmicrohttpd.a(libmicrohttpd_la-daemon.o)
  "_gnutls_certificate_server_set_request", referenced from:
      _internal_add_connection in libmicrohttpd.a(libmicrohttpd_la-daemon.o)
  "_gnutls_certificate_set_dh_params", referenced from:
      _MHD_start_daemon_va in libmicrohttpd.a(libmicrohttpd_la-daemon.o)
  "_gnutls_certificate_set_retrieve_function2", referenced from:
      _MHD_start_daemon_va in libmicrohttpd.a(libmicrohttpd_la-daemon.o)
  "_gnutls_certificate_set_x509_key_mem", referenced from:
      _MHD_start_daemon_va in libmicrohttpd.a(libmicrohttpd_la-daemon.o)
  "_gnutls_certificate_set_x509_key_mem2", referenced from:
      _MHD_start_daemon_va in libmicrohttpd.a(libmicrohttpd_la-daemon.o)
  "_gnutls_certificate_set_x509_trust_mem", referenced from:
      _MHD_start_daemon_va in libmicrohttpd.a(libmicrohttpd_la-daemon.o)
  "_gnutls_cipher_get", referenced from:
      _MHD_get_connection_info in libmicrohttpd.a(libmicrohttpd_la-connection.o)
  "_gnutls_credentials_set", referenced from:
      _internal_add_connection in libmicrohttpd.a(libmicrohttpd_la-daemon.o)
  "_gnutls_deinit", referenced from:
      _internal_add_connection in libmicrohttpd.a(libmicrohttpd_la-daemon.o)
      _MHD_cleanup_connections in libmicrohttpd.a(libmicrohttpd_la-daemon.o)
  "_gnutls_dh_params_deinit", referenced from:
      _parse_options_va in libmicrohttpd.a(libmicrohttpd_la-daemon.o)
      _MHD_stop_daemon in libmicrohttpd.a(libmicrohttpd_la-daemon.o)
  "_gnutls_dh_params_import_pkcs3", referenced from:
      _parse_options_va in libmicrohttpd.a(libmicrohttpd_la-daemon.o)
  "_gnutls_dh_params_init", referenced from:
      _parse_options_va in libmicrohttpd.a(libmicrohttpd_la-daemon.o)
  "_gnutls_global_deinit", referenced from:
      _MHD_fini in libmicrohttpd.a(libmicrohttpd_la-daemon.o)
      __GNUC_deinit_helper_MHD_fini in libmicrohttpd.a(libmicrohttpd_la-daemon.o)
  "_gnutls_global_init", referenced from:
      _MHD_init in libmicrohttpd.a(libmicrohttpd_la-daemon.o)
  "_gnutls_handshake", referenced from:
      _MHD_run_tls_handshake_ in libmicrohttpd.a(libmicrohttpd_la-connection_https.o)
  "_gnutls_init", referenced from:
      _internal_add_connection in libmicrohttpd.a(libmicrohttpd_la-daemon.o)
  "_gnutls_malloc", referenced from:
      _psk_gnutls_adapter in libmicrohttpd.a(libmicrohttpd_la-daemon.o)
  "_gnutls_priority_deinit", referenced from:
      _MHD_start_daemon_va in libmicrohttpd.a(libmicrohttpd_la-daemon.o)
      _parse_options_va in libmicrohttpd.a(libmicrohttpd_la-daemon.o)
      _MHD_stop_daemon in libmicrohttpd.a(libmicrohttpd_la-daemon.o)
  "_gnutls_priority_init", referenced from:
      _MHD_start_daemon_va in libmicrohttpd.a(libmicrohttpd_la-daemon.o)
      _parse_options_va in libmicrohttpd.a(libmicrohttpd_la-daemon.o)
  "_gnutls_priority_set", referenced from:
      _internal_add_connection in libmicrohttpd.a(libmicrohttpd_la-daemon.o)
  "_gnutls_protocol_get_version", referenced from:
      _MHD_get_connection_info in libmicrohttpd.a(libmicrohttpd_la-connection.o)
  "_gnutls_psk_allocate_server_credentials", referenced from:
      _MHD_start_daemon_va in libmicrohttpd.a(libmicrohttpd_la-daemon.o)
  "_gnutls_psk_free_server_credentials", referenced from:
      _MHD_stop_daemon in libmicrohttpd.a(libmicrohttpd_la-daemon.o)
  "_gnutls_psk_set_server_credentials_function", referenced from:
      _internal_add_connection in libmicrohttpd.a(libmicrohttpd_la-daemon.o)
  "_gnutls_record_check_pending", referenced from:
      _process_urh in libmicrohttpd.a(libmicrohttpd_la-daemon.o)
      _recv_tls_adapter in libmicrohttpd.a(libmicrohttpd_la-connection_https.o)
  "_gnutls_record_get_direction", referenced from:
      _MHD_connection_handle_idle in libmicrohttpd.a(libmicrohttpd_la-connection.o)
  "_gnutls_record_recv", referenced from:
      _process_urh in libmicrohttpd.a(libmicrohttpd_la-daemon.o)
      _recv_tls_adapter in libmicrohttpd.a(libmicrohttpd_la-connection_https.o)
  "_gnutls_record_send", referenced from:
      _process_urh in libmicrohttpd.a(libmicrohttpd_la-daemon.o)
      _send_tls_adapter in libmicrohttpd.a(libmicrohttpd_la-connection_https.o)
  "_gnutls_session_get_ptr", referenced from:
      _psk_gnutls_adapter in libmicrohttpd.a(libmicrohttpd_la-daemon.o)
  "_gnutls_session_set_ptr", referenced from:
      _internal_add_connection in libmicrohttpd.a(libmicrohttpd_la-daemon.o)
  "_gnutls_strerror", referenced from:
      _MHD_start_daemon_va in libmicrohttpd.a(libmicrohttpd_la-daemon.o)
      _parse_options_va in libmicrohttpd.a(libmicrohttpd_la-daemon.o)
      _process_urh in libmicrohttpd.a(libmicrohttpd_la-daemon.o)
  "_gnutls_transport_set_int2", referenced from:
      _internal_add_connection in libmicrohttpd.a(libmicrohttpd_la-daemon.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [xmrig-amd-notls] Error 1
make[1]: *** [CMakeFiles/xmrig-amd-notls.dir/all] Error 2
make: *** [all] Error 2

Any idea ?

**Comment by LeChatNoir69** [comment]
gnutls exists :
ls -lrt /usr/local/opt/
total 0
lrwxr-xr-x  1 lechat  admin  22 13 mar 08:30 cmake -> ../Cellar/cmake/3.13.4
lrwxr-xr-x  1 lechat  admin  22 13 mar 22:10 libuv -> ../Cellar/libuv/1.26.0
lrwxr-xr-x  1 lechat  admin  21 13 mar 22:11 gmp -> ../Cellar/gmp/6.1.2_2
lrwxr-xr-x  1 lechat  admin  23 13 mar 22:11 libtasn1 -> ../Cellar/libtasn1/4.13
lrwxr-xr-x  1 lechat  admin  23 13 mar 22:11 libtasn -> ../Cellar/libtasn1/4.13
lrwxr-xr-x  1 lechat  admin  29 13 mar 22:12 libunistring -> ../Cellar/libunistring/0.9.10
lrwxr-xr-x  1 lechat  admin  22 13 mar 22:12 nettle -> ../Cellar/nettle/3.4.1
lrwxr-xr-x  1 lechat  admin  22 13 mar 22:12 libnettle -> ../Cellar/nettle/3.4.1
lrwxr-xr-x  1 lechat  admin  22 13 mar 22:12 libffi -> ../Cellar/libffi/3.2.1
lrwxr-xr-x  1 lechat  admin  25 13 mar 22:12 p11-kit -> ../Cellar/p11-kit/0.23.15
lrwxr-xr-x  1 lechat  admin  24 13 mar 22:12 openssl -> ../Cellar/openssl/1.0.2q
lrwxr-xr-x  1 lechat  admin  24 13 mar 22:12 openssl@1.0 -> ../Cellar/openssl/1.0.2q
lrwxr-xr-x  1 lechat  admin  24 13 mar 22:12 libevent -> ../Cellar/libevent/2.1.8
lrwxr-xr-x  1 lechat  admin  23 13 mar 22:12 unbound -> ../Cellar/unbound/1.9.1
lrwxr-xr-x  1 lechat  admin  27 13 mar 22:12 libgpg-error -> ../Cellar/libgpg-error/1.35
lrwxr-xr-x  1 lechat  admin  25 13 mar 22:12 libgcrypt -> ../Cellar/libgcrypt/1.8.4
lrwxr-xr-x  1 lechat  admin  32 13 mar 22:12 libmicrohttpd -> ../Cellar/libmicrohttpd/0.9.62_1
lrwxr-xr-x  1 lechat  admin  22 13 mar 22:27 gnutls -> ../Cellar/gnutls/3.6.6

**Comment by xmrig** [comment]
If you like to build miner without external libuv and libmicrohttpd dependency, better option is build own libmicrohttpd without gnutls.
Thank you.

**Comment by LeChatNoir69** [comment]
You're right. Installed libmicrohttpd sources, compiled and everything is ok.
Thank you 👍
