### ISSUE TITLE
GTX480 issue to get running XMR mining CN-V8 XMRSTAK error

### ISSUE THREAD

**Issue by mindissue** [xmrig/xmrig-amd#244]
hey guys, tell me why i cant get detected my GTX480 (+ R9 270) second one is detected in such as XMRSTAK AiOminer or whatevr...

Nicehash legancy too, just R9 200 detectable, 
(..)

good2know that iam actually using a amd chipset motherboard, should also work with or??

**Comment by mindissue** [comment]
[url=https://www.xup.in/dl,15198155/errorXMRSTAKGTX480.png/][img]https://www1.xup.in/tn/2019_03/15198155.png[/img][/url]

**Comment by mindissue** [comment]
https://www1.xup.in/exec/ximg.php?fid=15198155
![errorXMRSTAKGTX480](https://user-images.githubusercontent.com/44915272/54397881-45c55d80-46b8-11e9-893a-584820feb6b1.png)

**Comment by bycarloz** [comment]
friend xmr-stak no longer supports cuda 8 must compile the miner for you to run the gtx 480 in xmrig must use the miner xmrig-nvidia cuda 8 and it will work for the problems of the dll you can get in the cup of cuda 8 can copy it from this path C:\ProgramFiles\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin files are nvrtc64_80.dll and nvrtc-builtins64_80.dll
