### ISSUE TITLE
Rigs stopping After 36 hours on CN/RWZ

### ISSUE THREAD

**Issue by MetallianFR68** [xmrig/xmrig-amd#245]
I'm mining graft with 4x6 VEGA56 since 2.14.0 update

Every 36 hours or so, some cards stop mining. First one card, then a second one some minutes later, until only one works alone.

Same problem on every Rig with different cards.

2.14.1 didn't fix the problème

Any Idea ?
Could this be a memory leak ?

**Comment by k0ste** [comment]
#241

**Comment by gjimenezf** [comment]
I have the same problem with 2.14.1

**Comment by xmrig** [comment]
https://github.com/xmrig/xmrig/releases/tag/v4.0.0-beta
