### ISSUE TITLE
xmrig-amd locks up pc as soon as it starts mining

### ISSUE THREAD

**Issue by rickbb** [xmrig/xmrig-amd#247]
Win 10 Enterprise, intel cpu, 16 gig ram, 5 x AMD HD7870 2 gig cards.
Tried several fresh config starts, miner goes through all the normal startup, then as soon as it gets to new block found it stops. No mouse clicks, no keyboard, walk away and leave it for an hour, nothing. Have to power cycle the PC to get control back.

**Comment by calvintam236** [comment]
I think maybe your computer froze? If so, usually due to memory error, overheating..

**Comment by rickbb** [comment]
Not the PC, only xmrig, everything else works. Not overheating, not a memory issue.

**Comment by xmrig** [comment]
https://github.com/xmrig/xmrig/releases/tag/v4.0.0-beta
