### ISSUE TITLE
Please add Conceal (CCX) correct support

### ISSUE THREAD

**Issue by Dr-Hard** [xmrig/xmrig-amd#248]
Please add Conceal (CCX) correct support for xmrig, xmrig-amd and xmrig-proxy.

**Comment by Dr-Hard** [comment]
Please add correct support cn (cn/r) "conceal" algo for CCX new fork to xmrig, xmrig-amd & xmrig proxy. Conceal dev group given you all info for it.

**Comment by Dr-Hard** [comment]
Please add correct and WORKING support cn (cn/r) "conceal" algo for CCX new fork to xmrig, xmrig-amd & xmrig proxy. Conceal dev group given you all info for it.

**Comment by xmrig** [comment]
https://github.com/xmrig/xmrig/releases/tag/v4.0.0-beta
