### ISSUE TITLE
Random X support

### ISSUE THREAD

**Issue by MetallianFR68** [xmrig/xmrig-amd#259]
Si Monero will fork to RandomX in July
LOKI announced fork to aRandomXL

Some weeks ago I read an article about AMD card beeing unable to mine that algorithm because of some missing function in OPEN CL

Today, I found some sort of implementation of a solution
https://github.com/SChernykh/RandomX_OpenCL

Are you going to work on that ?

We would miss a big opportunity if this is not ready when the fork arrives, letting CPU and NVIDIA card mine alone

**Comment by xmrig** [comment]
Monero will fork to RandomX in October and @SChernykh working on OpenCL implementation.
Thank you.

**Comment by Spudz76** [comment]
RandomX will only work on GPU with more than 2GB
It requires 2080MB minimum and then *on top of that* the scratchpads for whatever intensity/worksize combo (as you would calculate for CN-Lite with 1MB scratchpads).

So if you have less-than-3GB cards they will never work on RandomX anyway, so start looking somewhere else before the fork, for mining normal CN algos that don't have a minimum ram requirement (MoneroOcean pays Monero but lets you mine other algos...)

RandomX might as well be baby-dagger, it almost blows as much vram, and deprecates as many cards.

**Comment by xmrig** [comment]
https://github.com/xmrig/xmrig/releases/tag/v4.0.0-beta

Possible to use low memory GPUs by using dataset from system memory, autoconfig should enable it automatically.
Thank you.
