### ISSUE TITLE
xmrig process exiting after duplicate / no pools active

### ISSUE THREAD

**Issue by Amdpowered** [xmrig/xmrig-amd#26]
![34154665-4fc990a4-e484-11e7-90f0-6a86f9d598f2](https://user-images.githubusercontent.com/34679766/34156186-2a9a41ba-e48a-11e7-8b26-4eb5da05e8b5.png)

I used the default config.json with an additional pool. Not sure how to configure a failover pool but thought it should failover to the 2nd pool if this happened.

**Comment by huserbg** [comment]
This started happening to me as well - it exits while it shouldn't.
I compiled v2.4.4 from master, because I saw a commit saying "Fix wrong signal handle", but the issue is still happening.
Now I created a .cmd file to run it in a loop, but of course it will be much better to get this bug fixed.

**Comment by xmrig** [comment]
https://github.com/xmrig/xmrig/releases/tag/v4.0.0-beta
