### ISSUE TITLE
Windows console colors don't work

### ISSUE THREAD

**Issue by Spudz76** [xmrig/xmrig-amd#262]
They do work if you use `--config` mode and edit the current running config file to turn color back on...

...which led to patches ignoring any tty_init return values on Windows (which makes color work normally)...

PR #260 and #261

**Comment by Spudz76** [comment]
See Also: [xmrig-nvidia issue #196](https://github.com/xmrig/xmrig-nvidia/issues/196)

**Comment by xmrig** [comment]
https://github.com/xmrig/xmrig/releases/tag/v4.0.0-beta
