### ISSUE TITLE
Compiling xmrig-amd on Armv8, during make SSE2NEON.h throws erros

### ISSUE THREAD

**Issue by wll1rah** [xmrig/xmrig-amd#267]
I've been trying to compile xmrig-amd on a Rock Pi 4 as a test bed for being able to get OpenCL GPU mining to other platform.  Some of the chips that now support Open CL are the allwinner H6, RK3399/Pro, AML-S912, S922/X, A311D.  I've so far been able to get sgminer running and mining with opencl.  

The issue that I am having with xmrig-amd starts after 87%, The error is related to the SSE2NEON.h file and calls to stdinth.  The images below give more detail on what is happening  during the compilation and build process

<img width="461" alt="xmrig-amd cmake" src="https://user-images.githubusercontent.com/42458367/61597110-f12f7300-abc0-11e9-85ec-b3b150f33ad1.PNG">
<img width="683" alt="xmrig-amd make process" src="https://user-images.githubusercontent.com/42458367/61597111-f12f7300-abc0-11e9-8323-20b8ca659bd1.PNG">

**Comment by xmrig** [comment]
ARM not supported.
Thank you.

**Comment by wll1rah** [comment]
That's funny, you have build target option for arm in the CMakeLists.txt

**Comment by xmrig** [comment]
You can try add ARM support, by using this PR as example https://github.com/xmrig/xmrig-nvidia/pull/268

**Comment by grahamreeds** [comment]
Unfortunately there are several more hurdles to get over once this is done.

The change in algorithm meant that a couple of flags to determine direction had been added to most functions with the corresponding if/else clauses.

I started to work through them but without a test regime, a stable pool and a decent hotel wifi connection I gave up for another day.

**Comment by BenjaminWegener** [comment]
getting a little bit further:
![Screenshot_2019-08-04-22-03-38-381_com termux](https://user-images.githubusercontent.com/11700669/62428641-f2ee5000-b703-11e9-864a-7b178a2765aa.png)
https://github.com/BenjaminWegener/xmrig-termux-opencl

**Comment by xmrig** [comment]
https://github.com/xmrig/xmrig/releases/tag/v4.0.0-beta
