### ISSUE TITLE
Windows 64 XMRig/2.4.3-beta2 Not showing any H/s or Accepted blocks. Diff stays at 5000

### ISSUE THREAD

**Issue by Romeo1984** [xmrig/xmrig-amd#28]
Hi,
Looks like my Radeon 5800 Series is not working at all:

 * VERSIONS:     XMRig/2.4.3-beta2 libuv/1.14.1 OpenCL/2.0 MSVC/2017
 * CPU:          AMD A8-5500 APU with Radeon(tm) HD Graphics     x64 AES-NI
 * ALGO:         cryptonight, donate=10%
 * POOL #1:      monerohash.com:3333
 * COMMANDS:     hashrate, pause, resume
[2017-12-21 21:17:19] compiling code and initializing GPUs. This will take a while...
[2017-12-21 21:17:19] #0, GPU #0 AMD Radeon HD 5800 Series, intensity: 160 (8/256), cu: 20
[2017-12-21 21:17:26] use pool monerohash.com:3333 198.251.81.82
[2017-12-21 21:17:26] new job from monerohash.com:3333 diff 5000
[2017-12-21 21:18:23] speed 10s/60s/15m n/a n/a n/a H/s max: n/a H/s
[2017-12-21 21:19:23] speed 10s/60s/15m n/a n/a n/a H/s max: n/a H/s
[2017-12-21 21:20:15] new job from monerohash.com:3333 diff 5000
[2017-12-21 21:20:23] speed 10s/60s/15m n/a n/a n/a H/s max: n/a H/s
[2017-12-21 21:21:23] speed 10s/60s/15m n/a n/a n/a H/s max: n/a H/s
[2017-12-21 21:22:23] speed 10s/60s/15m n/a n/a n/a H/s max: n/a H/s
[2017-12-21 21:22:48] new job from monerohash.com:3333 diff 5000
[2017-12-21 21:23:23] speed 10s/60s/15m n/a n/a n/a H/s max: n/a H/s
[2017-12-21 21:24:23] speed 10s/60s/15m n/a n/a n/a H/s max: n/a H/s
[2017-12-21 21:25:23] speed 10s/60s/15m n/a n/a n/a H/s max: n/a H/s
[2017-12-21 21:26:23] speed 10s/60s/15m n/a n/a n/a H/s max: n/a H/s
[2017-12-21 21:26:36] new job from monerohash.com:3333 diff 5000
[2017-12-21 21:27:23] speed 10s/60s/15m n/a n/a n/a H/s max: n/a H/s
[2017-12-21 21:28:18] new job from monerohash.com:3333 diff 5000
[2017-12-21 21:28:23] speed 10s/60s/15m n/a n/a n/a H/s max: n/a H/s

Let me know what else you need to T-Shoot.

**Comment by jdschuitemaker** [comment]
I am seeing the same with a HD6850

**Comment by undrfined** [comment]
same with hd6670.

**Comment by mxfiberguy** [comment]
Same with a HD5570
![problem](https://user-images.githubusercontent.com/34863238/34359215-96ad1f12-ea1b-11e7-8fef-0e3e62e38b2a.jpg)

**Comment by lmeloni** [comment]
Same here, I'll be happy to provide additional details if needed
![immagine](https://user-images.githubusercontent.com/15343753/34455680-75305ba8-ed84-11e7-99af-943c93971881.png)

**Comment by munsuri** [comment]
Same here with similar card.
In my case, it is a hang on the clFinish calls. Unfortunately I'm no OpenCL expert so can't figure out much more at the moment.
Another way of observing the hang is by Ctrl+C the miner and it doesn't quit by itself (gotta kill the process)

**Comment by munsuri** [comment]
Hum, it is actually crashing the driver (recovered from C:\Windows\LiveKernelReports\WATCHDOG\)
```
Microsoft (R) Windows Debugger Version 10.0.14321.1024 AMD64
Copyright (c) Microsoft Corporation. All rights reserved.

Loading Dump File [C:\Windows\LiveKernelReports\WATCHDOG\WATCHDOG-20180105-1650.dmp]
Mini Kernel Dump File: Only registers and stack trace are available

Symbol search path is: srv*
Executable search path is: 
Windows 10 Kernel Version 15063 MP (4 procs) Free x64
Machine Name:
Kernel base = 0xfffff803`5aa94000 PsLoadedModuleList = 0xfffff803`5ade0660
Debug session time: Fri Jan  5 16:50:50.705 2018 (UTC + 1:00)
System Uptime: 1 days 6:37:17.658
Loading Kernel Symbols
...............................................................
................................................................
.............................................................
Loading User Symbols
Mini Kernel Dump does not contain unloaded driver list
*******************************************************************************
*                                                                             *
*                        Bugcheck Analysis                                    *
*                                                                             *
*******************************************************************************

Use !analyze -v to get detailed debugging information.

BugCheck 141, {ffffc700bcd204a0, fffff80359e3cc54, 0, 3024}

*** WARNING: Unable to verify timestamp for atikmpag.sys
*** ERROR: Module load completed but symbols could not be loaded for atikmpag.sys
Probably caused by : atikmpag.sys ( atikmpag+cc54 )

Followup:     MachineOwner
---------

3: kd> !analyze -v
*******************************************************************************
*                                                                             *
*                        Bugcheck Analysis                                    *
*                                                                             *
*******************************************************************************

VIDEO_ENGINE_TIMEOUT_DETECTED (141)
One of the the display engines failed to respond in timely fashion.
(This code can never be used for a real bugcheck.)
Arguments:
Arg1: ffffc700bcd204a0, Optional pointer to internal TDR recovery context (TDR_RECOVERY_CONTEXT).
Arg2: fffff80359e3cc54, The pointer into responsible device driver module (e.g owner tag).
Arg3: 0000000000000000, The secondary driver specific bucketing key.
Arg4: 0000000000003024, Optional internal context dependent data.

Debugging Details:
------------------


DUMP_CLASS: 1

DUMP_QUALIFIER: 400

BUILD_VERSION_STRING:  10.0.15063.786 (WinBuild.160101.0800)

DUMP_TYPE:  2

BUGCHECK_P1: ffffc700bcd204a0

BUGCHECK_P2: fffff80359e3cc54

BUGCHECK_P3: 0

BUGCHECK_P4: 3024

FAULTING_IP: 
atikmpag+cc54
fffff803`59e3cc54 ??              ???

DEFAULT_BUCKET_ID:  GRAPHICS_DRIVER_ENGINE_TIMEOUT

TAG_NOT_DEFINED_202b:  *** Unknown TAG in analysis list 202b


CPU_COUNT: 4

CPU_MHZ: c26

CPU_VENDOR:  GenuineIntel

CPU_FAMILY: 6

CPU_MODEL: 2a

CPU_STEPPING: 7

BUGCHECK_STR:  0x141

PROCESS_NAME:  System

CURRENT_IRQL:  0

ANALYSIS_SESSION_HOST:  

ANALYSIS_SESSION_TIME:  01-05-2018 16:59:00.0057

ANALYSIS_VERSION: 10.0.14321.1024 amd64fre

STACK_TEXT:  
ffffa980`92d183f0 fffff804`ab487447 : ffffc700`b8a03000 ffffc700`bcd204a0 ffffa980`92d18590 ffffc700`bce793b0 : watchdog!WdDbgReportRecreate+0x10c
ffffa980`92d18440 fffff804`ae15a0fd : 00000000`00000000 00000000`00000000 ffffc700`b8a05000 ffffc700`00000008 : dxgkrnl!TdrUpdateDbgReport+0xe7
ffffa980`92d18490 fffff804`ae1a1fa8 : ffffc700`b8a05000 00000000`00000000 00000000`00000001 ffffc700`b8a03001 : dxgmms1!VidSchiResetEngine+0x6b1
ffffa980`92d18790 fffff804`ae17483a : ffffa980`92d188d0 ffffc700`b8a05000 00000000`00000102 ffffc700`b8a03000 : dxgmms1!VidSchiResetEngines+0x98
ffffa980`92d187d0 fffff804`ae173ea9 : ffffc700`b8a05000 fffff804`ae14bf07 ffffc700`b8a05d60 ffffc700`b8a03000 : dxgmms1!VidSchWaitForCompletionEvent+0x48a
ffffa980`92d18890 fffff804`ae143c44 : ffffc700`ba5c9010 ffffc700`b8a03000 ffffc700`bb92c5f0 ffffc700`b8a03000 : dxgmms1!VidSchiWaitForCompletePreemption+0x7d
ffffa980`92d18980 fffff804`ae14c78d : ffffc700`ba5c9010 ffffc700`ba5c9010 ffffa980`92d18ac0 00000000`00000004 : dxgmms1!VidSchiCompletePreemption+0x28
ffffa980`92d189c0 fffff804`ae19064a : ffffc700`b8a03000 ffffc700`b8a03000 ffffc700`00000000 ffffc700`ba5c9010 : dxgmms1!VidSchiScheduleCommandToRun+0x78d
ffffa980`92d18b80 fffff804`ae19060b : ffffc700`b8a03000 00000000`00000080 fffff804`ae190570 00000000`00000000 : dxgmms1!VidSchiRun_PriorityTable+0x2a
ffffa980`92d18bd0 fffff803`5ab70eb7 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : dxgmms1!VidSchiWorkerThread+0x9b
ffffa980`92d18c10 fffff803`5ac05a06 : ffffa980`91e8c180 ffffc700`b7b9f7c0 fffff803`5ab70e70 00000000`00000246 : nt!PspSystemThreadStartup+0x47
ffffa980`92d18c60 00000000`00000000 : ffffa980`92d19000 ffffa980`92d13000 00000000`00000000 00000000`00000000 : nt!KiStartSystemThread+0x16


STACK_COMMAND:  kb

THREAD_SHA1_HASH_MOD_FUNC:  8d1bf39953a961ab132b9b91e981328d371ad90b

THREAD_SHA1_HASH_MOD_FUNC_OFFSET:  1680aa1461e1d62c4d637435edcc41017fdc1b1a

THREAD_SHA1_HASH_MOD:  31f3ba991666f8fec72437fcf2e89e524fd4bf33

FOLLOWUP_IP: 
atikmpag+cc54
fffff803`59e3cc54 ??              ???

SYMBOL_NAME:  atikmpag+cc54

FOLLOWUP_NAME:  MachineOwner

MODULE_NAME: atikmpag

IMAGE_NAME:  atikmpag.sys

DEBUG_FLR_IMAGE_TIMESTAMP:  563a75bb

FAILURE_BUCKET_ID:  LKD_0x141_IMAGE_atikmpag.sys

BUCKET_ID:  LKD_0x141_IMAGE_atikmpag.sys

PRIMARY_PROBLEM_CLASS:  LKD_0x141_IMAGE_atikmpag.sys

TARGET_TIME:  2018-01-05T15:50:50.000Z

OSBUILD:  15063

OSSERVICEPACK:  786

SERVICEPACK_NUMBER: 0

OS_REVISION: 0

SUITE_MASK:  272

PRODUCT_TYPE:  1

OSPLATFORM_TYPE:  x64

OSNAME:  Windows 10

OSEDITION:  Windows 10 WinNt TerminalServer SingleUserTS

OS_LOCALE:  

USER_LCID:  0

OSBUILD_TIMESTAMP:  2017-11-30 03:34:10

BUILDDATESTAMP_STR:  160101.0800

BUILDLAB_STR:  WinBuild

BUILDOSVER_STR:  10.0.15063.786

ANALYSIS_SESSION_ELAPSED_TIME: a71

ANALYSIS_SOURCE:  KM

FAILURE_ID_HASH_STRING:  km:lkd_0x141_image_atikmpag.sys

FAILURE_ID_HASH:  {c4561d61-ffbc-583d-5e1a-6fd6e42466ee}

Followup:     MachineOwner
---------
```

**Comment by lmeloni** [comment]
Mining with Cryptonight Lite gives me a hashrate, but I also get "COMPUTE ERROR". Summing up:
- Cryptonight -> No hashrate at all
- Cryptonight Lite -> Acceptable hashrate but always ends in COMPUTE ERROR

**Comment by maksimovichsam** [comment]
Same issue, using AMD Radeon HD 6450

**Comment by jdschuitemaker** [comment]
Make sure that you have a monitor connected to your cards.

Met vriendelijke groeten, Warm regards,

Jan-Dirk Schuitemaker

**Comment by Romeo1984** [comment]
Update From Original Poster:
FIXED - For what it's worth...  I had a system drive crash, so I had to reload Windows 10 from scratch (Originally upgraded from Windows 8), Installed the latest Radeon Drivers, and now it works.

Cheers.

**Comment by munsuri** [comment]
@Romeo1984 could you please share the exact link where you got the latest Radeon Drivers? Thanks

**Comment by Romeo1984** [comment]
Munsuri,
I actually used the self-identifying managed driver program here:

https://www2.ati.com/drivers/installer/17.50/beta/radeon-software-adrenalin-18.1.1-minimalsetup-180118_web.exe

It identifies your card and loads the best driver. 

Also, as a side note, I went from a DVI cabled monitor to an HDMI monitor. Not sure if that has anything to do with it. When I get a chance tonight, I will test the different configurations.

**Comment by Romeo1984** [comment]
So, I switched from HDMI to DVI and restarted the miner. IT did start successfully, but hte funny thing is I went from 109 H/S on HDMI to 65 H/S on DVI. No idea why...

**Comment by jdschuitemaker** [comment]
Which card is that? I get 223-225 on my Radeon HD 6850

Met vriendelijke groeten, Warm regards,

Jan-Dirk Schuitemaker

**Comment by mxfiberguy** [comment]
Well, as an old ex MyCom Netherlands employee I ensure myself that i have enough knowledge to know about connecting a monitor to a videocard.

I threw out the HD 5755 because it was bought back in 2011 and is just completely outdated. Also after trying to reinstall W10Home with fresh drivers etc would not work. So, i got 3 new GTX 1070 cards instead, which actually DO work.

**Comment by jdschuitemaker** [comment]
How many H/s do you get on each GTX 1070 card?

Met vriendelijke groeten, Warm regards,

Jan-Dirk Schuitemaker

**Comment by mxfiberguy** [comment]
Per card i reach a little over 700 H/s which is not bad considered the power limit is on 65% with no Core OC and MEM OC on +800Mhz, power consumage per card is a little under 100watts

**Comment by DoraemonYu** [comment]
The same as "DH 7000  series" card with v2.4.5, and my os is Win7 64bit.

**Comment by nassimosaz** [comment]
I have the same issue with my radeon 7500M/7600M Series..

**Comment by xmrig** [comment]
https://github.com/xmrig/xmrig/releases/tag/v4.0.0-beta
