### ISSUE TITLE
Error build on ApiState

### ISSUE THREAD

**Issue by kronoscrasher** [xmrig/xmrig-amd#29]
Having issue while building at following breakpoint 

Scanning dependencies of target xmrig-amd
[  2%] Building CXX object CMakeFiles/xmrig-amd.dir/src/api/Api.cpp.o
[  5%] Building CXX object CMakeFiles/xmrig-amd.dir/src/api/ApiState.cpp.o
/home/ethos/xmrig-amd/src/api/ApiState.cpp: In member function 'void ApiState::genId()':
/home/ethos/xmrig-amd/src/api/ApiState.cpp:146:53: error: no match for 'operator<' (operand types are 'uv_err_t {aka uv_err_s}' and 'int')
     if (uv_interface_addresses(&interfaces, &count) < 0) {
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~
/home/ethos/xmrig-amd/src/api/ApiState.cpp:153:58: error: 'uv_interface_address_t {aka struct uv_interface_address_s}' has no member named 'phys_addr'
             const size_t addrSize = sizeof(interfaces[i].phys_addr);
                                                          ^~~~~~~~~
/home/ethos/xmrig-amd/src/api/ApiState.cpp:157:41: error: 'uv_interface_address_t {aka struct uv_interface_address_s}' has no member named 'phys_addr'
             memcpy(input, interfaces[i].phys_addr, addrSize);
                                         ^~~~~~~~~
make[2]: *** [CMakeFiles/xmrig-amd.dir/src/api/ApiState.cpp.o] Error 1
make[1]: *** [CMakeFiles/xmrig-amd.dir/all] Error 2
make: *** [all] Error 2

**Comment by avujic** [comment]
Same error, same place...

[  4%] Building CXX object CMakeFiles/xmrig-amd.dir/src/api/ApiState.cpp.o
/opt/xmrig-amd/src/api/ApiState.cpp: In member function ‘void ApiState::genId()’:
/opt/xmrig-amd/src/api/ApiState.cpp:146:53: error: no match for ‘operator<’ (operand types are ‘uv_err_t {aka uv_err_s}’ and ‘int’)

**Comment by struktured** [comment]
@avujic @kronoscrasher this fixed it for me on kubuntu 17.04:

```sudo apt install libuv1-dev```

**Comment by avujic** [comment]
Works for me. Thank you.

**Comment by satchelfrench** [comment]
I get this same error:

`/home/xmrig/src/api/ApiState.cpp: In member function ‘void ApiState::genId()’:
/home/xmrig/src/api/ApiState.cpp:143:53: error: no match for ‘operator<’ (operand types are ‘uv_err_t {aka uv_err_s}’ and ‘int’)
     if (uv_interface_addresses(&interfaces, &count) < 0) {
                                                     ^
/home/xmrig/src/api/ApiState.cpp:150:58: error: ‘uv_interface_address_t {aka struct uv_interface_address_s}’ has no member named ‘phys_addr’
             const size_t addrSize = sizeof(interfaces[i].phys_addr);
                                                          ^
/home/xmrig/src/api/ApiState.cpp:154:41: error: ‘uv_interface_address_t {aka struct uv_interface_address_s}’ has no member named ‘phys_addr’
             memcpy(input, interfaces[i].phys_addr, addrSize);
                                         ^
make[2]: *** [CMakeFiles/xmrig.dir/src/api/ApiState.cpp.o] Error 1
make[1]: *** [CMakeFiles/xmrig.dir/all] Error 2
make: *** [all] Error 2
`

With CentOS 6.8, gcc 5.3
