### ISSUE TITLE
Color output missing when logging

### ISSUE THREAD

**Issue by namsur1234** [xmrig/xmrig-amd#30]
When parameter to log is present and defined in json config file, color output will not occur even if "colors" : true is present.
 VERSIONS:     XMRig/2.4.3-beta2 libuv/1.14.1 OpenCL/2.0 MSVC/2017

**Comment by DrStein99** [comment]
I believe this is also happening for "XMRIG" repository too.

**Comment by korishan** [comment]
Confirmed. Went all black/white when I turned on logging on mine as well.  :/

**Comment by sanitariu** [comment]
Confirmed

**Comment by xmrig** [comment]
Duplicate https://github.com/xmrig/xmrig/issues/103
