### ISSUE TITLE
"GPU COMPUTE ERROR" when mining cryptonight-lite with Radeon HD6870

### ISSUE THREAD

**Issue by Nasuno999** [xmrig/xmrig-amd#31]
I have two Radeon HD6870, (Win7 64). 
When the algorithm is set to "cryptonight-lite" (AEON mining), I get "GPU #1 COMPUTE ERROR" and "GPU #0 COMPUTE ERROR"
And it works fine with just "cryptonight" (XMR mining).
Tried several versions of drivers, but to no avail.

And when I use XMR Stak I'm getting similar errors for cryptonight-lite
Meaning it might be an OpenCL related issue, since you share that part of code, if I'm not mistaken

**Comment by semtex41** [comment]
This seems to be the same issue as https://github.com/xmrig/xmrig-amd/issues/13 and I completely agree with your assessment. It does seem to be related to the AMD HD series.

**Comment by cryptonius** [comment]
VLIW GPUs don't work well with this miner... it needs some fixes.

**Comment by mhowelljr** [comment]
I am experiencing the same COMPUTE ERROR issues with 6870's running xmrig-amd mining cryptonight-lite. However, the cards are working with xmr-stak 2.4.1 ("Day After Easter") with --nocpu --nonvidia. The only issue I'm having with xmr-stak is it doesn't seem to support variants of cryptonight-lite.

**Comment by maxstl** [comment]
Same with me,hd6870 hd6850 hd6770 etc,it seems nobody cares

**Comment by thedobe** [comment]
Welp, best of luck. Starting a white house gov petition. 😆

**Comment by thedobe** [comment]
@xmrig is this something which can be addressed or is it what it is?

**Comment by xmrig** [comment]
https://github.com/xmrig/xmrig/releases/tag/v4.0.0-beta
