### ISSUE TITLE
Forced Shutdown after start

### ISSUE THREAD

**Issue by erick-couto** [xmrig/xmrig-amd#33]
Windows 7 64 bits with RX 560 Sapphire 2gb and Radeon mining driver.
The software show board information and shutdows.

Image attached.

![whatsapp image 2018-01-05 at 21 38 19](https://user-images.githubusercontent.com/10121100/34634519-f3e7d926-f26b-11e7-8e68-daf95611b3cd.jpeg)

**Comment by xmrig** [comment]
https://github.com/xmrig/xmrig/releases/tag/v4.0.0-beta
