### ISSUE TITLE
Duplicate shares

### ISSUE THREAD

**Issue by kozfogel** [xmrig/xmrig-amd#34]
Hi,

sooner or later i get rejections caused of "Duplicate share" 

OS: Ubuntu 16.04
Driver: amdgpu-pro-17.40
GPU: Single 280X

VERSIONS:     XMRig/2.4.3-beta2 libuv/1.8.0 OpenCL/2.0 gcc/5.4.0

The problem does not occure in Windows.
The problem does not occure with the CPU miner

Sometimes its hours without happening, somtimes every 2min (get 5min ban - mining 2 min -> ban again)

**Comment by huserbg** [comment]
I also get duplicate shares.
In my case the OS is 32-bit Windows 7.
If this is not a bug and is normal to happen, maybe xmrig can keep the submitted results for the current block and check before submitting a new result if it's the same as one of the already submitted.

**Comment by kozfogel** [comment]
I have 5 Mining computers.
- 2 Windows with Ryzen
- 2 Linux with Ryzen
- 1 Linux with GPU

the CPU mineres never send a single duplicate share. The GPU  dont send duplicates if it runs in windows, and on linux it will only (but very often und reproducable) if i enable 2MB fragment size.

I can turn it off, but its a hit in the hashrate from 1250h/s -> 900h/s  (on windows i get 850)

I dont think the bug is in the miner, xmr-stak will also send duplicate shares with 2mb fragments - but a check that prevent that would be nice.

If someone would tell me where to check that i can build it my self (but im not familiar with c/c++)

**Comment by xmrig** [comment]
https://github.com/xmrig/xmrig/releases/tag/v4.0.0-beta
