### ISSUE TITLE
MacBook Pro 2016 No AMD device found

### ISSUE THREAD

**Issue by Tom-Shen** [xmrig/xmrig-amd#35]
Today I compiled the latest version of source code using cmake (run `cmake .` then `make`). When I run the executable, it tells me No AMD device found. Here is a log:

`bogon:~ tomshen$ xmrig-amd -o stratum+tcp://uspool.electroneum.com:3333 -u etnkJhfiquhGsk56httfGUg4uYRiTSwrCMSnob4EBWc8bfYXaquKmLJRhPoRGVnTDUDJRJfvPuP2HNFXhoNYFpUV5EYhutC5Rq -p x --opencl-platform 0
 * VERSIONS:     XMRig/2.4.3-beta2 libuv/1.15.0 OpenCL/1.2 clang/9.0.0
 * CPU:          Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz x64 AES-NI
 * ALGO:         cryptonight, donate=5%
 * POOL #1:      uspool.electroneum.com:3333
 * COMMANDS:     hashrate, pause, resume
[2018-01-07 18:12:10] compiling code and initializing GPUs. This will take a while...
[2018-01-07 18:12:10] No AMD device found.
[2018-01-07 18:12:10] Failed to start threads`

The AMD card in my Mac is `AMD Radeon Pro 455 2GB`. macOS 10.13.2

**Comment by NegativePotato** [comment]
Hi, 

I had a similar problem but not that one exactly this one. I had to change the config.json file from what is on the wiki github. Lines of interest are  "_opencl-devices_" and "_index_" (in threads).
```
{
    "algo": "cryptonight",
    "background": false,
    "colors": true,
    "donate-level": 1,
    "log-file": null,
    "print-time": 60,
    "retries": 5,
    "retry-pause": 5,
    "syslog": false,
    "opencl-platform": 0,
    "opencl-devices": 1,
    "threads": [
        {
            "index": 1,
            "intensity": 150,
            "worksize": 8,
            "affine_to_cpu": false
        }
    ],
    "pools": [
        {
            "url": "",
            "user": "",
            "pass": "x",
            "keepalive": true,
            "nicehash": false
        }
    ],
    "api": {
        "port": 0,
        "access-token": null,
        "worker-id": null
    }
}
```

2/ You may need to also download [this little tool ](https://github.com/steveschow/gfxCardStatus/releases) that allows you to switch from integrated (Intel HD graphics) to the discrete graphic card (AMD Radeon). I haven't had time to perform full tests on whether switching to discrete GPU using this tool is advantageous or not. 

Hope that helps.  

PS : Link to the tool in case it doesn't work : https://github.com/steveschow/gfxCardStatus/releases
