### ISSUE TITLE
How build for Ubuntu 16

### ISSUE THREAD

**Issue by LiStopaD45** [xmrig/xmrig-amd#38]
Hi! 
Thanks to the developer for a fine product!
 I wanted to establish RX 460, but didn't find the instruction how to build xmrig-amd for Ubuntu 16. The instruction exists? I click on the links in the section of Build, but they don't conduct anywhere. 
I ask for help.

**Comment by ghandmann** [comment]
Hi There, just noticed the same problem here. The project wiki (where the build instructions should be) seems to be disabled or something?

**Comment by LiStopaD45** [comment]
I hope for the reply of developer.

**Comment by wodgey** [comment]
I used the same build instructions, as for xmrig.
I needed to install the SDK from AMD and had to manually create a symlink. Was fairly simple and painless even for a beginner/noob

**Comment by LiStopaD45** [comment]
Thanks! I will know now. I am grateful to you for council!

**Comment by wodgey** [comment]
Just google the error message when it appears. 
I did this at 3am this morning so it is a little fuzzy

it was either this
cd $AMDAPPSDKROOT/lib/x86_64/sdk
sudo ln -sf sdk/libOpenCL.so.1 libOpenCL.so

or this
$ cd $AMDAPPSDKROOT/lib/x86_64
$ sudo ln -sf sdk/libOpenCL.so.1 libOpenCL.so

**Comment by LiStopaD45** [comment]
I thank you! Thanks a lot!!! Good luck!!!!

**Comment by xmrig** [comment]
https://github.com/xmrig/xmrig/releases/tag/v4.0.0-beta
