### ISSUE TITLE
Unable to build on OS X 10.13.2

### ISSUE THREAD

**Issue by rsadek** [xmrig/xmrig-amd#40]
Hello,
I'm eager to try out xmrig-amd! However, on Mac OS High Sierra (10.13.2) cmake fails to find OpenCL with the output below. Any fixes, workarounds or suggestions are welcome. 
Thanks!

>build (master)$ cmake ..
CMake Warning at cmake/OpenCL.cmake:51 (find_package):
  By not providing "FindOpenCL.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "OpenCL", but
  CMake did not find one.

  Could not find a package configuration file provided by "OpenCL" with any
  of the following names:

    OpenCLConfig.cmake
    opencl-config.cmake

  Add the installation prefix of "OpenCL" to CMAKE_PREFIX_PATH or set
  "OpenCL_DIR" to a directory containing one of the above files.  If "OpenCL"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  CMakeLists.txt:151 (include)

CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
OpenCL_LIBRARY
    linked by target "xmrig-amd" in directory /Users/Ramy/xmrig-amd

-- Configuring incomplete, errors occurred!

**Comment by ChromeHearts** [comment]
I am able to build 10.13.3
I think this is due to the OpenCL driver in older High Sierra

**Comment by xmrig** [comment]
https://github.com/xmrig/xmrig/releases/tag/v4.0.0-beta
