### ISSUE TITLE
CL memory error on larger rig

### ISSUE THREAD

**Issue by Jayd603** [xmrig/xmrig-amd#42]
3 x Vega 64

  "threads": [
        {
            "index": 0,
            "intensity": 1920,
            "worksize": 8,
            "affine_to_cpu": false
        },
        {
            "index": 0,
            "intensity": 1920,
            "worksize": 8,
            "affine_to_cpu": false
        }
    ],
above repeated for each with different intensities tried. allowing the program to auto select works but only ends up doing ~1300h/s per card.

all the threads appear to queue up fine but right when it goes to do work the CL memory errors flood the screen.  this is on windows with 8 GB RAM and 40GB virtual memory configured.

**Comment by MinerGuy1111** [comment]
I see people using 6 vega 64s with xmrig amd on the benchmark site, are there any special settings i'm not aware of?  Anyone have any info?

**Comment by noctrex** [comment]
Try to use only one card, and see the RAM usage of xmrig, maybe it's a RAM issue.
On my system I've seen about 2GB RAM used with one card.

**Comment by xmrig** [comment]
https://github.com/xmrig/xmrig/releases/tag/v4.0.0-beta
