### ISSUE TITLE
max usage

### ISSUE THREAD

**Issue by rik81h** [xmrig/xmrig-amd#43]
Hi,

Any way to limit gpu usage like on cpu version?

I run amd version on 2 pc's, one is completely usable the other is not whilst xmrig is running.

Thanks

**Comment by it-solutions-zehaczek** [comment]
I am also interested in low prio GPU mining to keep the system usable.

**Comment by spidero** [comment]
+1

**Comment by xmrig** [comment]
https://github.com/xmrig/xmrig/releases/tag/v4.0.0-beta
