### ISSUE TITLE
Compile for x86?

### ISSUE THREAD

**Issue by merkjinx** [xmrig/xmrig-amd#44]
i was wondering how to compile for x86 arch. i'm having issues getting visual studio to compile for x86 properly.

**Comment by metalurgus** [comment]
Were you able to find any build instructions at all?

**Comment by poteus** [comment]
Same here.  
I end up with this error:

/opt/AMDAPPSDK-3.0/lib/x86_64/libOpenCL.so: error adding symbols: File in wrong format
collect2: error: ld returned 1 exit status
CMakeFiles/xmrig-amd.dir/build.make:1085: recipe for target 'xmrig-amd' failed
make[2]: *** [xmrig-amd] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/xmrig-amd.dir/all' failed
make[1]: *** [CMakeFiles/xmrig-amd.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by xmrig** [comment]
https://github.com/xmrig/xmrig/releases/tag/v4.0.0-beta
