### ISSUE TITLE
Mining halting, even with multiple pools listed

### ISSUE THREAD

**Issue by korishan** [xmrig/xmrig-amd#48]
I only ever see it mining on Pool #1. I have several listed (as for me, I need to change locations for NiceHash as I get rejections from time to time)

>  * VERSIONS:     XM  Rig/2.4.3-beta2 libuv/1.14.1 OpenCL/2.0 MSVC/2017
>  * CPU:          AMD A6-6400K APU with Radeon(tm) HD Graphics    x64 AES-NI
>  * ALGO:         cryptonight, donate=1%
>  * POOL #1:      xmr-usa.dwarfpool.com:8005
>  * POOL #2:      cryptonight.br.nicehash.co:3333
>  * POOL #3:      cryptonight.br.nicehash.com:3355
>  * POOL #4:      cryptonight.br.nicehash.com:3355
>  * POOL #5:      cryptonight.br.nicehash.com:3355
>  * POOL #6:      cryptonight.br.nicehash.com:3355
>  * POOL #7:      cryptonight.br.nicehash.com:3355
>  * POOL #8:      cryptonight.br.nicehash.com:3355
>  * POOL #9:      cryptonight.br.nicehash.com:3355

```
        {

            "url": "xmr-usa.dwarfpool.com:8005",
            "user": "WALLET.Korishan2GPU",
            "pass": "x",
            "keepalive": true,
            "nicehash": false
        },
```

I stays on Pool #1, then every so often, I'll get "No work found" or something to that effect, and the miner closes and I'm left with "Press any key to continue...." which of course, closes the whole console out.
So, big question, why is it not cycling to the other pools when #1 doesn't have any work for my miner to do? I thought that was part of the reason for having multiple pools so the miner isn't left sitting idle.

TIA

**Comment by korishan** [comment]
> [2018-02-09 09:09:38] speed 10s/60s/15m 212.6 217.5 216.7 H/s max: 225.9 H/s
> [2018-02-09 09:09:53] speed 10s/60s/15m 219.4 217.2 216.7 H/s max: 225.9 H/s
> [2018-02-09 09:10:08] speed 10s/60s/15m 217.5 217.3 216.8 H/s max: 225.9 H/s
> [2018-02-09 09:10:14] new job from xmr-usa.dwarfpool.com:8005 diff 20000
> [2018-02-09 09:10:15] [xmr-usa.dwarfpool.com:8005] duplicate job received, reconnect
> [2018-02-09 09:10:15] no active pools, stop mining
> Press any key to continue . . .

So why didn't it automatically go over to the other pools? Isn't that the whole reason for multiple pools is to switch when nothing is active or one goes down?

```
    "pools": [
        {
            "url": "xmr-usa.dwarfpool.com:8005",
            "user": "WALLET.Korishan2GPU",
            "pass": "korishantalshin@gmail.com",
            "keepalive": true,
            "nicehash": false
        },
        {
            "url": "cryptonight.br.nicehash.co",
            "user": "WALLET.Korishan2GPU",
            "pass": "korishantalshin@gmail.com",
            "keepalive": true,
            "nicehash": false
        },
        {
            "url": "cryptonight.br.nicehash.com:3355\u0000\u0000hub.com:20580",
            "user": "WALLET.Korishan.2GPU",
            "pass": "x",
            "keepalive": true,
            "nicehash": false
        },
```

Actually, I just noticed there were 2 entries with extra text after the port number. I cleaned up the config file and will see if that cures the problem.

**Comment by xmrig** [comment]
I suspect miner is crashed when stop mining, probably it can be simulated by pause/resume commands.
Thank you.

**Comment by gurupras** [comment]
I'm also suffering from the same problem. How do we stop this?

If you can even point me to the parts of the code that you think may be responsible for this, I'll take a look at it and try to submit a PR

**Comment by alferz** [comment]
xmrig, I agree with your assumption, what I have seen is when a pool dies for whatever reason, the miner indeed does crash with a "no active pools, stop mining" message. It never fails over to any backup servers.

Is there anything that can be done to fix this? It sucks when you dont notice it crashed for several hours

**Comment by DrStein99** [comment]
Same problem here too.  What is the point of adding additional pools, if they are never used?  With xmr-stack, at least it will switch over, mine something else for # of seconds, then flip back.  XMRIG just sits there and takes a nap and does nothing.  

Have I setup .json file this incorrectly?  Is a programming flaw?

**Comment by xmrig** [comment]
https://github.com/xmrig/xmrig/releases/tag/v4.0.0-beta
