### ISSUE TITLE
Only runs with threads:null

### ISSUE THREAD

**Issue by Yuman** [xmrig/xmrig-amd#50]
v2.4.3-beta2
Starting with threads:null, it rewrites with good-looking thread:{} content and runs on RX 550. But restart fails. Each time before it restarts, I have to set threads:null

**Comment by xmrig** [comment]
Looks like duplicate #51

**Comment by sohosynergy** [comment]
I had the same problem until I updated from that beta to version 2.4.5 for AMD.  I also have the RX 550.
