### ISSUE TITLE
How to build a Ubuntu version...

### ISSUE THREAD

**Issue by kimats** [xmrig/xmrig-amd#53]
Hello,
How to build a ubuntu xmrig-amd...?
For xmrig and xmrig-nvidia,,, I see a wiki there...

**Comment by gUY-** [comment]
Hi
xmrig-amd can be build on Ubuntu like xmrig : 

https://github.com/xmrig/xmrig/wiki/Ubuntu-Build

**Comment by xmrig** [comment]
https://github.com/xmrig/xmrig/releases/tag/v4.0.0-beta
