### ISSUE TITLE
Trojan:Win32/Coinminer!bit detected from windows defender

### ISSUE THREAD

**Issue by sabbir360** [xmrig/xmrig-amd#54]
While I extracted in windows 10. It was detected as Trojan named ***Trojan:Win32/Coinminer!bit***

**Comment by theAltaran** [comment]
That's normal.  Just make a exception in your anti-virus.   It is not a virus.

**Comment by xmrig** [comment]
You can add the miner to exclusion list. Actually can't do anything with detection. Please read https://github.com/xmrig/xmrig/issues/270#issuecomment-352305211
Thank you.
