### ISSUE TITLE
extracting into windows

### ISSUE THREAD

**Issue by d0n-miner1** [xmrig/xmrig-amd#55]
why does whenever i extract, the miner goes missing?
how am i supposed to extract these?

using vs code?
mingw?

initially before extracting, there were 3 files in there.
as soon as u extract, only the .json and start.bat

what about the miner?

**Comment by xmrig** [comment]
Miner was deleted by your antivirus. You can add the miner to exclusion list. Actually can't do anything with detection. Please read https://github.com/xmrig/xmrig/issues/270#issuecomment-352305211
Thank you.
