### ISSUE TITLE
What can we do to tune the config file?

### ISSUE THREAD

**Issue by kimats** [xmrig/xmrig-amd#56]
Hi, 

my config file like blow:

"threads": [
        {
            "index": 0,
            "intensity": 1200,
            "worksize": 8,
            "affine_to_cpu": false
        }
    ],

and I run the script and it shows:

#0, GPU #0 AMD Radeon (TM) R9 380 Series, intensity: 1200 (8/256), cu: 28

How can I know if it is the best config? what does below parameters mean?

intensity,
worksize,
cu,

Please help... Thank you....

**Comment by aedelgod** [comment]
I have the same question for an RX460

**Comment by yyfong0918** [comment]
cu = compute unit, your R9-380 (?) card got 28 compute units.

Just for your reference, I monitor the GPU memory usage when tuning (increasing) the intensity, just below the max size.

**Comment by kimats** [comment]
Thanks man for the reply!!!
Thanks.
I will try to tune them.

2018-03-16 0:08 GMT+08:00 yyfong0918 <notifications@github.com>:

**Comment by Titus1969** [comment]
Same but with an R7 200 series

**Comment by leve1ord** [comment]
R9 270, xmrig 2.6.0-beta 1 x64 
#0, GPU #0 AMD Radeon (TM) R9 200 Series, intensity: 800 (8/256), cu: 20 (auto settings)
460 h/s
Same gpu, Claymore CryptoNote AMD GPU Miner v11.3, -h 448 (auto settings)
560 h/s
Why the difference is soooo big?

**Comment by TheDarknessz0rz** [comment]
#0, GPU #0 (AMD Radeon (TM) R9 380 Series), intensity: 890 (8/256), cu: 28
speed 10s/60s/15m 1040.1 1040.2 n/a H/s max: 1040.3 H/s


I'm currently in the process of trying to reach at least 1.1kH/s with an R9 380 4GB edition, no overclocks or underclocks. I have installed the AMD blockchain drivers for this card on Ubuntu 16.04 LTS.

**Comment by wheatdogg** [comment]
I tried the AMD blockchain drivers on Ubuntu 16.04.4 and on reboot I get stuck in a login loop. I followed the directions AMD provides. Any advice, TheDarkness0rz?

**Comment by xmrig** [comment]
https://github.com/xmrig/xmrig/releases/tag/v4.0.0-beta
