### ISSUE TITLE
How to reduce GPU utilization

### ISSUE THREAD

**Issue by anhvu100** [xmrig/xmrig-amd#57]
Please help to show me the options to reduce GPU / resource utilization so that the computer runs faster/less frozen while the miner is running

**Comment by noctrex** [comment]
For starters, backup your config file, and then try lowering the intensity and/or the worksize.

**Comment by bokorben** [comment]
Same problem here, machine is unusable with GPUminer running, intensity does not matter a lot. lag reduces, but still more than acceptable.

**Comment by xmrig** [comment]
https://github.com/xmrig/xmrig/releases/tag/v4.0.0-beta
