### ISSUE TITLE
Questions of XMRIG-AMD on Ubuntu Server

### ISSUE THREAD

**Issue by kimats** [xmrig/xmrig-amd#59]
Hello 
After hours of google,,,,finally i get the xmrig-amd running on ubuntu:

 * VERSIONS:     XMRig/2.4.5 libuv/1.8.0 OpenCL/2.0 gcc/5.4.0
 * CPU:                Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz x64 AES-NI
 * ALGO:         cryptonight, donate=1%
 * POOL #1:      dero.cryptopool.space:3333
 * COMMANDS:     hashrate, pause, resume
[2018-03-07 00:18:32] compiling code and initializing GPUs. This will take a while...
[2018-03-07 00:18:32] #0, GPU #0 AMD Radeon HD 7700 Series, intensity: 450 (8/256), cu: 4
[2018-03-07 00:19:36] speed 10s/60s/15m n/a n/a n/a H/s max: n/a H/s

**I have some questions, not sure if anyone can help give me answer...**

**1. CL_OUT_OF_HOST_MEMORY problem,**
I use below command to solve them:
export GPU_FORCE_64BIT_PTR=1
export GPU_USE_SYNC_OBJECTS=1
export GPU_MAX_ALLOC_PERCENT=100
export GPU_SINGLE_ALLOC_PERCENT=100
export GPU_MAX_HEAP_SIZE=100

What does export command actually do? can anyone help explain a little bit more?

**2. what does " intensity: 500 (8/256), cu: 4" mean?**
I can only adjust "500" and "8" to tune the card .... and I actually have no idea on what they stand for.......

**Comment by xmrig** [comment]
https://github.com/xmrig/xmrig/releases/tag/v4.0.0-beta
