### ISSUE TITLE
Problems with HD6990 4 gb

### ISSUE THREAD

**Issue by guile124** [xmrig/xmrig-amd#60]
When i start the miner i get this message for the hd6990 gpu:

Error CL_INVALID_BUFFER_SIZE when calling clCreateBuffer to create hash scratchpads buffer.

Default config.
Any advice?

**Comment by kimats** [comment]
you need export something first at your login bash/csh:

export GPU_FORCE_64BIT_PTR=1
export GPU_USE_SYNC_OBJECTS=1
export GPU_MAX_ALLOC_PERCENT=100
export GPU_SINGLE_ALLOC_PERCENT=100
export GPU_MAX_HEAP_SIZE=100

**Comment by guile124** [comment]
Thx Kimats, but i'm using win64 version, can you to explain me how can i do it?

**Comment by kimats** [comment]
I can't remember the relative command at Windows, but I believe you can find it on Google.

**Comment by guile124** [comment]
Edited start.cmd with:

@echo off

SET GPU_FORCE_64BIT_PTR=1
SET GPU_USE_SYNC_OBJECTS=1
SET GPU_MAX_ALLOC_PERCENT=100
SET GPU_SINGLE_ALLOC_PERCENT=100 SET GPU_MAX_HEAP_SIZE=100

Xmrig-amd.exe
pause


Anyone can to confirm me if it is the correct config for win64?

**Comment by benosimo** [comment]
In windows 64bit it should look like:

setx GPU_FORCE_64BIT_PTR 1
setx GPU_MAX_HEAP_SIZE 100
setx GPU_USE_SYNC_OBJECTS 1
setx GPU_MAX_ALLOC_PERCENT 100
setx GPU_SINGLE_ALLOC_PERCENT 100

xmrig-amd.exe
pause

**Comment by guile124** [comment]
This problem is solved installing catalyst 14.4 drivers.
