### ISSUE TITLE
Segmentation fault while typing "h" to get hashrate

### ISSUE THREAD

**Issue by tiix95** [xmrig/xmrig-amd#61]
Hello,

I just compiled xmrig-amd and started mining with 3 AMD RX560 and 1 RX470 on ubuntu 16.04.

All is going well, except when I type "h" to get hashrate. As soon as I type the command, I get : 
`zsh: segmentation fault (core dumped)  ./xmrig-amd --print-time 30 -S -l /var/log/xmrig-amd.log --donate-level 1   -`
Here is the command used : 
`./xmrig-amd --print-time 30 -S -l xmrig-amd.log --donate-level 3 --api-port 8080 -o pool.etn.spacepools.org:1337 -u <public_address> -p x -k`

Did you ever encounter this issue ?

Thank you !

**Comment by xmrig** [comment]
Probable fixed in upcoming v2.5, when implement new Monero PoW I found memory corruption, it can cause segmentation fault in random places like this.
Thank you.

**Comment by tiix95** [comment]
Thank you for answer ! Will stay aware for new version.

**Comment by Cole128** [comment]
I am getting this when starting xmrig-amd for the first time, and I am running the newest version, from git even.

**Comment by xmrig** [comment]
https://github.com/xmrig/xmrig/releases/tag/v4.0.0-beta
