### ISSUE TITLE
OpenCL.dll

### ISSUE THREAD

**Issue by tarris034** [xmrig/xmrig-amd#62]
Could you upload and share link for required OpenCL.dll file ? and does it need to be the same version as installed video drivers or it may be just the latest/any version that is required by miner ?

**Comment by xmrig** [comment]
Proper OpenCL.dll installed with display driver.

But I just copy dll from machine where only Intel OpenCL available to AMD machine and it works.
Also AMD OpenCL.dll (also signed by AMD) works with Intel, looks like this dll is just tiny wrapper to actual implementation, need proper check for it.
Thank you.

**Comment by developernew123** [comment]
I want 32 bit of it , I downloaded one from internet and it worked for 64 bit but not 32

**Comment by tarris034** [comment]
@developernew123:

Hope you downloaded it in a pack from Microsoft, if not - it was 100% infected.

**Comment by xmrig** [comment]
https://github.com/xmrig/xmrig/releases/tag/v4.0.0-beta
