### ISSUE TITLE
does it require amd sdk

### ISSUE THREAD

**Issue by developernew123** [xmrig/xmrig-amd#64]
does amd version require amd app sdk to be installed ?

**Comment by xmrig** [comment]
AMD SDK required to build miner from source, but not for run.
Thank you.

**Comment by tarris034** [comment]
how about this:

https://github.com/xmrig/xmrig-amd/issues/62

**Comment by xmrig** [comment]
https://github.com/xmrig/xmrig/releases/tag/v4.0.0-beta
