### ISSUE TITLE
Build instructions link broken.

### ISSUE THREAD

**Issue by Proteles** [xmrig/xmrig-amd#65]
"https://github.com/xmrig/xmrig-amd/wiki/Build" does not exist, redirects back to "https://github.com/xmrig/xmrig-amd"

**Comment by xmrig** [comment]
Wiki somehow gone long time ago, I lazy to write again. Build instructions almost same with CPU miner https://github.com/xmrig/xmrig/wiki/Build only one difference, you need install AMD SDK.
Thank you.

**Comment by developernew123** [comment]
And is there any parameter to locate the path of amd sdk

**Comment by xmrig** [comment]
https://github.com/xmrig/xmrig/releases/tag/v4.0.0-beta
