### ISSUE TITLE
Tap xmrig-amd on hombrew

### ISSUE THREAD

**Issue by Unnameless** [xmrig/xmrig-amd#66]
Hi,

While xmrig (CPU) is tapped into homebrew, for us Mac users it would be great if it would be possible to tap xmrig-amd through brew the same as with xmrig. Large scale maintenance would be so much easier via brew.

Ty

**Comment by xmrig** [comment]
Yep it will be nice, but I didn't add xmrig to Homebrew, someone did it, many thanks to this guy.
