### ISSUE TITLE
bluescreen death with Ryzen3 2200G APU (v.2.5.2)

### ISSUE THREAD

**Issue by GiulioPipitone** [xmrig/xmrig-amd#71]
Hi,
I start succesfully the miner and I can see the Vega CPU (8 cu) initialized but few seconds after the system crashes with blue screen of death.
Windows 10 Pro, version 2.5.2. Here is my config.json (initial part):
"algo": "cryptonight",
    "background": false,
    "colors": true,
    "donate-level": 1,
    "log-file": null,
    "print-time": 5,
    "retries": 5,
    "retry-pause": 5,
    "opencl-platform": 0,
    "threads": [
        {
            "index": 0,
            "intensity": 960,
            "worksize": 8,
            "affine_to_cpu": false
        }
    ],
...

Is there something I have to tweak?
Thank you

**Comment by leve1ord** [comment]
Intensity should be around 128-180 . I get up 169 h/s on vega 8. Not worth it.

**Comment by xmrig** [comment]
That right, for recent versions also should set `"strided_index": 0,`, anyway I will exclude Vega APU from autoconfig in next version (2.7.3).
