### ISSUE TITLE
Segfault when starting xmrig-amd

### ISSUE THREAD

**Issue by makeworld-the-better-one** [xmrig/xmrig-amd#74]
After finally finding the right drivers for my GPU, I kept encountering a segfault when running xmrig-amd.
Here is the message from dmesg:
```
segfault at 0 ip 00007f17d1f53cc7 sp 00007fff19188ca0 error 4 in libamdocl64.so[7f17d134b000+3b33000]
```
Here is the message from xmrig:
```[1]    <PIDnumber> segmentation fault (core dumped)  xmrig-amd -c .xmrig-amd-config```

I am running Antergos (basically Arch Linux at heart). Any ideas?

EDIT: so it seems this is probably a driver or OpenCL issue, although any help would still be appreciated.

**Comment by cdarken** [comment]
Same for me, only crashes on xmrig-amd and xmr-stak, using kernel 4.16.12 and opencl-amd 18.20

**Comment by xmrig** [comment]
https://github.com/xmrig/xmrig/releases/tag/v4.0.0-beta
