### ISSUE TITLE
Not all video cards have hash rate (Monero v7 POW)

### ISSUE THREAD

**Issue by jessedye** [xmrig/xmrig-amd#75]
I'm currently using v2.6.0-beta1 for Monero v7 POW. However, I am currently unable to get hash rates from my other cards (they were working before the update). I am currently using Radeon 6950 / 6970 2GB cards. Most of my configurations use around 6 cards per miner. However, it seems like a few of my cards are not getting any hash rates at all.  All my miners are using Catalyst 14.4 because no other version of Catalyst allow XMRig to see the full 2GB of memory per card. Is there anyone that could look into this as this is now the only mining software I can use for the new Monero fork? I appreciate all the efforts you guys make in supporting miners such as myself with older hardware!

<img width="891" alt="screenshot" src="https://user-images.githubusercontent.com/17808103/38473967-06ebdee4-3b66-11e8-8792-d19939d79e4e.PNG">

**Comment by guile124** [comment]
@jessedye  You had the same problem with previous xmrig versions?
I have the same problem with the old xmrig with my HD6990, you can see my opened issue #76. 
maybe @xmrig can help us with the config

**Comment by guile124** [comment]
@ademturk it´s working fine in claymore and xmr-stak? or same problems?

**Comment by jessedye** [comment]
@guile124 I have not had problems with previous versions. This is using v2.6.0-beta1 for the XMR hard fork.

**Comment by jessedye** [comment]
@guile124 
config.json
```
{
    "algo": "cryptonight",
    "background": false,
    "colors": true,
    "donate-level": 1,
    "log-file": null,
    "print-time": 60,
    "retries": 5,
    "retry-pause": 5,
    "opencl-platform": 0,
    "threads": [
        {
            "index": 0,
            "intensity": 704,
            "worksize": 8,
            "affine_to_cpu": false
        },
        {
            "index": 1,
            "intensity": 704,
            "worksize": 8,
            "affine_to_cpu": false
        },
        {
            "index": 2,
            "intensity": 704,
            "worksize": 8,
            "affine_to_cpu": false
        },
        {
            "index": 3,
            "intensity": 704,
            "worksize": 8,
            "affine_to_cpu": false
        },
        {
            "index": 4,
            "intensity": 704,
            "worksize": 8,
            "affine_to_cpu": false
        },
        {
            "index": 5,
            "intensity": 704,
            "worksize": 8,
            "affine_to_cpu": false
        }
    ],
    "pools": [
        {
            "url": "xxxxxxxxxxx",
            "user": "xxxxxxxxxx",
            "pass": "xxxxxxxxx",
            "keepalive": true,
            "nicehash": false,
            "variant": -1
        }
    ],
    "api": {
        "port": 0,
        "access-token": null,
        "worker-id": null
    }
}
```
start.cmd

```
@echo off
setx GPU_FORCE_64BIT_PTR 1
setx GPU_MAX_HEAP_SIZE 100
setx GPU_USE_SYNC_OBJECTS 1
setx GPU_MAX_ALLOC_PERCENT 100
setx GPU_SINGLE_ALLOC_PERCENT 100
C:
cd C:\miner
xmrig-amd.exe
pause
```

**Comment by guile124** [comment]
@jessedye I have the same config, and same problem also... i think that maybe is a temperature limit problem... or the overcharge of a gpu because is used for some Windows task... it would be interesant to put lower intensity in one or two gpu´s and study it... but cannot to fix the compute units working in xmrig really? temperature limit neither?

Maybe sir @xmrig can help us when he will fix all new forks...

**Comment by Boss13014** [comment]
@jessedye I've got same problem with 2 card 6950, i only use one card by computer, not a rig ...

I've you try an answer ? I've tested lot of miner, claymore, xmr stak .... the only one hash a littre is "SRB Miner" but i've got a low hash, 145h/s, i've got 350 with claymore 9.7 before the fork.

I hope we find a solution with our old Radeon.

Thx.

**Comment by Boss13014** [comment]
i've tweaked intensity with 14.4 Drivers whql i get 207 h/s with 25 intensity on SRB Miner.
xm rig amd crashed with 6950 Did you hash with this card with this miner ?! @jessedye

**Comment by ademturk** [comment]
thanks

**Comment by carlospea** [comment]
Hi, I was reviewing between different intensities, @guile124 we have several identical cards, the xmrig program does not work well when the intensity for the main card where we have connected the video cable can not be greater than 66% of the load, I suppose it should be some limitation of the xmrig.

**Comment by Tohelo101** [comment]
![image](https://user-images.githubusercontent.com/38385662/40046476-bb3a22ac-5835-11e8-869e-3ad78edfa398.png)
Hello im trying change intensity to 704 but i get all times that error CL_invalid buffer size ? any fix for that?

**Comment by Tohelo101** [comment]
@carlospea Okey i test it and best what i did get is this
"threads": [
        {
            "index": 0,
            "intensity": 352,
            "worksize": 8,
            "affine_to_cpu": false
        },
        {
            "index": 1,
            "intensity": 352,
            "worksize": 8,
            "affine_to_cpu": false
        },
        {
            "index": 2,
            "intensity": 383,
            "worksize": 8,
            "affine_to_cpu": false
        },
        {
            "index": 3,
            "intensity": 352,
            "worksize": 8,
            "affine_to_cpu": false
        },
        {
            "index": 4,
            "intensity": 383,
            "worksize": 8,
            "affine_to_cpu": false
        },
        {
            "index": 5,
            "intensity": 383,
            "worksize": 8,
            "affine_to_cpu": false
        },
        {
            "index": 6,
            "intensity": 352,
            "worksize": 8,
            "affine_to_cpu": false
        },
        {
            "index": 7,
            "intensity": 383,
            "worksize": 8,
            "affine_to_cpu": false
        }
    ],
![image](https://user-images.githubusercontent.com/38385662/40144545-b06de7f4-5967-11e8-90f2-8b93dcca7175.png)
Will that worksize help ?? if i increase that

**Comment by carlospea** [comment]
@Tohelo101, I have tried to change worksize and follow the same hash, go increasing the intensity as I said 10 in 10, then when you get to the error low 10 and you increase by 1 in 1 (do it on a single card and when you get a peak good you put it to the others).

Also try duplicating the thread information:
{
"index": 0,
"intensity": 352,
"worksize": 8,
"affine_to_cpu": false
},
{
"index": 0,
"intensity": 352,
"worksize": 8,
"affine_to_cpu": false
},
{
"index": 1,
"intensity": 383,
"worksize": 8,
"affine_to_cpu": false
}, .....

With that I could solve when the first card that is the one used for the video processing of the so, does not let you use the maximum of the card. You just have to find the maximum value and divide it in half, my hd7850 2gb and hd7950 3gb place them like this and give me maximum values ​​without oc (350 and 420 respectively)

{
"index": 0,
"intensity": 368, // (I do not remember exactly right now)
"worksize": 8,
"affine_to_cpu": false
},
{
"index": 0,
"intensity": 368,
"worksize": 8,
"affine_to_cpu": false
},
{
"index": 1,
"intensity": 448,
"worksize": 8,
"affine_to_cpu": false
},
{
"index": 1,
"intensity": 448,
"worksize": 8,
"affine_to_cpu": false
},

**Comment by xmrig** [comment]
https://github.com/xmrig/xmrig/releases/tag/v4.0.0-beta
