### ISSUE TITLE
Same config for all gpu´s but gpu 0 n/a  

### ISSUE THREAD

**Issue by guile124** [xmrig/xmrig-amd#76]
I cannot to understand this fail, the hardware is ok i have changed the gpu´s and gpu 0 shows ever n/a in hashrate report,, tried to put low intensity in gpu0 but the fail continue.
Anyone can help me with it? Thx guys
@xmrig 

OS Win10 64 bits

![20180409_234851](https://user-images.githubusercontent.com/37140613/38525137-75c6340e-3c51-11e8-8d26-62c4a562bcf6.jpg)

{
    "algo": "cryptonight",
    "background": false,
    "colors": true,
    "donate-level": 1,
    "log-file": null,
    "print-time": 60,
    "retries": 5,
    "retry-pause": 5,
    "opencl-platform": 0,
    "threads": [
        {
            "index": 0,
            "intensity": 768,
            "worksize": 8,
            "affine_to_cpu": false
        },
        {
            "index": 1,
            "intensity": 768,
            "worksize": 8,
            "affine_to_cpu": false
        },
        {
            "index": 2,
            "intensity": 768,
            "worksize": 8,
            "affine_to_cpu": false
        },
        {
            "index": 3,
            "intensity": 768,
            "worksize": 8,
            "affine_to_cpu": false
        }
    ],
    "pools": [
        {
            "url": "msr.soyminero.es:4447",
            "user": "5npfRtprLDxVGimvEqqvYSEWLMJCVtsdVgEaWwJYD2tTexnMoR2vu4vU7z8SpspXLPq6y29FBjEEevk3K25VPhNAVLeBw",
            "pass": "x",
            "keepalive": true,
            "nicehash": false
        }
    ],
    "api": {
        "port": 0,
        "access-token": null,
        "worker-id": null
    }
}

@echo off
setx GPU_FORCE_64BIT_PTR=1
setx GPU_USE_SYNC_OBJECTS=1
setx GPU_MAX_ALLOC_PERCENT=100
setx GPU_SINGLE_ALLOC_PERCENT=100
setx GPU_MAX_HEAP_SIZE=100
xmrig-amd.exe
pause

**Comment by carlospea** [comment]
Hi, I have the same problem, as I have win 10 64bit catalyst 14.4. My cards before with claymore 9.7 to each 210h / s, with xmrig I could make one arrive at 200h / s but the other one that is identical does not hold the configuration, it appears the same as the partner. Only one card works with the configuration, the other does not. What I found is that changing the configuration of the card that does not start at values ​​much below, makes it work but very slow, now I have one in 200h / s and the other in 110h / s. How can it be resolved so that they all work?

**Comment by carlospea** [comment]
Hi, I was reviewing between different intensities, @guile124 we have several identical cards, the xmrig program does not work well when the intensity for the main card where we have connected the video cable can not be greater than 66% of the load, I suppose it should be some limitation of the xmrig.

**Comment by xmrig** [comment]
https://github.com/xmrig/xmrig/releases/tag/v4.0.0-beta
