### ISSUE TITLE
Support cryptonight-heavy ?

### ISSUE THREAD

**Issue by saphiretr** [xmrig/xmrig-amd#77]
This miner support cryptonight-heavy algo ?

**Comment by sitchi** [comment]
yes,  https://github.com/xmrig/xmrig-amd/releases

**Comment by saphiretr** [comment]
i got "Low Difficulty Share" with that link.
What do we have to write on the config file at "algo": "cryptonight", line ? cryptonight-heavy or what ?

**Comment by sitchi** [comment]
"algo": "cryptonight-heavy"

**Comment by saphiretr** [comment]
donate: 5% ? oh no thank you !

**Comment by sitchi** [comment]
donate can be changed to 1%, edit config file to "donate-level": 1,

**Comment by chienasic** [comment]
{
    "algo": "cryptonight-heavy",
    "background": false,
    "colors": true,
    "donate-level": 1,
    "log-file": null,
    "print-time": 60,
    "retries": 5,
    "retry-pause": 5,
    "opencl-platform": 1,
    "threads": [
        {
            "index": 0,
            "intensity": 768,
            "worksize": 8,
            "affine_to_cpu": false
        },
        {
            "index": 1,
            "intensity": 768,
            "worksize": 8,
            "affine_to_cpu": false
        },
        {
            "index": 2,
            "intensity": 768,
            "worksize": 8,
            "affine_to_cpu": false
        },
        {
            "index": 3,
            "intensity": 768,
            "worksize": 8,
            "affine_to_cpu": false
        },
        {
            "index": 4,
            "intensity": 768,
            "worksize": 8,
            "affine_to_cpu": false
        },
        {
            "index": 5,
            "intensity": 768,
            "worksize": 8,
            "affine_to_cpu": false
        }
    ],
    "pools": [
        {
            "url": "mine.loki.fairpool.xyz:5577",
            "user": "LK8CGQ17G9R3ys3Xf33wCeViD2B95jgdpjAhcRsjuheJ784dumXn7g3RPAzedWpFq364jJKYL9dkQ8mY66sZG9BiCzCWw5q9LuxLPW3oGZ+cr2",
            "pass": "x",
            "keepalive": true,
            "nicehash": false,
            "variant": -1
        }
    ],
    "api": {
        "port": 0,
        "access-token": null,
        "worker-id": null
    }
}
not work

**Comment by xmrig** [comment]
https://github.com/xmrig/xmrig/releases/tag/v4.0.0-beta
