### ISSUE TITLE
Version 2.6.0 Trojan - windows defender 

### ISSUE THREAD

**Issue by francescocmazza** [xmrig/xmrig-amd#78]
Hi, 
I downloaded 2.6.0 Beta 1 and Windows defender claims that the file is infected with Win32/Skeeyah.A!rfn Trojan.
2.5.2 Version instead appears to be infected with Win32/Tiggre!plock trojan. What's happening?
Thank you

**Comment by merkjinx** [comment]
false positive, compile yourself to fix.

**Comment by bokorben** [comment]
All miner executables are detected as trojans by the antivirus softwares.

**Comment by xmrig** [comment]
https://github.com/xmrig/xmrig/releases/tag/v4.0.0-beta
