### ISSUE TITLE
Any chance of more than 1 thread?

### ISSUE THREAD

**Issue by cpny** [xmrig/xmrig-amd#8]
Right now with vega it suggests an intensity of around 1500 and the max i can seem to set it is around 2000 but that doesn't come close to maxing vega.

On xmr-stak-amd i can use two threads with 1920 intensity each giving my vega 56 around 2020 h/s, any way to do it like that on xmrig right now?

I get 1550 h/s with xmrig and 2000 intensity.

Thank you

**Comment by xmrig** [comment]
Same syntax with xmr-stak-amd, something like:
```json
    "threads": [
        {
            "index": 0,
            "intensity": 1920,
            "worksize": 8,
            "affine_to_cpu": false
        },
        {
            "index": 0,
            "intensity": 1920,
            "worksize": 8,
            "affine_to_cpu": false
        }
    ],
```

or if you prefer command line options instead of config:

```
--opencl-platform=0 --opencl-devices=0,0 --opencl-launch=1920x8,1920x8
```

**Comment by cpny** [comment]
Oh thank you very much, gonna try that!

**Comment by Kanelus** [comment]
Hi, its not working for me, i edit the config.json but after changes it does not even start. Tried with commas and without between threads.
Example
"threads":
 [

 {

"index": 0,

"intensity": 2016,

"worksize": 8,
"affine_to_cpu": false

},

{

"index": 1,
"intensity": 2016,

"worksize": 8,

"affine_to_cpu": false
},
"index": 0,
"intensity": 1600,

"worksize": 8,

"affine_to_cpu": false
},
{

"index": 1,
"intensity": 1600,

"worksize": 8,

"affine_to_cpu": false
}
],

**Comment by j205** [comment]
@Kanelus you have got a missing { before your 3rd object

**Comment by MinerGuy1111** [comment]
Tried this in a rig with 3 Vega 64s, crashes with a CL memory error. Works with auto settings but has a low hash rate.  xmr-stak-amd works fine and does ~5800h/s

40GB virtual memory at boot and 8GB ram.

**Comment by kimats** [comment]
@xmrig 
is it meaningful to have multiple treads?

**Comment by kilid** [comment]
> Same syntax with xmr-stak-amd, something like:
> 
> ```json
>     "threads": [
>         {
>             "index": 0,
>             "intensity": 1920,
>             "worksize": 8,
>             "affine_to_cpu": false
>         },
>         {
>             "index": 0,
>             "intensity": 1920,
>             "worksize": 8,
>             "affine_to_cpu": false
>         }
>     ],
> ```
> 
> or if you prefer command line options instead of config:
> 
> ```
> --opencl-platform=0 --opencl-devices=0,0 --opencl-launch=1920x8,1920x8
> ```

i keep getting this error 

[2018-10-17 22:14:44] Error CL_INVALID_BUFFER_SIZE when calling clCreateBuffer to create hash scratchpads buffer.
[2018-10-17 22:14:44] Failed to start threads.

any advice ?

**Comment by xmrig** [comment]
https://github.com/xmrig/xmrig/releases/tag/v4.0.0-beta
