### ISSUE TITLE
Vega Frontier Edition cryptonight lite- hashrate

### ISSUE THREAD

**Issue by daddyDa** [xmrig/xmrig-amd#80]
I see people using SRBminer with the same Vega Frontier Edt and get over 4k Hs per card mining cryptonight-liteV7. (link below)
https://www.youtube.com/watch?v=BnRtmxKbeLc 

the highest i could get with SRB is 3000 per card.
The highest I could get with Xmrig is 2800 (I've been using xmrig since my AMD opteron 6276 LOL). 
I have the exact same overclock setting as the guy ( this card is not yet bios mod possible yet- not sure why I have different hash rate while using SRB)

I'm using a bat file (not json.conf- sure i'm stupid everytime i try to setup the json file it does not work LOL)

Is there anyway I could boost the intensity a bit with the bat file?

my current config 
@echo off
xmrig-amd.exe --algo cryptonight-lite --variant 1 -o turtle.ingest.cryptoknight.cc:4901 -u TRTLuxEgh4DLBdoqwRdiYwHanTL6dPzS6ZsVfRW3YWCRAZu7qbAU5sHjFTp1JR1HYc1VB4SxBKdAp3rHmUiZJoPs6CKcupwPSWh -l turtle --print-time 20 -r 100
pause

By the way anyway i could add color with .bat file (not with json) when having a log file?

**Comment by noctrex** [comment]
You can specify the intensity like this (this is for my 2 cards):
`--opencl-launch 512x7,512x8`

AFAIK there is no color for text logs.

**Comment by pmancele** [comment]
Thanks for the help. And how to determine the acceptable values for a RX 570 ? for `--opencl-launch`

Pierre-Marie

**Comment by daddyDa** [comment]
@noctrex the —opencl-launch just does not work for me i tried the —open-launch and the script just does not run, got error “unsupported non-option argument”

**Comment by daddyDa** [comment]
so i got the opencl-launch working with platform 0 and opencl device for double threads. still the hash is just as before. very weird.

**Comment by noctrex** [comment]
@daddyDa just as I posted above, change the intensity values till you get the best results.
On my setup I saw speedups also when setting the system variables
set GPU_MAX_ALLOC_PERCENT=100
set GPU_SINGLE_ALLOC_PERCENT=100

**Comment by daddyDa** [comment]
thank you I already do the set GPU things. 
as far as the hash rate goes and intensity. It's weird. I mean i could understand getting somewhat lower hash rate but not like 25-30% lower with exact same setting. I have the same OC info of the guy on geek mark, exact same software he uses SRBminer which gives hime 4000hs a card (without further configuration from SRBminer) however with SRB miner i still get a bit over 3k hs like 3040 something it's not like 3500 or 3700 low. So i wonder what else could be the issue? Since i don't think it's the setting of the miner at this moment since i have tested quite a bit and it does not seem to want to go up any.

**Comment by daddyDa** [comment]
figure the dang thing out, it's just a matter of getting the FE edition working right, with new SRBminer i get 4k immediately, still playing with xmrig manual config

**Comment by pmancele** [comment]
@daddyDa "FE" version ?

**Comment by daddyDa** [comment]
VEGA Frontier Edition. Very different from 56 or 64
