### ISSUE TITLE
XMRIG vega 56 . recognise as cu 56   instead of cu64

### ISSUE THREAD

**Issue by 777crypto777** [xmrig/xmrig-amd#81]
hello. i had xmrig installed  with 2 vega 56 .   not bios modified  .    they were recognise as cu 64   whan i set xmrigup .   i used it for days at 1900hs    . now i got a third  vega 56  . i reinstalled everything  and xmrig too .  now xmrig  recognised my 3 vega 56 as cu 56 .   and lost many hs .   any explanation how i can have xmrig recognise my vegas as cu 64 .    thanks

**Comment by xmrig** [comment]
https://github.com/xmrig/xmrig/releases/tag/v4.0.0-beta
