### ISSUE TITLE
Xmrig-amd only sees my onboard intel gpu, and not my other gpus

### ISSUE THREAD

**Issue by Glentved** [xmrig/xmrig-amd#84]
I have just fiddled around with Windows 10 and AMD driver issues. It ended with that I had to make a Windows 10 system reset. 
I have 4 GPUs connected to my rig, they work and I can see them and can adjust them in AMDs driver and with overclocking software. 
Xmrig only sees my onboard graphics, which in my G4400 is not much, this is seen as Index 0.
If I specify Index 1, I get Index 1 dosent exist.
It all worked 2 days ago, before something happened with the AMD driver
Am I missing a driver or a setup thing? I have only installed Visual studio 2017, but i am not sure if it is needed

**Comment by xmrig** [comment]
Run `xmrig-amd.exe --print-platforms` to determine platform index of AMD OpenCL, then change `"opencl-platform"` option in config file.
Thank you.

**Comment by Glentved** [comment]
That was it, thank you, and thank you for the fast responce
