### ISSUE TITLE
2.6.1 - "-a cryptonight-heavy" not working

### ISSUE THREAD

**Issue by yuzi-co** [xmrig/xmrig-amd#85]
2.6.1 - "-a cryptonight-heavy" not working

exits with "Try "xmrig" --help' for more information."

**Comment by xmrig** [comment]
Sorry I was upload older release, please download again.
Thank you.

**Comment by chc-pr** [comment]
I have just downloaded 2.6.1 and tried to get it to work with cryptonight-heavy but I cannot seem to get it to work. I tried just using cryptonight as the algo but that returned invalid hashes, algo=cryptonight-heavy just crashes the startup.

**Comment by yuzi-co** [comment]
re-uploaded issue solved the problem
