### ISSUE TITLE
Compiling code and initializing GPUs..

### ISSUE THREAD

**Issue by madmossy** [xmrig/xmrig-amd#89]
Any way this could be sped up a bit, with multi gpu systems this could easily add 5-10 minutes onto just starting the miner, which when used for profit switching algo, specially if going from the likes of monero7 to cryptonight heavy where configurations will be different it can be a major pain, specially on a 13 GPU setup.

Could it not be cached after compiling once so that only needs to be loaded from the cache after, unless the configuration is changed.

**Comment by xmrig** [comment]
https://github.com/xmrig/xmrig/releases/tag/v4.0.0-beta
