### ISSUE TITLE
Only one OCL device used and detected

### ISSUE THREAD

**Issue by megadampfnudel** [xmrig/xmrig-amd#9]
I just ran into an issue with my R9 270 and my HD 6870. After I had to mess around with the drivers to get OpenCL working on the HD 6870, I started xmrig and saw that the HD 6870 was detected as OCL device but the R9 270 was not. After i checked the GPU utilisation of both cards, I recognized that the R9 270 was fully utilized but the HD 6870 was at idle. So the card that has been detected is not working, but that one that hasn't been detected is working...

Hopefully someone can help me with my problem.

I'm also uploading some screenshots, if that could help solving my problem.
![r9 270](https://user-images.githubusercontent.com/11699397/32631461-a6b1e5d6-c5a0-11e7-9751-985339da76e9.PNG)
![xmrig](https://user-images.githubusercontent.com/11699397/32631462-a6d31260-c5a0-11e7-936b-5f546d0bcb7e.PNG)
![6870](https://user-images.githubusercontent.com/11699397/32631463-a6f11bac-c5a0-11e7-86b3-90fda6af130e.PNG)
![config](https://user-images.githubusercontent.com/11699397/32631704-51cb4a2a-c5a1-11e7-90b6-a0c89929e664.PNG)

**Comment by dewminer** [comment]
The threads section of Your config file for 2 GPU should look like this:

"threads" : [ 
	{ "index" : 0, "intensity" : 896, "worksize" : 8, "affine_to_cpu" : false },
	{ "index" : 1, "intensity" : 896, "worksize" : 8, "affine_to_cpu" : false },
],

lower the intensity for HD6870 if the miner does not start

**Comment by megadampfnudel** [comment]
I have already tried this, but then two threads are running on the HD 6870, but the R9 270 is af 100% load and the HD 6870 at 0%.

**Comment by dewminer** [comment]
are you sure the thread index number was different in each line of the threads section ?
can you paste the clinfo output ?

**Comment by megadampfnudel** [comment]
Yes, i'm sure. Otherwise the miner wouldn't even start.

Here is clinfo: https://hastebin.com/ixiceqeqit.pas

**Comment by xmrig** [comment]
clinfo show only one CL_DEVICE_TYPE_GPU device available and it is `AMD Radeon HD 6800 Series`.
Definitely something wrong with drivers.

**Comment by megadampfnudel** [comment]
Ok, weird. After reinstalling the driver, getting OpenCL to work on the HD 6870 again, exactly as I have done it before it's working just fine...
But anyways thank you both for your help.

**Comment by zero1double2** [comment]
opencl-platform": 0,

Try opencl-platform": 0,1
