### ISSUE TITLE
IPBC Algo

### ISSUE THREAD

**Issue by sbash** [xmrig/xmrig-amd#90]
With the latest version, I'm using --algo=cryptonight-ipbc

I get the error "Low Difficulty Share"

FWIW, I also get this issue using beta3 of the cpu branch, while the latest release does not seem to support the --algo=cryptonight-ipbc...

**Comment by bananajamma** [comment]
Which coin?

[v2.7.3-beta](https://github.com/xmrig/xmrig-amd/releases/tag/v2.7.3-beta) changed:

* `cryptonight-lite/ipbc` replaced to `cryptonight-heavy/tube` for Bittube (TUBE).
 
List of all algorithms supported: https://github.com/xmrig/xmrig-proxy/blob/master/doc/STRATUM_EXT.md#14-algorithm-names-and-variants

**Comment by xmrig** [comment]
https://github.com/xmrig/xmrig/releases/tag/v4.0.0-beta
