### ISSUE TITLE
Vega 56/64 hashing too low on cryptonight-heavy(SUMO)

### ISSUE THREAD

**Issue by alejandrocfg** [xmrig/xmrig-amd#92]
I have two AMD cards, an AMD RX 580 and AMD RX Vega 56. Both perform great on cryptonight and cryptonightv7(~850h/s and ~1850h/s). The issue is the with Vega when mining cryptonight-heavy SUMO. First I noticed I had to change(lower) the intensity considerably on the Vega to get the miner to work but then the hash rate wont go over ~1200h/s on the other hand the 580 works perfectly having same hash rate than the other 2 algorithms without changing settings. I double checked this issue with a friend having a Vega 64 rig and he had the same issue than my Vega 56 one.

I tried the latest version and also tried compiling the latest source code having the same issue.

**Comment by krypknot** [comment]
Same issue - RX580 and RX480 are fine with settings left alone between the algo's.  
Vega64's require reduction in intensity and performance is decreased.  Attempted to compensate by adjusting power (overdriven) without success.  

Next test will be to see if any other miner apps suffer the same fate (may be a 'vega thing' vs something influenced by the code)

**Comment by xmrig** [comment]
https://github.com/xmrig/xmrig/releases/tag/v4.0.0-beta
