### ISSUE TITLE
[v2.6.1] Cryptonight-Heavy  -loss H/S with time

### ISSUE THREAD

**Issue by bluemelatonin** [xmrig/xmrig-amd#93]
Hello,

I have an isue on cryptonight-heavy algo, i lost many H/S after a few hours. sometimes divided by two. if i stop an relaunch imediatly the miner, my H/S back to normal state. 

Any idea ? 

My config file : 

            "index": 0,  //  RX550 - 2 GB ~ 244h/S on cryptonught-heavy
            "intensity": 448,
            "worksize": 8,

            "index": 1, //  RX550 - 2 GB 244h/S on cryptonught-heavy
            "intensity": 448,
            "worksize": 8,

            "index": 2, //  RX570 - 4GB ~710h/S on cryptonight-heavy
            "intensity": 960,
            "worksize": 8,

            "index": 3, //  RX570 - 4GB  ~710h/S on cryptonight-heavy
            "intensity": 960,
            "worksize": 8,

**Comment by xmrig** [comment]
https://github.com/xmrig/xmrig/releases/tag/v4.0.0-beta
