### ISSUE TITLE
The miner stops mining after several hours of work.

### ISSUE THREAD

**Issue by technotrance911** [xmrig/xmrig-amd#94]
Hello!
The miner stops mining after several hours of work.
My system is:
- Windows srv 2008 R2
- Crimson-ReLive-Beta-Blockchain-Workloads-Aug23
- Xmrig Amd 2.6.1 (But issue also present in other versions. I tried v2.6.0-beta1 and v2.5.2)
- Intel HD Graphics 4600 (Integrated graphics on the motherboard, connected to the monitor.)
- AMD Radeon R7 360 2gb (A card that mining sumokoin.)
My bat file is:
`xmrig-amd.exe -o mine.sumo.fairpool.xyz:5555 -u <my wallet+worker> -p x -a cryptonight-heavy -k`
Also I tried:
`xmrig-amd.exe -o mine.sumo.fairpool.xyz:5555 -u <my wallet+worker> -p x -a cryptonight-heavy -r 10 -R 10`
I suspect that the problem is related to the fact that my system uses a integrated video card. But I can not disable the integrated card, it is needed.
![sumo](https://user-images.githubusercontent.com/38863487/39439483-2df5d596-4cc1-11e8-8e12-9be07cbb27b2.png)
If the miner to restart manually, the mining continues. But after a few hours also stops.

**Comment by deweler** [comment]
this is a "fair" pools problem not the miner problem ... i have rigs conected with miningrentals .. they show real time 16KH .. on "fairpool" only 9 ... i think they like to Cheat people up

**Comment by technotrance911** [comment]
I doubt that the pool is to blame. Other rigs with cards RX460 and RX560 are stable.

**Comment by NmxMilk** [comment]
I have also noticed this problem while mining monero (v7) under windows 10 with version 2.5.2:
![xmrig hs drop to zero](https://user-images.githubusercontent.com/30717667/40890570-76a87b96-6778-11e8-97e0-f4414e8df334.png)

If i restart it reworks normally:
![xmrig normal](https://user-images.githubusercontent.com/30717667/40890588-9da14606-6778-11e8-83f5-f4c69f45d4d1.png)

One other problem I noticed compared to previuous version (pre-fork) is higher number of rjected shared (2 to 4%).
Would be nice if dev gave feedback.

**Comment by xmrig** [comment]
https://github.com/xmrig/xmrig/releases/tag/v4.0.0-beta
