### ISSUE TITLE
Miner stops immediately after starting with 'Press any key to continue' 2.5.2

### ISSUE THREAD

**Issue by seanspotatobusiness** [xmrig/xmrig-amd#95]
Operating System
	Windows 10 Pro 64-bit
CPU
	Intel Celeron G3930 @ 2.90GHz	
RAM
	4.00GB Single-Channel Hynix @ 1066MHz (15-15-15-35)
Motherboard
	ASRock H110 Pro BTC+
GPUs
	2048MB ATI Radeon RX 550 Series (Gigabyte)
	2048MB ATI Radeon RX 550 Series (XFX Pine Group)
	2048MB ATI Radeon RX 550 Series (ASUStek Computer Inc)

Config file:
[config.json.txt](https://github.com/xmrig/xmrig-amd/files/1962324/config.json.txt)

Miner output:
` * VERSIONS:     XMRig/2.5.2 libuv/1.19.2 OpenCL/2.0 MSVC/2017
 * CPU:          Intel(R) Celeron(R) CPU G3930 @ 2.90GHz x64 AES-NI
 * ALGO:         cryptonight, donate=1%
 * POOL #1:      at01.supportxmr.com:7777
 * POOL #2:      xmr-eu2.nanopool.org:14444
 * POOL #3:      fr.minexmr.com:7777
 * POOL #4:      frankfurt-1.xmrpool.net:7777
 * COMMANDS:     hashrate, pause, resume
[2018-04-30 22:55:54] compiling code and initializing GPUs. This will take a while...
Press any key to continue . . .`

**Comment by xmrig** [comment]
https://github.com/xmrig/xmrig/releases/tag/v4.0.0-beta
