### ISSUE TITLE
About Skein Algorithm

### ISSUE THREAD

**Issue by dev-jbam** [xmrig/xmrig-amd#96]
Hello. 
I really appreciate using this source code. 
Now I am converting this source code for me.

But I have a problem with skein algorithm. When I run this skein it is not working well.
So I just ran this algorithm only. And I got different results with the same nonce value though I fixed input. Could you help me?
When I use variant 1 for Monero v7. It is working different way what I thought. 

Is there any issue for skein algorithm?

If you answer this question, It would be great for me.
Thanks, Regards 
Joon

**Comment by dev-jbam** [comment]
It seems my machine problem. 
I am using iMac 2017 with Radeon Pro 570 GPU
In the Skein algorithm, variable t and p are corrupted when it goes into the function. 
So I initialize again just before the function. 

It works fine thanks.

**MY clinfo information, If you has the same problem I would recommend to initialize and check memory corruption.


Device Name                                     AMD Radeon Pro 570 Compute Engine
  Device Vendor                                   AMD
  Device Vendor ID                                0x1021c00
  Device Version                                  OpenCL 1.2
  Driver Version                                  1.2 (Jan 30 2018 12:29:15)
  Device OpenCL C Version                         OpenCL C 1.2
  Device Type                                     GPU
  Device Profile                                  FULL_PROFILE

 NULL platform behavior
  clGetPlatformInfo(NULL, CL_PLATFORM_NAME, ...)  Apple
  clGetDeviceIDs(NULL, CL_DEVICE_TYPE_ALL, ...)   Success [P0]
  clCreateContext(NULL, ...) [default]            Success [P0]
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_DEFAULT)  Success (1)
    Platform Name                                 Apple
    Device Name                                   AMD Radeon Pro 570 Compute Engine
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CPU)  Success (1)
    Platform Name                                 Apple
    Device Name                                   Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_GPU)  Success (1)
    Platform Name                                 Apple
    Device Name                                   AMD Radeon Pro 570 Compute Engine
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ACCELERATOR)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CUSTOM)  Invalid device type for platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ALL)  Success (2)
    Platform Name                                 Apple
    Device Name                                   AMD Radeon Pro 570 Compute Engine
    Device Name                                   Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
        NOTE:   your OpenCL library only supports OpenCL 1.0,
                but some installed platforms support OpenCL 1.2.
                Programs using 1.2 features may crash
                or behave unexpectedly

**Comment by xmrig** [comment]
https://github.com/xmrig/xmrig/releases/tag/v4.0.0-beta
