### ISSUE TITLE
API seems to be broken in 2.6.1

### ISSUE THREAD

**Issue by sooth** [xmrig/xmrig-amd#97]
Running the below command:
`xmrig-amd -o stratum+tcp://haven.ingest.cryptoknight.cc:5532 -p tester -u %VALID_ADDY% --donate-level 1 --print-time 5 -a cryptonight-heavy --api-access-token test --api-port 4028 --api-worker-id tester`

Yields
`root@simpleminer:~# curl -H "Authorization: Bearer test" http://localhost:4028/
curl: (7) Failed to connect to localhost port 4028: Connection refused`

`root@simpleminer:~# sudo netstat -peanut
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       User       Inode       PID/Program name
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      0          17651       666/sshd
tcp        0      0 192.168.2.92:22         192.168.3.1:34010       ESTABLISHED 0          3869309     8804/sshd: miner [p
tcp        0      0 192.168.2.92:54536      195.201.82.83:5532      ESTABLISHED 1000       4116494     12792/xmrig-amd
tcp        0      0 192.168.2.92:58452      104.23.241.254:443      TIME_WAIT   0          0           -
tcp        0      0 192.168.2.92:58458      104.23.241.254:443      TIME_WAIT   0          0           -
tcp        0    304 192.168.2.92:22         192.168.3.1:41490       ESTABLISHED 0          3883558     15555/3
tcp        0      0 192.168.2.92:41236      104.23.240.254:443      TIME_WAIT   0          0           -
tcp        0      0 192.168.2.92:58450      104.23.241.254:443      TIME_WAIT   0          0           -
tcp6       0      0 :::22                   :::*                    LISTEN      0          17653       666/sshd
udp        0      0 0.0.0.0:68              0.0.0.0:*                           0          17540       638/dhclient
`

**Comment by xmrig** [comment]
https://github.com/xmrig/xmrig/releases/tag/v4.0.0-beta
