### ISSUE TITLE
Error CL_MEM_OBJECT_ALLOCATION_FAILURE

### ISSUE THREAD

**Issue by Meacho** [xmrig/xmrig-amd#99]
When I load the start command I get the following continuous error:
ERROR CL_MEM_OBJECT_ALLOCATION_FAILURE when calling clEnqueueNDRangeKernel for Kernel 0.
I have 2 AMD Radion R9 200s 3GB core 1070 MHz.
Any idea how to fix this issue?

![image](https://user-images.githubusercontent.com/15829136/39658468-356e5a10-5058-11e8-9011-43d71931047c.png)

**Comment by k0ste** [comment]
Use Linux or set swap to 16G.

**Comment by xmrig** [comment]
https://github.com/xmrig/xmrig/releases/tag/v4.0.0-beta
